### ISSUE TITLE
Clearing stage doesn't always react the UI

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#10]
* seattle
* edit Green Lake to Green Lake1
* UI reacts; refresh
* UI SSR to old state then reacts
* clear stage from view menu
* bug: UI does not react

**Comment by khardenstine** [comment]
Cannot reproduce

**Comment by dustingetz** [comment]
COuldnt rep in seattle but repped in todomvc (todomvc had to be repaired first)
![bug](https://user-images.githubusercontent.com/124158/35349524-27dfc4f4-0109-11e8-8558-f7d2afe4c5ef.gif)

**Comment by khardenstine** [comment]
Pushing reactivity throughout hc.browser is still unfinished.  user-fns still accept unreactive lists of entities.  Entity's still returns raw values from ILookup, yet have equality defined by db/id.

See #7

**Comment by khardenstine** [comment]
Fixed with #7
