### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by eggsyntax** [hyperfiddle/hyperfiddle#100]
Hey Dustin,

Just wanted to let you know you've got a broken link in the README. In "#3, Data driven UI", you have this line: `Above EDN definition, rendered. Pink highlights indicate a link to another fiddle. click here for the live fiddle.` Clicking the link takes you to a page showing the following:

```
malformed entity param -- {:params [#entity["$" nil]]}
Assert failed: missing fiddle-id
fiddle-id
nil
```

Thanks for your work on Hyperfiddle!

**Comment by dustingetz** [comment]
Hi Egg thank you for the report I fixed the link and here it is: <http://dustingetz.hyperfiddle.net/ezpmaWRkbGUtaWQgMTc1OTIxODYwNDU0MTgsIDpjb2RlLWRhdGFiYXNlIG5pbH0,>

**Comment by eggsyntax** [comment]
Thanks!
