### ISSUE TITLE
CLJS tests should compile with shadow, remove boot from hyperfiddle

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#1014]
I cleaned up the unit tests, remaining failures are in contrib.cljs-eval and hyperfiddle.readers (failing due to broken cljs-eval unit tests). This is because cljs-eval is coded shadow-specific.

```
Testing contrib.eval-test

ERROR in (test-eval-string) (Error:NaN:NaN)
expected: (= 1 (eval-expr-str! "1"))
  actual: #object[Error Error: find-ns-obj not supported for target ]

ERROR in (test-eval-string) (Error:NaN:NaN)
expected: (= 2 ((eval-expr-str! "(constantly 2)")))
  actual: #object[Error Error: find-ns-obj not supported for target ]
```
This error is coming out of cljs compiler when invoked by boot test-cljs. I confirmed eval-expr-str! works at runtime because fiddle/renderer uses it and works.

**Comment by dustingetz** [comment]
https://github.com/crisptrutski/boot-cljs-test/blob/master/src/crisptrutski/boot_cljs_test.clj

**Comment by ggeoffrey** [comment]
What does `cljs-eval is coded shadow-specific` mean in this context? Does it mean ShadowCLJS got it's own implementation of `cljs-eval` and is forcing its usage at runtime?

Also, would [this](https://gist.github.com/mfikes/66a120e18b75b6f4a3ecd0db8a976d84) help?

**Comment by dustingetz** [comment]
This line of code is shadow specific https://github.com/hyperfiddle/hyperfiddle/blob/master/src/contrib/eval_cljs.cljs#L16
