### ISSUE TITLE
ordered-map string serialization is broken

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#1018]
![image](https://user-images.githubusercontent.com/124158/79674137-462f0280-81ae-11ea-84a3-b0829053c139.png)

**Comment by Invocatis** [comment]
https://github.com/hyperfiddle/hyperfiddle/commit/d1be73f0c2907dd57bd0cd0d9c3f28007b061ce5

**Comment by Invocatis** [comment]
Was an issue when calling toString (which is not used by transit).

The order and values were being stringified with str. Using pr-str now.
