### ISSUE TITLE
Common fiddles I replicate into userland a lot

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#104]
- [ ] system/options-by-ns
```
[:find (pull ?e [:db/id :db/ident]) :in $ ?ns :where 
 [?e :db/ident ?v]
 [(namespace ?v) ?ns]]
```
- [ ] system/entity.ident (pull `[[:db/id :db/ident]]`)
- [ ] system/schema-exporter
```
[:find [(pull $ ?attr [:db/id :db/ident :db/valueType :db/cardinality :db/doc :db/unique :db/isComponent :db/fulltext]) ...] :in $ :where
 [$ :db.part/db :db.install/attribute ?attr]]

(fn [result]
  (let [whitelist #{"buinsess" "driver-license" "document" "business" "passport" "national-id" "person-info" "communication"}]
    [:pre
     (->> result
          (filter (comp whitelist namespace :db/ident))
          #_(map (comp namespace :db/ident))
          #_set
          js/pprint-str)]))
```
- [ ] fiddle exporter
```
[:find (pull $repo ?e [:db/id :fiddle/name]) :in $repo :where
 [$repo ?e :fiddle/name]]
```

**Comment by khardenstine** [comment]
Schema exporter seems like generic features to add to our table/form ui.
- "Export to edn" button at the top of the table (csv and excel too)
- client side filters on columns

Not sure what fiddle exporter is, that query just looks like the show all fiddles:
![image](https://user-images.githubusercontent.com/7741805/36854988-6f2120e4-1d40-11e8-86b1-0fe0e70dfba0.png)

**Comment by dustingetz** [comment]
too old, will come up organically
