### ISSUE TITLE
picklist component needs to style for ::hf/is-invalid prop

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#1041]

**Comment by Invocatis** [comment]
React typeahead already supports the `is-invalid` prop, and reagent automatically strips namespaces from props. So this is already supported 💯 💯 

![image](https://user-images.githubusercontent.com/22183930/87177005-ee81ce00-c2a8-11ea-9373-f046e36df633.png)
![image](https://user-images.githubusercontent.com/22183930/87176922-ca25f180-c2a8-11ea-8a37-7ebb13b35310.png)

Additional styling can be added as such,

```css
.rbt-input.is-invalid {
  background-color: pink;
}
```

Substituting `.rbt-input` with `.form-control` will also work
