### ISSUE TITLE
Attribute security is broken

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#1043]
Regression introduced here, this logic is ????
![image](https://user-images.githubusercontent.com/124158/85228154-b9701300-b3af-11ea-8d93-73eeed3ad081.png)

**Comment by dustingetz** [comment]
`#(and @(r/track context/component? ctx))`

**Comment by Invocatis** [comment]
See this [commit](https://github.com/hyperfiddle/hyperfiddle/commit/01f36269f56884d4147c6ac1c7a04b85d3aa0635#diff-0055e8215729ed27280d2babc93814fa)

**Comment by Invocatis** [comment]
This line was to allow empty components to be editable, however it seems to have also allowed the editing of transacted component idents. Logic will be needed to understand when a component has been filled.

**Comment by Invocatis** [comment]
This is also the logic that was likely desired
```
 #(and (not (context/component? (:hypercrud.browser/parent ctx)))
                                        (or %
                                          (not @(r/track writable-entity? ctx))
                                          (not @(r/track hf/subject-may-edit-attr? ctx)))))
```

**Comment by Invocatis** [comment]
For the purpose of unblocking rosie, removing this line will be sufficient. However, this will cause creation of components not possible by editing the attributes
