### ISSUE TITLE
Boolean regression related ::to hf/view-change!

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#1053]
In this screenshot false is retracted but true is not added.

Luke It wasn't including the old/new pair
Dustin Getz Ok, this is a deeper bug then
Luke So I think it was doing change from false to nil. instead of change from false to true
This is partially what I was speaking to when I said the ideals will end up being coupled with the transactions being produced
Which is going to happen either way really

![image](https://user-images.githubusercontent.com/124158/86019734-f4e49000-b9f4-11ea-8536-cf4a63f42fab.png)

**Comment by Invocatis** [comment]
Properly parameterized on-change with `old value` to `new value`.

In this case, it was simply calling `(on-change (not v) v)`
