### ISSUE TITLE
Select Box Rendering Issues

### ISSUE THREAD

**Issue by Invocatis** [hyperfiddle/hyperfiddle#1054]
When rendering [fiddle](http://localhost:8080/:user.demo.seattle!community/17592186045440) in Seattle Demo, select box rendering fails with `Invalid route nil - failed: map? spec: :hyperfiddle/route`.

Repro Steps

1.) Load Seattle Demo : `(use 'dev) (load-demo 'user.demo.seattle)`
2.) Navigate to [fiddle](http://localhost:8080/:user.demo.seattle!community/17592186045440)

![image](https://user-images.githubusercontent.com/22183930/86172893-13c64d80-baed-11ea-9899-ba503f7775b2.png)

![image](https://user-images.githubusercontent.com/22183930/86172922-22146980-baed-11ea-93f6-1b52d8590fcb.png)

**Comment by dustingetz** [comment]
This is working now , right? 
![image](https://user-images.githubusercontent.com/124158/86182440-f9e13680-bafd-11ea-9c81-16879b3a97db.png)
