### ISSUE TITLE
"cant auto-transact if we started dirty" - need visual indicator of this in userland

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#107]
Super confusing when it happened on dustingetz.com. There's also a bug or something that got me into a dirty state in the first place. I have probably lost a lot of edits over this.

`(runtime/dispatch! rt [:disable-auto-transact]) ; ; should serialize this to localStorage too`

**Comment by khardenstine** [comment]
Auto-tx is now always on in non-ide cases
