### ISSUE TITLE
hello-world pickers broken

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#1072]
Cardinality is wrong on this tx

```clojure
[[:db/retract [:dustingetz/email "alice@example.com"] :dustingetz/gender :dustingetz/female] 
 {:db/id [:dustingetz/email "alice@example.com"], :dustingetz/gender [:dustingetz/female]}]
```
emitted by these radios
![image](https://user-images.githubusercontent.com/124158/87883259-1f15e600-c9d4-11ea-890e-e42601d19fed.png)

Also, the selected state is not showing

**Comment by dustingetz** [comment]
Also here http://localhost:8080/:user.hello-world!submission-detail/~entity('$',(:dustingetz!email,'alice@example.com'))

**Comment by dustingetz** [comment]
The undefined symbols here is probably part of the problem
![image](https://user-images.githubusercontent.com/124158/87886386-7030d480-c9ea-11ea-96ef-cd7662e09af2.png)

**Comment by Invocatis** [comment]
In the selection code, we are piggy backing off the table rendering code to create our table picker.
We achieve this by using the options-ctx, not the values of options. This means that FindRel and FindTuple can be passed as the picker options. Each row under these queries has a tupled key, which causes the error in emitted tx and the unselected states.

**Comment by Invocatis** [comment]
```(defn context-of
  [ctx fiddle-ident]
  (let [link-ref (from-result (data/select+ ctx fiddle-ident))
        link-ctx (from-result (context/refocus-to-link+ ctx link-ref))
        [occluded-ctx initial-route] (from-result (context/build-route-and-occlude+ link-ctx link-ref)) ; ":link/fiddle required"
        options-pid (context/build-pid-from-link ctx link-ctx initial-route)
        ctx (from-result (base/browse-partition+ (context/set-partition occluded-ctx options-pid)))]
    ctx))

(defn resolve-options
  [ctx props]
  (condp some [(unqualify (contrib.datomic/parser-type (hf/qfind ctx)))]
         #{:find-coll :find-scalar} (hf/data ctx)
         #{:find-rel :find-tuple} (mapv #(get % (::hf/option-element props 0))
                                        (hf/data ctx))))

(defn options-of
  [ctx fiddle-ident props]
  (resolve-options (context-of ctx fiddle-ident) props))```
