### ISSUE TITLE
edit of :keyword :one inside a table emits a broken tx

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#1074]
http://localhost:8080/:user.hello-world!submission-detail/~entity('$',(:dustingetz!email,'alice@example.com'))

Editing the following keyword emits a broken tx

![image](https://user-images.githubusercontent.com/124158/87883446-6e104b00-c9d5-11ea-9f98-da4800f3f858.png)

```
[#:dustingetz{:type :dustingetz/gender1} 
 [:db/retract nil :dustingetz/type :dustingetz/gender]]
```
Tx should be like
```
[{:db/ident :dustingetz/male :dustingetz/type :dustingetz/gender1}
 [:db/retract :dustingetz/male :dustingetz/type :dustingetz/gender]]
```

**Comment by Invocatis** [comment]
Issue was in ideals. Did not know how to parse keyword as identifier. Now assuming keyword e is a :db/ident

```
(keyword? e)
          {:db/ident e}
```
