### ISSUE TITLE
(s/coll-of keyword?) maps to wrong datomic schema

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#1079]
`(s/def ::locations (s/coll-of keyword?))` is mapping to :ref :many 

```
(defn from-spec [attr]
  (when attr
    (let [{:keys [name type predicate]} attr]
      {:db/ident       name
       :db/valueType   (case type
                         (:hyperfiddle.spec/coll :hyperfiddle.spec/keys) :db.type/ref            ; broken
                         (type-of predicate))
       :db/cardinality (if (= :hyperfiddle.spec/coll type) :db.cardinality/many :db.cardinality/one)})))
```

**Comment by ggeoffrey** [comment]
What should it map to ?

**Comment by ggeoffrey** [comment]
Sorry I commented too quickly. I understand the issue.

**Comment by dustingetz** [comment]
This is a collection of keywords
:many :keyword

**Comment by dustingetz** [comment]
This is blocking Rosie, we can't remove a fake datomic schema without this
`http://localhost:8081/:swinged.rosie.subs!sub-display/~entity('$',(:sub!id,~uuid,'5d41b392-49fe-4474-8123-040ad8cd63d7'))`
