### ISSUE TITLE
Search picklists send option records into route, not lookup refs

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#1080]

**Comment by ggeoffrey** [comment]
@dustingetz you might want to check this one and ensure it's not breaking existing fiddles. @Invocatis and I talked about it and this seems to be ok.

**Comment by ggeoffrey** [comment]
@Invocatis I'm getting this error, arising from this change in the above commit:
```diff
- (into [] (concat selected (remove (set selected) vals))))	  
+ (into [] (sort-by first (concat selected (remove (set selected) vals)))))
```
<img width="1280" alt="Capture d’écran 2020-08-04 à 11 26 47" src="https://user-images.githubusercontent.com/3972968/89277972-cbe39a80-d645-11ea-9913-6e7e24c2b9f4.png">

**Comment by ggeoffrey** [comment]
My previous commit on this issue is nonsense. The above message follows this nonsense. Please ignore it.

**Comment by ggeoffrey** [comment]
Fixed by 5c8b1a64

**Comment by ggeoffrey** [comment]
merge-route should behave differently for defaults + hydrated-defaults.
If a hydrated result is `nil`, it should take precedence over `defaults`. 
Example : pulling a non-existing lookup ref returns nil. We should keep nil and not return the lookup ref

**Comment by dustingetz** [comment]
This is an issue again in both master and the version in prod at Rosie

**Comment by ggeoffrey** [comment]
It was mostly a user land issue.
Specs are parsed on both clj and cljs. They are not shipped over the wire anymore.
Given this code:

```clojure
(ns foo
  (:require [clojure.spec.alpha :as s]))

(s/fdef foo :args (s/cat :attr ref?))  ; `ref?` doesn’t exist
```
Compilation would have failed on the JVM, but in JS `ref?` is `undefined`, which is of course not a `:db.type/ref`.
Vars don’t exists in CLJS, so spec parsing is implemented in a different way.

I made the parser stricter:
- asserting and throwing if the symbolic predicate cannot be resolved, symptomatic of a missing require or typo.
- issuing a warning when a `:db/valueType` can’t be infered from the given predicate.

<img width="487" alt="Capture d’écran 2020-09-08 à 10 57 42" src="https://user-images.githubusercontent.com/3972968/92457609-b58ca980-f1c4-11ea-8dfc-c3566942e6ff.png">
