### ISSUE TITLE
Migrate Rosie wrapper fiddles to search params

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#1084]
Rosie currently has an anti-pattern, in the below screenshot, the sub name should actually be a gray typeahead that binds to the datomic-arg route param. This cancels out another layer of wrapper fiddles/iframes in Rosie.

![image](https://user-images.githubusercontent.com/124158/89127656-2998ab00-d4bd-11ea-9cd9-fc7edd94fe1b.png)

**Comment by dustingetz** [comment]
Here is a more complicated example: the admin Anna Chavez (datomic-arg) should be gray typeahead, but that param is an input to both queries on this page. I guess the iframes need to be denested (made siblings as in new HFQL) in this case so that they share the search params?

![image](https://user-images.githubusercontent.com/124158/89127685-8300da00-d4bd-11ea-96fb-00183afc98f0.png)

**Comment by dustingetz** [comment]
![image](https://user-images.githubusercontent.com/124158/89128103-30c1b800-d4c1-11ea-813b-99909917895b.png)

**Comment by dustingetz** [comment]
@ggeoffrey Flattening out ::datomic-args will result in approx 25% reduction in LOC of Rosie, I think

**Comment by dustingetz** [comment]
Here's another one in Rosie that is hacked differently ... the school name could be gray and base-pay-rates becomes a query, not a pull

![image](https://user-images.githubusercontent.com/124158/89131832-a63b8180-d4dd-11ea-9751-e3bd3cbc18ba.png)

**Comment by ggeoffrey** [comment]
What if the default formula passed the whole parent route to iframes?
Setting `:datomic-args` (or whatever it's named now) would make it available to all frames, except if it's shadowed by some existing iframe-specific route param

**Comment by dustingetz** [comment]
That is interesting question but in the case described by the issue, all of the iframes can be removed, only one query per page is needed.

**Comment by ggeoffrey** [comment]
60ce1184 should solve this one
