### ISSUE TITLE
Picker on datomic-args parameter doesn't work

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#1088]
This sub picker doesn't work – the picker emits the changed lookup ref and routes it to the server (visible in the edn view) but then gets controlled back to the previous state. Perhaps has to do with datomic-args tech debt?

![image](https://user-images.githubusercontent.com/124158/89713507-1a56a900-d966-11ea-85a6-ad391d274df8.png)

**Comment by ggeoffrey** [comment]
Could you share the `hf/render` implementation for this picker?
