### ISSUE TITLE
Auto transact not working at all on dustingetz.com

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#109]
* Before this was localStorage.clear() followed by refresh. 
* In between the commands I made a 1char change and then blurred.

![image](https://user-images.githubusercontent.com/124158/36992583-5d2ec256-2079-11e8-8e6e-30c66b0876b7.png)

**Comment by dustingetz** [comment]
#107

**Comment by khardenstine** [comment]
Auto-tx is now always on in non-ide cases
