### ISSUE TITLE
Don't generate [:db/add ""]

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#110]
This is the main cause of the two-datoms error that busts the page

**Comment by dustingetz** [comment]
This area hasn't been touched since 2016 and it needs to be paved. I made it so update-entity accepts nil, and stringy widgets normalize empty->nil, and it only generates a retract. A remaining issue is that the shadow-fiddles now generate fake retracts, and it can generate double retracts which is a broken tx.

**Comment by dustingetz** [comment]
This retract is illegal but if you comment out either of the retracts it becomes legal.
```
{nil
 {#uri "datomic:free://datomic:4334/sandbox"
  ([:db/retract 17592186045886 :fiddle/renderer "a"]
   [:db/retract 17592186045886 :fiddle/renderer "b"])}}
```

**Comment by dustingetz** [comment]
When this happens, the error is quite intimidating
![image](https://user-images.githubusercontent.com/124158/39214007-1b088864-47e1-11e8-9ac5-413b4c7327ca.png)

**Comment by khardenstine** [comment]
The only realistic improvement I see is to get rid of the topnav.
We can detect the nil partition's errors in hf.ide/view and either:
- route the view to go through the fatal error path
- just omit the topnav and let the user's browser-ui display the error

**Comment by khardenstine** [comment]
> This area hasn't been touched since 2016 and it needs to be paved. I made it so update-entity accepts nil, and stringy widgets normalize empty->nil, and it only generates a retract. A remaining issue is that the shadow-fiddles now generate fake retracts, and it can generate double retracts which is a broken tx.

There is a ticket capturing this general sentiment and the related specific problematic behaviors:
https://github.com/hyperfiddle/hyperfiddle.net/issues/18

**Comment by dustingetz** [comment]
Pasting the exact same stage as above no longer generates a datoms conflict error ???????

**Comment by dustingetz** [comment]
Yes it does, the problem is the dbid was not on the page i guess. This repros:

```
{nil
 {#uri "datomic:free://datomic:4334/~dustin.getz"
  [[:db/add "-2017569654" :fiddle/ident :test11112]
   [:db/add "-2017569654" :fiddle/type :query]
   [:db/add "-2017569654" :fiddle/entrypoint? true]
   [:db/retract "-2017569654" :fiddle/renderer "b"]
   [:db/retract
    "-2017569654"
    :fiddle/renderer
    "[:div {:class class} [:h3 (some-> ctx :hypercrud.browser/fiddle deref :fiddle/ident name)]\n (hypercrud.ui.control.link-controls/anchors [] false ctx :class \"hyperfiddle-link-index\")\n [hypercrud.ui.control.markdown-rendered/markdown\n  (some-> ctx :hypercrud.browser/fiddle deref :fiddle/markdown) ctx]\n (hypercrud.ui.control.link-controls/iframes [] false ctx)]"]]}}
```

**Comment by dustingetz** [comment]
New repro steps: 

1. New fiddle
2. Alter the renderer and transact
3. delete renderer, dont transact
4. relete renderer again
