### ISSUE TITLE
typeaheads must understand s/cat routes

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#1101]
`(hf/swap-route! ctx assoc (::hf/needle-key props) s)` "Vector's key for assoc must be a number."

**Comment by ggeoffrey** [comment]
An unblocked would be to use the attribute index as `::hf/needle-key` in user land.
`::hf/needle-key 1` (first arg)

We need to figure out an abstraction

**Comment by ggeoffrey** [comment]
Ah nevermind, I already had one
```diff
- (hf/swap-route! ctx assoc (::hf/needle-key props) s)
+ (hf/swap-route! ctx utils/assoc-in-route [(::hf/needle-key props)] s)
```

`assoc-in-route` reflects on the fiddle's function symbol (ƒ) and rewrite the path by replacing s/cat names by their respective numeric index.

NOTE: it's difficult to abstract `assoc-in-route` away in `hf/swap-route!` as it would bring dependencies in `hf.api`.
