### ISSUE TITLE
Should *user* be auto provided to queries that ask for it, or should we force the formula to specify it?

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#111]
If the formula specifies it, it means we need at least one link-blank to get the chain started (e.g. the index). Also impacts routing: 
* if all datomic args must be specified in formula, do we want the userid on the URLs, or do we want the router to add the user-id to the urls
* If special datomic args can be provided outside the formula, then urls do not need to include userid

**Comment by dustingetz** [comment]
If an adminstrator wants to impersonate a user, it is straightforward when user is in formulas.

**Comment by khardenstine** [comment]
Are all these concerns captured by the session api #130?
