### ISSUE TITLE
assoc-in-route for invalid needle-key (not in spec) corrupts route

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#1121]
For now we can resolve by adding error handling to assoc-in-route

This is the case for the gallery's ref-many picker currently (the gallery src is in a bad state)

repro:
1. Fiddle `(s/fdef foo :args (s/cat))`
2. Set a picker with ::hf/needle-key :needle 
3. assoc-in-route will choose 0 as the index

How does this fn even work? It doesn't seem to do the right thing, I might be tired
```clojure
(defn- assoc-in-route [route path value]
  (let [[position :as path] (-> path
                                (update 0 position-in route)
                                (update 0 inc))]
    (if (<= position (count route))
      (assoc-in route path value)
      (assoc-in (expand-route-to position route) path value))))
```

**Comment by ggeoffrey** [comment]
It works by rewriting attribute-based path to a position based path. 
The bug is in `position-in`
```
(defn position-in [key [f & args]]
  (when-let [spec (s/get-spec f)]
    (let [index-of  #(.indexOf %2 %1)
          spec-args (-> spec (spec/parse) (spec/args-spec))
          names     (spec/names spec-args)]
      (assert (= ::spec/cat (:type spec-args)) (str "Please provide an s/cat args spec for this fiddle. " f))
      (->> (index-of key (vec names))))))
```
If not found, `.indexOf` returns -1, which is then incremented to 0, which is incorrect.
I think the assertion should account for a missing key and throw.

**Comment by dustingetz** [comment]
Thanks
