### ISSUE TITLE
server error should print full stack trace to page

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#1137]
![image](https://user-images.githubusercontent.com/124158/102492932-63b7b300-4040-11eb-8d46-ec2c333b22f4.png)

**Comment by ggeoffrey** [comment]
<img width="827" alt="Capture d’écran 2020-12-18 à 11 48 23" src="https://user-images.githubusercontent.com/3972968/102606797-9e484b00-4127-11eb-98cc-29e78f35ac7d.png">
