### ISSUE TITLE
Shadow links buggy when changing from pull to query and links were already shadowed

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#116]
It renders in ways that don't make any sense because I guess the system provides paths wrong or no longer provides paths or something. The way out is to retract shadowed sys links, so that way things at least start making sense. I will add repro later but this is triggered by migrating the invoicing app to thread the current user through each page, which turns pulls into queries.

**Comment by khardenstine** [comment]
These actions have basically the same problems too:
- changing the order of find elements in a query
- removing a ref attribute from a pull expression (query or entity)
- when a request fails, the auto-links function cannot generate anything

Shadow links needs a fairly complete overhaul
