### ISSUE TITLE
"cant branch from past" + auto-transact is undefined

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#122]
I'm not sure what it did.

**Comment by khardenstine** [comment]
I dont think we send up local-basis on transact, so it likely just went through fine

**Comment by dustingetz** [comment]
It's on a d/with (popoer open). I think i saw it somehow know to turn off auto-transact since the stage is dirty now (it gets hung on a non-nil branch without any open popover to stage/discard)
