### ISSUE TITLE
:blank fiddles with buttons need messy bindings

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#123]
* link-blank often wants to have buttons, the buttons need a database in scope, but setting this in a binding makes things the wrong color, so the database has to be bound at the last second in N places (formula AND txfn, foreach button). Alternatively, the logic doing the coloring could inspect different parts of ctx to determine color, but that gets weird because things like table headers don't have an entity in scope to get the color (though the URI has already been set in the ctx at the find-element stage). A solution that colors a button without coloring everything around it could be link/props - which sets the color per link, the correct granularity - but might as well just duplicate it in the formula and txfn at that point, its not really a big win, other than you would actually see the link colored correctly if done as props, and one-off formula tweaks do not color the link.

**Comment by khardenstine** [comment]
Can't we just unbind uri at the top of the table and form hierarchy? [Here](https://github.com/hyperfiddle/hyperfiddle/blob/master/src/hypercrud/ui/result.cljs#L42) or at the top of result-renderer (also would need to hit up the request side).

If that is too ugly and immoral we could add a different binding `#(assoc % :hypercrud.browser/default-db "$")`
So in the one place we want to fall back to that (auto-entity-from-stage) we could.

**Comment by dustingetz** [comment]
Is this still true?

**Comment by khardenstine** [comment]
Is this the only thing preventing a formal archiving of `:fiddle/bindings`?

**Comment by dustingetz** [comment]
This is done with formula now
