### ISSUE TITLE
fiddle/name -> fiddle/ident

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#124]
- [ ] Migrate existing fiddles with db/ident to fiddle/ident; db/ident is for compile time enumerated query constants
- [ ] Migrate existing fiddle/name strings to namespaced idents and retire fiddle/name.

Rationale: Real apps have too many fiddles for human names. They are like java classes in a package, e.g. a namespaced keyword. Turns out that identifying fiddles as a keyword is useful in routing and probably other places (a typeahead picker for link/fiddle?). There is a path for future work in structuring the namespaces better, using `::` to auto-qualify names, stuff like that.

Sets up https://github.com/hyperfiddle/hyperfiddle/issues/117

**Comment by khardenstine** [comment]
:db/ident has been added.
:fiddle/name is now second class, and just needs removed once all fiddles have a fiddle/ident.
The remaining work is captured by #46
