### ISSUE TITLE
call stack exceeded on sync-to-storage

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#144]
localStorage.clear() also causes the infinite loop

![image](https://user-images.githubusercontent.com/124158/38119186-d1c28b76-338d-11e8-8858-49117d719b20.png)

**Comment by dustingetz** [comment]
Only on my machine and only with this localStorage - incognito works as normal

**Comment by dustingetz** [comment]
Happens when you click a topnav button - stage, or links etc

**Comment by khardenstine** [comment]
Can reproduce on any domain with:
localStorage.setItem(hypercrud.transit.encode(kw('BUILD')), 'asdf')
