### ISSUE TITLE
datepicker css zindex

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#145]
![image](https://user-images.githubusercontent.com/124158/38630867-218a34ea-3d86-11e8-9496-eabc821efc38.png)

**Comment by dustingetz** [comment]
![image](https://user-images.githubusercontent.com/124158/38631001-850d6078-3d86-11e8-8ef9-6887887925ee.png)

**Comment by dustingetz** [comment]
TWBS is adding z-index 2 on .input-group .form-control; top-nav has a z-index which the popover content inherits

**Comment by khardenstine** [comment]
hyperfiddle/hyperfiddle.net@728f69b559af2bdf2d73be304ac4363a233f35a4
