### ISSUE TITLE
simple anchors cause "Unstaged work will be lost on navigate, are you sure?"

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#146]
![image](https://user-images.githubusercontent.com/124158/38153613-a9e35e1a-343b-11e8-8add-d5a58e447c0e.png)

**Comment by dustingetz** [comment]
Clearing stage didnt help, the error still happened. Then refreshing (w cleared stage) fixes it.

**Comment by dustingetz** [comment]
@khardenstine What is the reason that this error state has to exist? I know you told me before but I can't find it with search.

**Comment by khardenstine** [comment]
If you navigate while having a popover open, the popover's staged contents will get hosed

**Comment by dustingetz** [comment]
Can we reduce the surface area by inspecting the stage area for presence of branches?

**Comment by khardenstine** [comment]
Related #37

**Comment by dustingetz** [comment]
This was a regression I forget why.

**Comment by khardenstine** [comment]
This shouldn't happen when you are clicking an anchor.
At least one way this can happen:
1. in a popover edit some data, dont stage
![image](https://user-images.githubusercontent.com/7741805/38686764-1cb92a94-3e43-11e8-9548-e4f7f7b18583.png)
2. open another tab to the same domain
3. click on any anchor
![image](https://user-images.githubusercontent.com/7741805/38686783-2b046a28-3e43-11e8-8686-6b2bb3e0193a.png)
