### ISSUE TITLE
router regression: soft-nav to home-route doesn't cannonicalize

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#148]
Going from sandbox todomvc to index results in `/:index/`

**Comment by dustingetz** [comment]
#37

**Comment by khardenstine** [comment]
Is this solved?

**Comment by dustingetz** [comment]
No: from <http://dustingetzcom.hyperfiddle.net/:hyperblog.2!tag/:hyperfiddle> nav home via domain panel and chrome url is "/:hyperblog.2!index/" instead of "/"

**Comment by dustingetz** [comment]
Can't rep from http://dustingetzcom.hyperfiddle.net/:hyperblog!dashboard/
