### ISSUE TITLE
core: illegal derefs of eithers

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#154]
These must branch appropriately

![image](https://user-images.githubusercontent.com/124158/38207033-73f99292-367a-11e8-858b-6f099ffebc78.png)

**Comment by khardenstine** [comment]
Although reactive values should be rendered to the user appropriately, reactions aren't necessarily run in order.  Are any problems surfacing to the user? or are you inside a breakpoint that doesn't make sense?

If it's the latter, that is to be expected, and there isn't much we can do at the moment.
If it's the former, I'd need to see more information on the error

**Comment by dustingetz** [comment]
I misworded the issue. The thing inside the reaction is a deref'ed left, which should never get here. The fiddle has been realized by the time we get here. The root cause was a code mismatch between ssr and browser, but even still, I dont think we should get here if the query is still loading.

**Comment by khardenstine** [comment]
You can get there because reactions don't run in perfect order.  Was there a user facing error?  Or did you just break on exception?

**Comment by dustingetz** [comment]
Closing as I think this was never a real issue, I just flagged it as suspicious and was wrong
