### ISSUE TITLE
stale/loading incorrectly caches old render function on error, or something

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#157]
This is totally screwed. It's caching the old fiddle, it never got to the new fiddle which is broken

**Comment by dustingetz** [comment]
![image](https://user-images.githubusercontent.com/124158/38276066-dc60ed5c-3761-11e8-9221-4391296e3852.png)

**Comment by khardenstine** [comment]
I'm guessing this can be closed, both browser-ui and user-portal have been repaved since this was reported

**Comment by dustingetz** [comment]
This is a router artifact; the url is unexpectedly matching this route: `[#entity["$" :a] "/"] :hyperblog/index`

**Comment by dustingetz** [comment]
I fixed it by removing the conflicting line from the router. The other blog routes do not overlap with auto-routes. The only urls in the wild that are now broken are /:hyperfiddle/ and /:personal/ neither of which matter.
