### ISSUE TITLE
clojure.string is not nil safe

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#167]
This fails with a namespaceless keyword `#(clojure.string/starts-with? (namespace (:db/ident %)) "zzz")` which is ridiculous. using cuerdas fixes it.

Proposition: ban clojure.string everywhere

**Comment by khardenstine** [comment]
I wouldn't go so far as banning, but by default we should reach for cuerdas.
Maybe going forward reserve the `string` alias for cuerdas. 
```clj
[cuerdas.core :as string]
[clojure.string :as clojure-string]
```

**Comment by khardenstine** [comment]
This burns:
`(not (string/blank? nil))`
cuerdas = true
clojure = false

**Comment by dustingetz** [comment]
Maybe you want contrib.data/or-str
```
(defn orp "or with custom predicate" [f? & args]            ; todo macro
  (first (remove f? args)))

(defn or-str [& args]                                       ; todo macro
  (apply orp str/empty-or-nil? args))
```

**Comment by khardenstine** [comment]
Right there in or-str: `cuerdas.core/empty-or-nil?`  Thats what I want

**Comment by dustingetz** [comment]
https://github.com/funcool/cuerdas/issues/56
