### ISSUE TITLE
tempid collision - unmanaged create new

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#17]
Staging here will clobber the existing tempid
![image](https://user-images.githubusercontent.com/124158/35454284-6a3725fc-029b-11e8-81d8-bdd350f2a8f0.png)

**Comment by khardenstine** [comment]
Are you running latest?  This should have been fixed yesterday 58bd3aed4961828aaa46fe448f478fecadb855ea #14

**Comment by khardenstine** [comment]
Already fixed
