### ISSUE TITLE
Unrecognized datomic or hyperfiddle errors

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#170]
Please log any unmatched errors here so we can match them, thanks!

**Comment by khardenstine** [comment]
## Good starting point on seattle:

```
[:find (pull ?e [*])
 :in $
 :where [?e :neighborhood/name]]
```

FWIW some of these look like datascript.parser errors failing before datomic (e.g. `Cannot parse :find, ...`)

## failures
```
[:find (pull ?e [*])
 :in $a
 :where [?e :neighborhood/name]]

Unrecognized Datomic error
java.lang.Exception: processing rule: (q__28514 ?e), message: processing clause: [?e :neighborhood/name], message: :db.error/invalid-data-source Nil or missing data source. Did you forget to pass a database argument?
```

```
[:find (pull ?e [*])
 :in $
 :where [$a ?e :neighborhood/name]]

Unrecognized Datomic error
clojure.lang.ExceptionInfo: Where uses unknown source vars: [$a] {:error :parser/query, :vars #{#datascript.parser.SrcVar{:symbol $a}}, :form [:find (pull ?e [*]) :in $ :where [$a ?e :neighborhood/name]]}
```

```
[:find (pull ?e [* asdf])
 :in $
 :where [?e :neighborhood/name]]
Unrecognized Datomic error
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: :db.error/invalid-attr-spec Attribute identifier asdf of class: class java.lang.String does not start with a colon
```

```
[:find (pull $a ?e [*])
 :in $
 :where [?e :neighborhood/name]]

Unrecognized Datomic error
java.lang.Exception: Unable to find dbval for '$a'. Please check your pull expression
```

```
[:find (pull ?e)
 :in $
 :where [?e :neighborhood/name]]

Unrecognized Datomic error
clojure.lang.ExceptionInfo: Cannot parse pull expression, expect ['pull' src-var? variable (constant | variable | plain-symbol)] {:error :parser/find, :fragment (pull ?e)}
```

```
[:find ?f
 :in $
 :where [?e :neighborhood/name]]

Unrecognized Datomic error
clojure.lang.ExceptionInfo: Query for unknown vars: [?f] {:error :parser/query, :vars #{#datascript.parser.Variable{:symbol ?f}}, :form [:find ?f :in $ :where [?e :neighborhood/name]]}
```

```
[:find (sum $ ?e)
 :in $
 :where [?e :neighborhood/name]]

Unrecognized Datomic error
clojure.lang.ArityException: Wrong number of args (2) passed to: aggregation/sum
```

```
[:asdf $
 :find ?e
 :where [?e :neighborhood/name]]

Unrecognized Datomic error
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: No :find clause specified
```

**Comment by khardenstine** [comment]
```
Unrecognized Datomic error
java.lang.IllegalArgumentException: :db.error/datoms-conflict Two datoms in the same transaction conflict
```

**Comment by khardenstine** [comment]
Stage a bad cas:
[:db/cas e a "NOT THE ACTUAL CURRENT VAL" nv]

`java.lang.IllegalStateException: :db.error/cas-failed Compare failed: ...`

![image](https://user-images.githubusercontent.com/7741805/42776044-f24fd6fc-8903-11e8-8988-11b81695ab99.png)

**Comment by jc776** [comment]
Following the tutorial for tank.hyperfiddle.net, I got a "detach" link that wasn't write-restricted which caused an unrecognized error.

:hyperfiddle.error/unrecognized
```
java.lang.IllegalArgumentException: :db.error/invalid-lookup-ref Invalid list form: [{:db/id 17592186045531, :neighborhood/name "South Park", :neighborhood/district {:db/id 17592186045530}}]
```
```
#hypercrud.types.EntityRequest.EntityRequest{:e [:fiddle/ident :jcoady612/seattle], :db #hypercrud.types.DbVal.DbVal{:uri #uri "datomic:free://datomic:4334/tank", :branch nil}, :pull-exp [:db/id :db/doc :fiddle/css :fiddle/ident {:fiddle/links [:db/id :link/class {:link/fiddle [:db/id :fiddle/ident :fiddle/query :fiddle/type]} :link/formula :link/ident :link/path :link/rel :link/tx-fn]} :fiddle/markdown :fiddle/pull :fiddle/pull-database :fiddle/query :fiddle/cljs-ns :fiddle/renderer :fiddle/type :fiddle/hydrate-result-as-fiddle *]}
```
```
[[:db/add "-2017569654" :fiddle/ident :jcoady612/seattle]
 [:db/retract "-2017569654" :fiddle/type :blank]
 [:db/add "-2017569654" :fiddle/type :query]
 [:db/retract "-2017569654" :fiddle/query "[:find (pull ?e [:db/id *]) :where\n [?e :db/ident :db/add]]"]
 [:db/add "-2017569654" :fiddle/links "-719525300"]
 [:db/add "-719525300" :link/rel :hf/self]
 [:db/add "-1077685589" :fiddle/ident :jcoady612.seattle/neighbourhood]
 [:db/add "-719525300" :link/fiddle "-1077685589"]
 [:db/retract "-1077685589" :fiddle/type :blank]
 [:db/add "-1077685589" :fiddle/type :entity]
 [:db/add "-1253778134" :link/rel :hf/remove]
 [:db/add "-2017569654" :fiddle/links "-1253778134"]
 [:db/add "-1136589204" :link/rel :hf/detach]
 [:db/add "-2017569654" :fiddle/links "-1136589204"]
 [:db/add "-2017569654" :fiddle/query "[:find \n (pull ?e [:db/id :hyperfiddle/owners :neighborhood/name :neighborhood/district])\n :where\n [?e :neighborhood/name]]"]
 [:db/add "-719525300" :link/path "0"]
 [:db/add "-1253778134" :link/path "0"]
 [:db/add "-1136589204" :link/path "0"]
 [:db/retract [{:db/id 17592186045531, :neighborhood/name "South Park", :neighborhood/district {:db/id 17592186045530}}] 0 17592186045531]]
```

**Comment by alexandrkozyrev** [comment]
:hyperfiddle.error/unrecognized
java.lang.IllegalStateException: :db.error/cas-failed Compare failed: presentation mode presentation mode
- arrows-controls
- simple-deck-layout
- hiccup
Please comment this error at hyperfiddle#170 so we can match it.

#hypercrud.types.EntityRequest.EntityRequest{:e [:fiddle/ident :deck], :db #hypercrud.types.DbVal.DbVal{:uri #uri "datomic:free://datomic:4334/~alexandr.kozyrev@gmail.com+1", :branch nil}, :pull-exp [:db/id :fiddle/css :fiddle/ident :fiddle/uuid {:fiddle/links [:db/id :link/class {:link/fiddle [:db/id :fiddle/ident :fiddle/query :fiddle/type]} :link/formula :link/ident :link/path :link/tx-fn]} :fiddle/markdown :fiddle/pull :fiddle/pull-database :fiddle/query :fiddle/cljs-ns :fiddle/renderer :fiddle/type :fiddle/hydrate-result-as-fiddle *]}

**Comment by wmatson** [comment]
`java.lang.IllegalStateException: :db.error/cas-failed Compare failed: 103 102`

`#hypercrud.types.EntityRequest.EntityRequest{:e [:fiddle/ident :hfnet.tank/index], :db #hypercrud.types.DbVal.DbVal{:uri #uri "datomic:free://datomic:4334/tank", :branch nil}, :pull-exp [:db/id :fiddle/css :fiddle/ident :fiddle/uuid {:fiddle/links [:db/id :link/class {:link/fiddle [:db/id :fiddle/ident :fiddle/query :fiddle/type]} :link/formula :link/ident :link/path :link/tx-fn]} :fiddle/markdown :fiddle/pull :fiddle/pull-database :fiddle/query :fiddle/cljs-ns :fiddle/renderer :fiddle/type :fiddle/hydrate-result-as-fiddle *]}`

The above is from hitting the root url after causing the error.
----

This happened after clicking the `inc` button twice on :dustingetz/counter (it was there was an age field that seemed to increment upon clicking a button), the link was visible without scrolling before. Now I get the error on the root of http://tank.hyperfiddle.net/ as above. If I open the same url in an incognito window, everything is fine, but the error reproduces upon the same steps.

The paste data is slightly different upon initial error:
`#hypercrud.types.EntityRequest.EntityRequest{:e [:fiddle/ident :dustingetz/counter], :db #hypercrud.types.DbVal.DbVal{:uri #uri "datomic:free://datomic:4334/tank", :branch nil}, :pull-exp [:db/id :fiddle/css :fiddle/ident :fiddle/uuid {:fiddle/links [:db/id :link/class {:link/fiddle [:db/id :fiddle/ident :fiddle/query :fiddle/type]} :link/formula :link/ident :link/path :link/tx-fn]} :fiddle/markdown :fiddle/pull :fiddle/pull-database :fiddle/query :fiddle/cljs-ns :fiddle/renderer :fiddle/type :fiddle/hydrate-result-as-fiddle *]}`

**Comment by dustingetz** [comment]
Hey thanks for the report. I see there is a bug with our staging area. Use
localStorage.clear() in the js console to fix it.
ᐧ
ᐧ

**Comment by khardenstine** [comment]
```[:find (pull ?e [*]) :in $not-dollar-sign :where [?e :db/ident]]``` from #944
