### ISSUE TITLE
retractEntity is crossing databases - really bad

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#172]
I have seen this once in a blue moon and was kind of like 'huh'? but I just saw it indisputably. I was blogging and retracted a blog post, and it retracted the active fiddle instead, and now my blog is fuxored!

**Comment by dustingetz** [comment]
You know, now I'm questioning myself again. I am reverting the tx, but, I am questioning if I am crazy and just managed to retract the fiddle instead of the post in my caffeine frenzy of blogging with three windows open

**Comment by dustingetz** [comment]
This tx shows a fiddle being retractEntitie'd along with its links
```
(def src (d/connect "datomic:free://datomic:4334/starter-blog-src2"))
  (def $log (d/log src))
  (-> $log keys)                                    ; (:db :olookup :root-id :tail)
  (-> $log :db :basisT)
  (->> (d/tx-range $log 1413 nil) first)
  (rollback src 1413)
```
```
{:t 1413,
 :data [#datom[13194139534725 50 #inst"2018-04-07T17:00:54.440-00:00" 13194139534725 true]
        #datom[17592186045559
               96
               "(fn [ctx]\n  (let [post @(:hypercrud.browser/result ctx)\n        pretty-date (fn [date] (.format (js/moment date) \"YYYY\"))\n        bio' ((:browse' ctx) :bio [] ctx)\n        bio (-> bio' (cats.core/mplus (cats.monad.either/right nil)) (cats.core/extract))]\n    [:div.hyperblog.container.markdown\n     [:h1 (:post/title post) \" \" (if-let [d (:post/date post)] [:small (pretty-date d)])]\n     [:div.title [hypercrud.ui.markdown/markdown (:user/bio-short bio)]]\n     [hypercrud.ui.markdown/markdown (:post/content post)]\n     [:style {:dangerouslySetInnerHTML {:__html \"\n.hyperblog.container { padding-bottom: 300px; max-width: 46rem; }\n.hyperblog div.title { padding-bottom: 20px; }\n.hyperblog div.author-img { float: right; width: 130px; }\n.hyperblog pre { border: 0; word-wrap: unset; word-break: unset; }\n.hyperblog pre code { border: 0; white-space: unset; }\n\"}}]]))"
               13194139534725
               false]
        #datom[17592186045559 102 :entity 13194139534725 false]
        #datom[17592186045559
               107
               "[[:db/id :post/title :post/content\n  :db/ident :post/published :post/date :post/summary :post/hc-route :post/url]]"
               13194139534725
               false]
        #datom[17592186045559
               108
               ".hyperfiddle-user .hyperfiddle-form-cell { display: block; }\n.markdown h4 {margin-bottom: 20px; margin-top: 30px; }"
               13194139534725
               false]
        #datom[17592186045559 109 :hyperblog/post 13194139534725 false]
        #datom[17592186045558 69 17592186045559 13194139534725 false]
        #datom[17592186045758 69 17592186045559 13194139534725 false]
        #datom[17592186045576 68 :bio 13194139534725 false]
        #datom[17592186045576 69 17592186045496 13194139534725 false]
        #datom[17592186045576 72 true 13194139534725 false]
        #datom[17592186045559 92 17592186045576 13194139534725 false]]}
```

**Comment by khardenstine** [comment]
My best guesses:

1. You hit remove fiddle
2. Txfns are being cached/reused in different spots in the app (thing stale/loading), deeply concerning, but seems impossible if that was even happening that they would cross between the topnav and userland.
3. The id of the fiddle (17592186045559) was the same as the id of your post.   And maybe the tx function ran with the wrong uri bound (or staged to the wrong uri).
4.  The id of the fiddle (17592186045559) was the same as the id of your post. You were hand editing the stage area and moved a statement to the wrong URI.

Should be able to verify that there is or is not a post with id 17592186045559 and rule out the last two.

**Comment by dustingetz** [comment]
5. Data corruption - of the "entity has fiddle/ident and link/rel" variety

Signs are pointing towards user error, but I want to talk about this in person because I have seen some really funky and suspicious things over the last year

**Comment by dustingetz** [comment]
This is probably user error and can be solved with UX (tabbed staging area with individual transact)
