### ISSUE TITLE
localStorage cycles when multiple tabs running but different builds

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#178]
The newer tab clears localStorage due to new build, the older tab reacts to the clear event and re-syncs to localStorage resetting the stale value, causing "refresh" error in new tab

**Comment by khardenstine** [comment]
This only ever happened once correct?
The timeline corresponds with this [commit](https://github.com/hyperfiddle/hyperfiddle.net/commit/56804a097be0951236b5a70e4c520900316c20ea) when we switched from an unencoded ":BUILD" storage key.  This shouldn't ever happen again

**Comment by dustingetz** [comment]
well, on my machine, but what about, say Ken's machine?

**Comment by khardenstine** [comment]
Sure it could happen if he has an old tab of hyperfiddle still **open** on his machine from 11 days ago

**Comment by dustingetz** [comment]
ah, yes i see
