### ISSUE TITLE
markdown renderer inserts excessive font styles and extra div

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#181]

**Comment by dustingetz** [comment]
I dont know how to remove the div, what are the font styles you're talking about?

**Comment by khardenstine** [comment]
Really the 15px font size is the issue.  Its really bad in topnav
![image](https://user-images.githubusercontent.com/7741805/38587321-105e0ee0-3cef-11e8-9140-7771af631331.png)

## data mode
![image](https://user-images.githubusercontent.com/7741805/38587456-84481f12-3cef-11e8-9170-2931d54b3e5a.png)
## view mode
![image](https://user-images.githubusercontent.com/7741805/38587452-7bba315a-3cef-11e8-8c3e-6a6918c61218.png)

**Comment by dustingetz** [comment]
Oh, yeah this is a tough one. Instead of .markdown i think we need .not-markdown

**Comment by dustingetz** [comment]
`hypercrud.ui.control.markdown_rendered.remarkInstance.processSync(value, {"commonmark": true}).contents`
