### ISSUE TITLE
Report custom router no-matches as failures

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#185]
* <http://dustingetzcom.hyperfiddle.net/:datomic-faq>
* Data mode
* Scroll to bottom, alt-click "bio"
* Observe not taken to bio, you're somewhere else
* Alt-click "bio" again, it works this time

**Comment by khardenstine** [comment]
hyperfiddle/hyperfiddle.net#148 has regressed as well

**Comment by khardenstine** [comment]
This is a missing route `[:hyperblog/bio]` in the custom user router
```edn
["/"
 {"drafts/" :hyperblog/drafts
  "pairing/" :user/pairing
  [#entity["$" :a] "/"] :hyperblog/index
  [#entity["$" :a]] :hyperblog/post}]
```

None of this makes sense:
```clj
(encode [:hyperblog/bio])
=> "/:hyperblog!bio/"
(decode "/:hyperblog!bio/")
=> [:hyperblog/index [#entity["$" :hyperblog!bio]]]
```

**Comment by khardenstine** [comment]
Reopening, to redirect this ticket for communicating the failure of their router to users better.
Is there a reason we fall back to the ednish router when the user's fails to match?
I vote we throw an informative message instead
