### ISSUE TITLE
empty auto-table doesn't draw headers

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#19]
![image](https://user-images.githubusercontent.com/124158/35455136-db474576-029e-11e8-90c4-cc73c3286f7f.png)
stage is
```
{nil {#uri "datomic:free://datomic:4334/litepay-app"
        [[:db/add "2" :db/ident :invoice.status/pending]
         [:db/add "1" :db/ident :invoice/status]
         [:db/add "1" :db/valueType 20] [:db/add "1" :db/cardinality 35]]}}
```

**Comment by dustingetz** [comment]
Query is bugged here, but setting to [*] (unquoting the *) still renders same.

**Comment by khardenstine** [comment]
Not sure if this is the only issue, but there arent any headers to possibly draw when there are 0 results and the query has a wildcard pull-exp

**Comment by khardenstine** [comment]
For relation queries, we map over the result set when generating the ui find-elements. 0 results = 0 fes.  This needs fixed.  Requests might be impacted too

**Comment by dustingetz** [comment]
This embedded link at :items is also drawing nothing for the embedded query. Not even a pink box. The query is bunk so it should show the datomic error. Note the new link works. 
![image](https://user-images.githubusercontent.com/124158/35459133-f25a1a28-02ac-11e8-966d-ee5b5869ac78.png)

**Comment by dustingetz** [comment]
I fucked this up, removing the latest
