### ISSUE TITLE
is hyperfiddle.io and hyperfiddle.server the same thing

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#192]
collapse it all into "hyperfiddle-io" which is the second artifact? I checked the reducers, it looks like it might split cleanly

**Comment by khardenstine** [comment]
hf.io is the interface that for data sync; the implementations are HTTP or datomic api calls
hf.server is literally just bits for an HTTP server in node or the jvm

**Comment by dustingetz** [comment]
From a deps perspective, hyperfiddle.server depends on pedestal, and cloud-jvm also depends on pedestal. From a deps perspective, shouldn't the pedestal stuff flatten into cloud-jvm and the non-pedestal stuff flatten into hyperfiddle.io ?

**Comment by dustingetz** [comment]
The ultimate goal being to have one fewer artifact to talk about in the docs. cloud-jvm and cloud-node maybe can be combined as well (and the parallel devkit for which node is optional)

**Comment by khardenstine** [comment]
For starters cloud-* are all private builds and have no impact on anyone else.

When doing the CLI, I'll look into creating multiple maven artifacts via classifiers and get all the public code under one repo; we can partition the code by directory (e.g. src-jvm, src-node, src).  But the goal of one repository and artifact is pretty tough.  We don't need or want pedestal when building a browser or node artifact
