### ISSUE TITLE
`#?(:clj clojure.test :cljs cljs.test)` can be simplified to just `clojure.test`

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#196]
> There is a relatively new simplification to the ns form that you can employ: You can use clojure in lieu of cljs in the first segment of namespaces in the case of nonexistent clojure.* namespaces that can be mapped to cljs.* namespaces. <https://clojurescript.org/guides/ns-forms>

**Comment by khardenstine** [comment]
Looks like `#?(:clj :refer :cljs :refer-macros)` falls out too for clojure.test
