### ISSUE TITLE
Failures with multiline (dotall) regex support

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#217]
CircleCI
```
dmbp17:target dustin$ ssh -p 64536 18.205.17.167
root@ff788f5511de:~# node --version
v8.8.1
root@ff788f5511de:~# node
> /^(.+ :db.error\/datoms-conflict )(.+)$/s
/^(.+ :db.error\/datoms-conflict )(.+)$/s
^
SyntaxError: Invalid regular expression flags
```
Local node
```
dmbp17:hyperfiddle dustin$ node --version
v9.5.0
dmbp17:hyperfiddle dustin$ node
> /^(.+ :db.error\/datoms-conflict )(.+)$/s
/^(.+ :db.error\/datoms-conflict )(.+)$/s
>
```

prod node
```
root@hypercrud-prod:~# docker-compose run node bash
bash-4.3# node --version
v8.11.1
bash-4.3# node
> /^(.+ :db.error\/datoms-conflict )(.+)$/s
/^(.+ :db.error\/datoms-conflict )(.+)$/s
> 
```

**Comment by khardenstine** [comment]
```
$ node --version
v8.6.0
$ node
> /^(.+ :db.error\/datoms-conflict )(.+)$/s
/^(.+ :db.error\/datoms-conflict )(.+)$/s
^

SyntaxError: Invalid regular expression flags
```

**Comment by dustingetz** [comment]
The bad regex is commented out, but once its back in, the test case to activate it is to stage a new query fiddle, go to stage area, duplicate the fiddle/type statement to create the conflict as below:

```
{nil
 {#uri "datomic:free://datomic:4334/sandbox"
  [[:db/add "-2017569654" :fiddle/ident :aaaaa]
   [:db/add "-2017569654" :fiddle/type :query]
   [:db/add "-2017569654" :fiddle/type :entity]
   [:db/add "-2017569654" :fiddle/entrypoint? true]
   [:db/add
    "-2017569654"
    :fiddle/query 
    "[:find (pull ?e [:db/id]) :where\n [?e]]"]]}}
```

**Comment by khardenstine** [comment]
Assuming this [post](https://groups.google.com/a/chromium.org/d/msg/blink-dev/0uSHjqvgAwQ/R32gcLs2BQAJ) is accurate, dotall was supported in V8 v6.2.66
Node updated to V8  >6.2.66 in [v8.10.0](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#2018-03-06-version-8100-carbon-lts-gibfahn) (specifically to 6.2.414.46)

**Comment by khardenstine** [comment]
It would be good to know browser support as well.
Chrome >= 62
FF ???
IE ???
Edge ???
Safari ???
Opera ???

**Comment by khardenstine** [comment]
Sidestepping this mess with string/split instead of capture groups.
Can punt this until it rears its head again, or becomes a non-issue with better environment support

**Comment by khardenstine** [comment]
We are on node10+ everywhere
