### ISSUE TITLE
Schema editor features

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#22]
Query should accept a user-specified filter on the namespace of the db/ident (or similar). This seems difficult, as the filter string isn't in the url, maybe needs a custom request fn. Can be client-only like hide-datomic-attrs.

**Comment by dustingetz** [comment]
This seems difficult, as the field isn't in the url, maybe needs a custom request fn

**Comment by dustingetz** [comment]
Can be client-only like hide-datomic-attrs

**Comment by khardenstine** [comment]
This seems a higher level feature request for ui.table, of which I see a few:
- Allow arbitrary client side filtering by column (along with the lines of a more fully featured grid component).  These could be driven by the attribute's datatype, such that you could have namespace filters for idents, contains for strings, ranges for longs, etc
- Hooks from the table to edit the raw datalog (e.g. prompt user to type a partial datalog clause and append it to the fiddle/query)

**Comment by dustingetz** [comment]
I did this client side in the schema editor. Trying it out and we can generalize it later.
