### ISSUE TITLE
Table not remounting on url change

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#231]
Not sure what the exact distinction should be for remounting, but navigating to a different schema view should definitely remount.  The remount should probably be happening all the way at the browser with a react key, however what that key should be, is a nuanced

Example:
Set a bunch of local state with filters and sorts:
![image](https://user-images.githubusercontent.com/7741805/39551459-129afc86-4e33-11e8-8599-bd1b1800da24.png)
Click $domains schema link, notice all state has persisted:
![image](https://user-images.githubusercontent.com/7741805/39551471-1c14d8c2-4e33-11e8-91e2-412b5097e43a.png)

**Comment by dustingetz** [comment]
What are the precise repro steps? How did you get from $ to $domains without going through another (wildly different) page first?
