### ISSUE TITLE
Inject fiddle into $src from edn

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#232]
What do you suppose is the best way to get this to show up in link/fiddle picker?

![image](https://user-images.githubusercontent.com/124158/39553969-40dee7dc-4e3e-11e8-9afd-844e5207d0b6.png)

**Comment by dustingetz** [comment]
Note there is a interesting almost symmetry between fiddle/ident and link/rel. Maybe for the auto link case, the link/rel is the semantic bit that conjures the matching auto-fiddle out of thin air. Then there is no need for a link/fiddles picker at all.

**Comment by dustingetz** [comment]
No, that's crap. [:link/rel :options] -> [:fiddle/ident :hyperfiddle/idents-for-ns]

**Comment by khardenstine** [comment]
Related #104

**Comment by khardenstine** [comment]
Agreed :options aren't related, they is a weird way of inlining a system renderer.

We want a way to inject non-database values into either the query result OR the select component.  Both are probably desired behaviors in the long haul.

This was fun:
```clj
(d/q '[:find [?any-result ...]
       :in $ ?inlined-results
       :where
       [(datomic.api/q '[:find [(pull ?link [:db/id :fiddle/ident]) ...]
                         :where (or [?link :fiddle/ident]
                                    [?link :fiddle/type])]
                       $) ?db-results]
       [(concat ?inlined-results ?db-results) [?any-result ...]]]
     (db! root-uri)
     #{{:fiddle/ident :hyperfiddle.builtin/ident}
       {:fiddle/ident :hyperfiddle.builtin/idents-for-ns}})
=>
[{:db/id 17592186061141, :fiddle/ident :hyperfiddle.ide/fiddle-more}
 {:fiddle/ident :hyperfiddle.builtin/ident}
 {:db/id 17592186061236, :fiddle/ident :hyperfiddle.domains/edit}
 {:db/id 17592186045651, :fiddle/ident :hyperfiddle.ide/html}
 {:db/id 17592186058175, :fiddle/ident :hyperfiddle.ide/new-link}
 {:db/id 17592186056398, :fiddle/ident :hyperfiddle.ide/new-fiddle}
 {:db/id 17592186060846, :fiddle/ident :hyperfiddle/topnav}
 {:db/id 17592186045602, :fiddle/ident :hyperfiddle.ide/edit-fiddle-links}
 {:db/id 17592186060551, :fiddle/ident :hyperfiddle.ide/entry-point-fiddles}
 {:db/id 17592186045605, :fiddle/ident :hyperfiddle.ide/fiddle-options}
 {:db/id 17592186060871, :fiddle/ident :hyperfiddle.domains/new}
 {:db/id 17592186045564, :fiddle/ident :hyperfiddle.ide/domain}
 {:fiddle/ident :hyperfiddle.builtin/idents-for-ns}
 {:db/id 17592186061152, :fiddle/ident :hyperfiddle.ide/stage}
 {:db/id 17592186060438, :fiddle/ident :hyperfiddle.ide/attribute-renderers}
 {:db/id 17592186045557, :fiddle/ident :hyperfiddle/domains}
 {:db/id 17592186045735, :fiddle/ident :hyperfiddle.ide/account}
 {:db/id 17592186060817, :fiddle/ident :hyperfiddle.ide/attribute-edit}]
```

That list of ?inlined-results would be injected from the route, which is awful for URLs.  So then the problem becomes how do we inline certain query parameters automatically.  [This ticket captures this area](https://github.com/hyperfiddle/hyperfiddle.net/issues/71)
