### ISSUE TITLE
popover's stage button should sometimes be labeled transact!

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#235]
![image](https://user-images.githubusercontent.com/7741805/39602990-dead46a0-4ef4-11e8-9ec5-ebc75cb042aa.png)

If auto-transact is on, and the branch is one up from the nil branch, the UI label should express the side effect

**Comment by dustingetz** [comment]
This will mess up my docs and isn't technically true. The runtime controls the database side effect. How about "submit" and "discard". Submit is ambiguous enough to still be true in "baked RPC" configurations.

**Comment by dustingetz** [comment]
Closing as labels will improve organically
