### ISSUE TITLE
Hyperfiddle can cause :db.error/datoms-conflict

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#24]
![image](https://user-images.githubusercontent.com/124158/35459325-9f14c57e-02ad-11e8-80ab-adc160f81aeb.png)

**Comment by dustingetz** [comment]
`dispatch(main.main.root_ctx, hyperfiddle.foundation.actions.toggle_staging)` is still a working backdoor

**Comment by khardenstine** [comment]
Related hyperfiddle/hyperfiddle.net#177

**Comment by dustingetz** [comment]
`window.toggle_stage()` is backdoor

**Comment by dustingetz** [comment]
Related #110

**Comment by dustingetz** [comment]
```
{nil
 {#uri "datomic:free://datomic:4334/sandbox"
  [[:db/add "-2017569654" :fiddle/ident :hello-world]
   [:db/add "-2017569654" :fiddle/type :entity]
   [:db/add "-2017569654" :fiddle/type :query]
   [:db/add
    "-2017569654"
    :fiddle/query 
    "[:find (pull ?e [:db/id]) :where\n [?e]]"]]}}
```

**Comment by dustingetz** [comment]
Related #217

**Comment by khardenstine** [comment]
We liberally throw the staging area whenever there are errors.
I yanked toggle_staging as it no longer fits our state model.
Closing, any other issues in this area are captured by their own tickets
