### ISSUE TITLE
hc routes should be maps

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#243]
This is what I want to write: `(assoc route :fragment "asdf")`

This wouldn't be too offensive, but it NPEs: `(assoc route 3 "asdf")`

So we end up with this monstrosity...
```clj
(defn assoc-fragment [route fragment]
  (-> (->> (map-indexed vector route)
           (reduce (fn [route [pos v]]
                     (assoc route pos v))
                   [nil nil nil nil]))
      (assoc 3 frag)))
```

**Comment by dustingetz** [comment]
I am not a fan of this, i think the canonical format (as visible to users) should be positional and flat and minimal syntax. I am okay with extending various clojure types with a router protocol a-la bidi (and probably also datomic query)
