### ISSUE TITLE
Fetching domain for low bootstrap level causes double render

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#245]
Visible post #238 because the first render was to the non-fragment state, not sure why that jostled the order but it made me spot this.

**Comment by dustingetz** [comment]
https://github.com/hyperfiddle/hypercrud.server/commit/f7c6d57b91749fc9d0780e80c029deca7f32b7fd

**Comment by khardenstine** [comment]
https://github.com/hyperfiddle/hyperfiddle.net/commit/a7a48f19f79ffb5d3bf9db9a23c2b1d583a6ce49

**Comment by khardenstine** [comment]
Related https://github.com/hyperfiddle/hyperfiddle.net/issues/230

**Comment by khardenstine** [comment]
I guess this change makes sense because we no longer SSR in non-aliased domains.  And we dont rehydrate on aliased domains.  So there is no longer a reason to attach react while rehydrating.
