### ISSUE TITLE
foundation alias exceptions and www

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#246]
Confusion here - (not= www) happens in IDE which means foundation features like bypass SSR doesn't account for www

**Comment by khardenstine** [comment]
The problem is you want auto-tx on for owners on www?
```clj
writable = (or owner (and alias? (not= "www" (:domain/ident domain))))
```

**Comment by dustingetz** [comment]
No this is causing the SSR to say "loading" on www because the hardcoded logic is in the wrong place. ez fix
