### ISSUE TITLE
src mode background color should fill entire window height

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#247]
![image](https://user-images.githubusercontent.com/7741805/39825206-41a76c0c-537f-11e8-86c3-63c3475c6e1d.png)

**Comment by khardenstine** [comment]
![image](https://user-images.githubusercontent.com/7741805/41432653-b0f95418-6fe4-11e8-90f9-cd9b5a52d07f.png)

Not fixed

**Comment by dustingetz** [comment]
Its fixed, the fix may not be deployed

**Comment by dustingetz** [comment]
I had to revert something and fix differently

**Comment by khardenstine** [comment]
![image](https://user-images.githubusercontent.com/7741805/41475613-3e316aa2-708d-11e8-8c5b-5e6a7b79147b.png)
