### ISSUE TITLE
Always have access to schema from src mode

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#250]
Currently there is no way to get to schema from a blank fiddle.
Have to either set the type to query or entity, or navigate to a query or entity fiddle

**Comment by khardenstine** [comment]
It's awful UX.  Users need a consistent way to get to it.
One without thinking through the logic of what predicates needs to be true for it to appear.
If I was someone else, I would not have guessed that its not available for blank fiddles.

**Comment by dustingetz** [comment]
I also want the "markdown gist" mode to be as simple and non-scary as possible
i was thinking about bumping fiddle/markdown to above the fiddle/type and fiddle/query

it feels like we are polluting the app builder side of things for this one use case
markdown gist != app-builder/hyperfiddle
we are building app-builder/hyperfiddle
