### ISSUE TITLE
src-mode support for fiddle/links

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#254]

**Comment by dustingetz** [comment]
This is simply fiddle/type clojure, i think. Fiddle/type clojure unifies all the different fiddle types into one clojure expression, though obviously the devil is in the details.

**Comment by khardenstine** [comment]
new :link/fiddle and :fiddle/link don't work inside hf-live right?

**Comment by dustingetz** [comment]
fiddle src mode is working fine

**Comment by khardenstine** [comment]
hf-live/src-mode is being removed
