### ISSUE TITLE
Sys link on limited attributes

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#255]
```clj
[:find (pull ?e [:db/id :community/name (limit :community/category 1)])
 :where [?e :community/name]]
```
![image](https://user-images.githubusercontent.com/7741805/39879239-4877c8fa-5448-11e8-9750-cd32402e0ad2.png)

We could generate sys links to the remaining set of categories, maybe with a trailing `...` link label in the cell.

**Comment by dustingetz** [comment]
Links are no longer generated, all links are modeled
