### ISSUE TITLE
Fiddle with a default query - links to it style invalid 

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#259]
:my-test is legit it just has a default query

![image](https://user-images.githubusercontent.com/124158/39942855-d79d1652-552e-11e8-9f80-6c24e449ee79.png)

**Comment by khardenstine** [comment]
This was a bug in the [entry-point](http://hyperfiddle.hyperfiddle.net/:hyperfiddle.ide!entry-point-fiddles/#:src)'s renderer.
Fixed by applying `hypercrud.browser.fiddle/data-defaults`
