### ISSUE TITLE
Toggling fiddle from blank to pull should draw the form readonly (no entity parameter)

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#268]
It can be conjured, perhaps. Makes sense to me that nothing would nil-pun to ~entity('$','tempid'). It might also make sense to render a readonly form (no backing entity), but that seems undefined from a datomic api call perspective

**Comment by dustingetz** [comment]
![image](https://user-images.githubusercontent.com/124158/40014318-3c851870-577e-11e8-80cd-6104b1322458.png)

**Comment by dustingetz** [comment]
#49

**Comment by dustingetz** [comment]
I am deep into this. This case is solved by having a "EntityRequest" with no dbid, uri or db, but it does have a pulled-tree which drives find-elements to get a form to show up (readonly and colorless)

**Comment by dustingetz** [comment]
You actually can't draw the form because there is not a $ in `/:hyperfiddle.system!edit/` which means we don't know the schema which is very interesting. I think we've made a mistake. Consider the following: 

* `/:hyperfiddle.system!edit/~entity('$',17592186045544)` 
* `/:hyperfiddle.system!edit;'$'/~entity(17592186045544)`

Today the $ is bound by the argument, which is deliberate due to the entity api having closures over the database. We waffled on this. This way doesn't require the fiddle-side to declare the database, and makes it easier to traverse the entity graph with syslinks. But there is now precedent for encoding $ as a fiddle param in our schema links and such. If we make this change, syslinks can draw readonly forms with the proper widgets when the parameter is omitted.

**Comment by dustingetz** [comment]
@khardenstine  review pls

**Comment by dustingetz** [comment]
Closed prematurely, cosmetics remain

**Comment by dustingetz** [comment]
* `/:my-q/~entity('$',-1)/~entity('$seattle',-2)`
* `/:my-q/1001/1001`
* `/:my-q/'-1'/'-1'`
* `/:edit;$seattle/1001`
* `/:neighborhood/1001`

Conculsions from IRL conversation: tempids must always be passed with $ for tempid reversal. URLs have tempids in them (otherwise what happens when you ssr without the stage? (not a great argument)) We'd have to audit the code, Karl's gut is this is not gonna work out. We dont know why.

Counter argument: d/transact and d/with are the same API, so if transact redirects, then d/with should redirect also. Reply: this isn't stable, because concurrent edits will churn the d/with'd id (and break urls in the wild with the old way the tempid resolved). So you'd have to freeze the t-value.

What if you never auto-sync if you have a staging area? Make rebase an explicit operation if there is a staging area, and automatic if not. (This doesn't work due to Datomic bugs)

Karl's conclusion: Using the dbval from a tempid is immoral unless doing tempid reversals. Getting the $ from an ~entity is immoral. The pull needs to get it from the url.
* `/:edit;$seattle/1001`
* `/:edit;$seattle/~tempid('$seattle','-1')`

Does this factoring cancel out the FatEntity types, and thinEntity becomes ~tempid, and it is only used for this url generation and no other part of the view (color will come from the fiddle not the entity), which means the form views see hashmaps and not FatEntity types. :db/id is a ~tempid[$ -1] or a long. Thesis: if there are no tempids in play, then :db/id is just a long. Karl says not sure if this is true.

So ~tempid would be manufactured on the spot for the url only, by looking for the in-scope dbval's tempid reversal map. The view sees a proper :db/id long. Only the URL has to unwind that. Any time we put a navcmp anchor on the page we have to reverse it.

What about formulas which get data from anywhere?

**Comment by dustingetz** [comment]
Refactoring fiddle :pull to encode dbval (symmetric with :query) will mean we can draw a readonly form with the right widget types. This is blocked on fiddle params in the route. For now, we will just draw the readonly form without typed widgets (just nils)

**Comment by khardenstine** [comment]
In the long term we will end up reverting my last commit.
This is a 404, and should error out, at least when dev tools are unavailable (prod/alias modes).
And when dev tools are on the page we could provide a UI to mock out different request parameters.
But obviously building that out is not in the cards for awhile.

**Comment by khardenstine** [comment]
This has regressed

**Comment by dustingetz** [comment]
@khardenstine what was regressed? I can't rep an issue

**Comment by khardenstine** [comment]
I cleaned this up in https://github.com/hyperfiddle/hyperfiddle/commit/f17a1713d547aab706ec3ec92ad78fc2f9c152b9#diff-b0bad5c759d0f6b38c834798db4e245bL119
