### ISSUE TITLE
WWW SSR "cljs eval failed" (and then react fixes it when attaches)

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#272]
`view-source:http://www.hyperfiddle.net/` and c-f "cljs eval failed" can rep locally too

**Comment by dustingetz** [comment]
Reproduced in the new domain panel. This is unrelated to hyperfiddle-live

**Comment by dustingetz** [comment]
hyperfiddle.core missing from node; the error is hypercrud.ui.attribute.code/code not defined

**Comment by khardenstine** [comment]
https://github.com/hyperfiddle/hyperfiddle.net/commit/c0cb8908aa12e68290424a2d7640549009a2a26d
