### ISSUE TITLE
Fiddle params in route

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#278]
Topnav and fiddle-src are the same fiddle with a different renderer. It is done out of band. This bit can be set in-band with a fiddle-param. That would let me edit the fiddle-src view live in hyperfiddle, something that saves me a lot of busywork (restore prod->dev, commit push test deploy, migrate prod)

Also
* Schema builtin fiddles
* Probably future auto-fiddles need this (higher order is more flexible)

**Comment by khardenstine** [comment]
Topnav and fiddle-src are no longer the same fiddle
