### ISSUE TITLE
Blog doesn't work in offline mode anymore

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#280]
It made a cool demo and I was about to write about it

**Comment by khardenstine** [comment]
Do we have aliases syncing now?

**Comment by dustingetz** [comment]
"Offline mode" means the chrome devtools disable network, the site should load from cache

**Comment by dustingetz** [comment]
It is not due to sync, it is something else

**Comment by khardenstine** [comment]
So long as the content has been downloaded this works again
![image](https://user-images.githubusercontent.com/7741805/46325065-9b9fc080-c5c4-11e8-94da-e97057a95fce.png)
