### ISSUE TITLE
:fiddle/pull-database

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#284]

**Comment by dustingetz** [comment]
Here is an interesting idea. What if the syntax is `(pull $ [:db/id :post/title])`, as in code (though a very whitelisted and validated piece of code)

**Comment by khardenstine** [comment]
Seems useful to want to query this data for data corrections and insights.
Also that pull syntax is entirely invented, we would still need to map that list of symbols into an EntityRequest.

Not to kill the debate, but this is landed now.  We can amend the feature as we see fit
