### ISSUE TITLE
fiddle/cljs-ns

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#293]

**Comment by dustingetz** [comment]
Not tested

**Comment by dustingetz** [comment]
This is actually i think cljc-ns and viewcode can use #?. In the long run, probably do not want #? in userland, but in the short run I like it in people's faces to force awareness that only the view is cljs

**Comment by khardenstine** [comment]
Can you provide some background?
What is this? What does this feature allow/enable?

**Comment by dustingetz** [comment]
It is for fiddle view code like topnav.cljs
