### ISSUE TITLE
"Duplicate key" error on simple query

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#298]
http://dustingetzcom.hyperfiddle.net/:hyperblog!tags/

Busted query: `[:find (pull ?e [:db/id *])  :where [_ :post/tag ?e]]`

I can't get any variations of that query to work. I can however query the posts

![image](https://user-images.githubusercontent.com/124158/40887817-441c2058-671c-11e8-9006-880dfe25da6d.png)

**Comment by dustingetz** [comment]
This worked `[:find ?e :where [_ :post/tag ?e]]` because post/tag is a keyword you can't pull but i am not sure this is the whole error as i tried similar before

**Comment by khardenstine** [comment]
This is pretty pathological.  Apparently you can pull on keywords, because datomic will assume a db/ident lookup.  Although that query makes no sense, we need to be able to display these results:

```edn
[[#:db{:id nil}]
 [{:db/id 17592186046661,
   :post/title "Capitalism – searching for a definition",
   :post/date #inst"2018-03-13T02:09:11.349-00:00",
   :post/published true,
   :post/tag [:capitalism],
   :fiddle/ident :capitalism,
   :fiddle/markdown "...",
   :fiddle/type :blank}]
 [#:db{:id nil}]
 [#:db{:id 17592186046269}]
 [#:db{:id nil}]
 [#:db{:id nil}]
 [#:db{:id nil}]
 [#:db{:id nil}]
 [#:db{:id nil}]
 [#:db{:id nil}]
 [#:db{:id nil}]
 [#:db{:id nil}]
 [#:db{:id nil}]
 [#:db{:id nil}]
 [#:db{:id nil}]
 [#:db{:id 17592186045843}]
 [#:db{:id nil}]
 ...
 [#:db{:id nil}]]
```

It looks like datomic runs set logic PRIOR to pulling (makes sense).  Which means you can have duplicate rows in the result set.  Our result set key algorithm (and r/unsequence) needs to take this into account.

**Comment by khardenstine** [comment]
When unsequencing (everywhere), we need to handle the following cases:
- cannot run hash on dbids (hashing numbers in cljs has collisions)
- most datomic queries do NOT return sets, so a simple hash is not sufficient, integer would be preferred
- tables are also used in nested card/many cases
- the safest method would be to use row index numbers as keys, need to understand effects on component updates and remounting
- validation is impacted, best bet would be to disallow fiddle/ident spec validation on resultsets

**Comment by khardenstine** [comment]
Punting on the actual collisions

**Comment by dustingetz** [comment]
I understand this now and it may be in my line of fire

**Comment by dustingetz** [comment]
#854 i think fixed this

**Comment by dustingetz** [comment]
The design issue here is that we have a keyfn that looks at a row and figures out the key (e.g. dbid). If no db/id or any other identity is pulled, it is likely that there will be duplicates. 

For example, ::name is the identity here, if we remove ::name then these records are the same:
```
{:neighborhood/name "Admiral (West Seattle)",
  :neighborhood/district {:db/id 17592186045521, :district/name "Southwest", :district/region {:db/ident :region/sw}}}
 {:neighborhood/name "Alki", :neighborhood/district {:db/id 17592186045521, :district/name "Southwest", :district/region {:db/ident :region/sw}}}
 ```

The fix is actually to disable the duplicate detection. Since the records are indistinguishable, they actually do have the same lookup key to get the value of the record, it doesn't matter which record you get. Iterating the resultset is still driven by the ordered vector result as emitted from Datomic, it just uses that ordered result to generate a lookup key. So it works!

**Comment by dustingetz** [comment]
And here it is working:
![image](https://user-images.githubusercontent.com/124158/52145528-31109700-262f-11e9-8e29-2c8d21b295be.png)


@khardenstine  pls review

**Comment by dustingetz** [comment]
This does result in reagent key warnings from the table (detecting the duplicate key). It is hard to fix, but possible. We want to have nil key in this case so the table can fallback to row index to resolve the warning. However this needs to be done without breaking the internal index lookups, which use the value as the key in the absence of smarter identity. This just means coordinating the keyfns inside the context result indexing, but returning a nil key to the outside world. Ultimately the view should see a missing key warning in this case and provide their own fallback e.g. with map-indexed.

**Comment by dustingetz** [comment]
This is  legal
![image](https://user-images.githubusercontent.com/124158/52150759-f0b91500-263e-11e9-87a1-7288e00824dc.png)
