### ISSUE TITLE
Postwalk in the formula routing (converting entity types) is not walking

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#307]
Postwalk does not understand how to descend into Entity. Thus I believe we have been getting lucky. I believe it should be a pre-walk. (To pretty print a pull-soup, we need to prewalk)

**Comment by dustingetz** [comment]
There is a comment "walk trees wants a map" – that's because it doesn't understand Entity.

**Comment by khardenstine** [comment]
This issue doesn't make sense to me but I could be confused.  postwalk wouldn't understand how to walk an Entity, which required a wrapper.  But once converting an Entity to a ThinEntity, we wouldn't need to descend into the type, you convert the type and are done.

Regardless the Entity is dead, long live the map
