### ISSUE TITLE
Inject browser-ui

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#308]
Invocations to `browser/ui` should be decoupled from the actual ui components.
The ui should be injected.

**Comment by khardenstine** [comment]
The abstraction layer is a WIP.  We really want to inject inside the 3fns for the `stale` component

**Comment by dustingetz** [comment]
This perfectly unifies with recent auto-control and hyperfiddle.ui refactoring, the whole point of which is top-of-the-world dependency injection. The final unification (including navcmp/browser) remains to be done, but no need to track an issue for this.
