### ISSUE TITLE
Lost invalid-css on link errors

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#31]
Tooltip present but no invalid style on the anchor itself
![image](https://user-images.githubusercontent.com/124158/35520038-e7a4d49a-04e3-11e8-98ca-6f71e745ed0b.png)

**Comment by khardenstine** [comment]
This was just a red dashed line underneath before right?
The new dashed pink line that is under all anchors is overriding it.  I would vote get rid of that.

**Comment by dustingetz** [comment]
The pink line under the anchor is important signal, perhaps we can style the text red, or a second bolder underline, or have the red be !important

**Comment by khardenstine** [comment]
!important is pretty useless, the two styles are way too similar to distinguish:
![image](https://user-images.githubusercontent.com/7741805/35648731-b10f7b0c-06a4-11e8-9596-306c33600787.png)

Maybe background-color: light-red?

**Comment by dustingetz** [comment]
Sure, whatever, or make the underline weightier, i dunno
