### ISSUE TITLE
IDE fails to load without home-route

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#317]
http://*.hyperfiddle.net/_/:hyperfiddle.schema!$/
![image](https://user-images.githubusercontent.com/7741805/41430951-76f90ce0-6fdf-11e8-92b6-f57f759c9108.png)

Literally adding any value fixes it (whether the fiddle/lookup exists or not)

Navigating to the index still needs a valid value though

Related: #221 hyperfiddle/hyperfiddle.net#200

**Comment by dustingetz** [comment]
How to reproduce? http://dustingetz.hyperfiddle.site/ redirects to not-found and everything is fine
