### ISSUE TITLE
Tempid resolution buggy in isComponent true case

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#33]
The embed should be valid now. When I click transact and refresh the page, the entity appears

![image](https://user-images.githubusercontent.com/124158/35522861-76938532-04eb-11e8-9df6-af838fc2a16a.png)

**Comment by khardenstine** [comment]
Unable to reproduce this as well, my assumption would be this is reactivity problems and you fixed this.  But I don't see any custom renderers.

First I transacted the retraction of the communication entity:
> ![image](https://user-images.githubusercontent.com/7741805/35651741-c1c89618-06ae-11e8-888e-8d19069cf2e3.png)


Create new, pre stage button:

> ![image](https://user-images.githubusercontent.com/7741805/35651618-648b92e8-06ae-11e8-873d-7e5d04e1cf6b.png)

Post stage button press:

> ![image](https://user-images.githubusercontent.com/7741805/35651689-946ca22c-06ae-11e8-82ec-fe07b2cd0538.png)
