### ISSUE TITLE
schema attr editor is readonly all of a sudden

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#34]
Don't have any idea why or what I did. I navigated from the domain panel as always. Refreshing fixed it.

![image](https://user-images.githubusercontent.com/124158/35524260-11441620-04ef-11e8-9b52-c5ba919d5fbe.png)

**Comment by khardenstine** [comment]
Any console errors?
Need a bit more to go off of.  This could be reactivity issues (#7) or buggy renderers (nothing was glaringly wrong on review) or something else entirely
