### ISSUE TITLE
SSR does not need userportals, let it crash the page and use the IDE to fix it

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#343]
Original title: SSR userportals: Can we use error boundaries instead?

Would this get rid of the div.hyperfiddle-userportal wrapper div which is highly frustrating when working with bootstrap layouts?

**Comment by dustingetz** [comment]
No: https://reactjs.org/docs/error-boundaries.html

**Comment by dustingetz** [comment]
"This is intentional / a known limitation. With streaming rendering it's impossible to "call back" markup that has already been sent, and we opted to keep renderToString and renderToNodeStream's output identical." https://github.com/facebook/react/issues/10442

**Comment by dustingetz** [comment]
What if we removed user portals entirely from SSR? There isn't SSR in dev mode, so anything that breaks is fixable. User portals are like a developer convenience

**Comment by dustingetz** [comment]
Here is the motivating use case, which fails to style properly as a bootstrap layout due to the wrapper divs (A workaround is to add yet another wrapper div for the layout)

```
[:div.row
    [hyperfiddle.ui/browse :index [] ctx nil {:class "col-sm-2"}]
       (let [[_ [inner-fiddle & inner-args]] (:route ctx)]
     [hypercrud.browser.core/ui-from-route [inner-fiddle inner-args] ctx "col-sm-10"])]
```

**Comment by dustingetz** [comment]
Currently running this patch, gonna see how it goes
![image](https://user-images.githubusercontent.com/124158/42170805-8d7ec6c6-7de5-11e8-9068-6e1dddf6cc06.png)

**Comment by dustingetz** [comment]
This is working like a charm, I am commiting it

**Comment by dustingetz** [comment]
I am confused why this other type of error does not crash the SSR though:

![image](https://user-images.githubusercontent.com/124158/42172400-def97768-7de9-11e8-8ee6-5c589d2c9057.png)

**Comment by dustingetz** [comment]
The exception is caught in the either and propogated properly to the renderer, that's why. It's in a data stack frame, not a view stack frame. So, only view errors will crash the page.

**Comment by khardenstine** [comment]
I'm not a fan of this tradeoff: error handling inconsistencies just for styles.
It would be really nice if this was implemented: https://github.com/facebook/react/issues/12014

Not sure if there is a lower level API that provides a short on renderToString/Stream, since we know the user-portal in node is only called by renderToString/Stream.

**Comment by dustingetz** [comment]
@khardenstine What is inconsistent about it? I have seen zero issues running this patch in prod all week

**Comment by khardenstine** [comment]
Unless I'm missing something, SSR no longer renders errors the same, they blow the entire stack now.   Thus mounting in the browser would not generate the same dom as SSR.

**Comment by dustingetz** [comment]
Oh, right. My stance for the time being is: go fix your "source code" in the IDE. We can do the right thing when React gives us the tools to do so
