### ISSUE TITLE
contrib.try -> contrib.try$ to silence warnings

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#346]
`WARNING: Namespace contrib.try contains a reserved JavaScript keyword, the corresponding Google Closure namespace will be munged to contrib.try$`

**Comment by dustingetz** [comment]
i'll wait until after merge

**Comment by khardenstine** [comment]
Has this been done already and just needs to be merged? Or is this up for grabs?

**Comment by dustingetz** [comment]
It's not done but um i can't reproduce so that's something

**Comment by khardenstine** [comment]
dev builds have hacked in `:warnings {:munged-namespace false}` https://github.com/hyperfiddle/hyperfiddle.net/commit/02abba50515a1d412003131f67dd6785a3413be5

Here is CI from a few hours ago:

![image](https://user-images.githubusercontent.com/7741805/43108373-830b7d44-8eaf-11e8-9180-a91eac6bc618.png)
