### ISSUE TITLE
Ability to sort iframe links in data mode

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#36]
The nav options should render up top
![image](https://user-images.githubusercontent.com/124158/35525759-727e08de-04f3-11e8-9e7b-092ddced7012.png)

**Comment by khardenstine** [comment]
This is a tad more demanding than just ordering links in relation to each other.  We need a way to express the location in relation to the data component (before or after).  This is starting to drift into custom renderer territory.

Interestingly at first glance of that screenshot, that "Merchant dashboard" starts to look like foundation, albeit userland.

**Comment by dustingetz** [comment]
say more about what could be foundation ish?

**Comment by dustingetz** [comment]
related requirements question is if the anchors need to be repositioned. the action here should be below

**Comment by dustingetz** [comment]
Fixed by link/class changeset
