### ISSUE TITLE
Shadow links: going from sys to not-sys gets link/dependent backwards

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#360]
My link was stuck at link/dependent true but drawing in the :head, across refreshes. Toggling it fixed it.

**Comment by dustingetz** [comment]
THere are many bugs here, links tab is pretty much unusable for link shadowing right now. You need to know when it breaks so you can work around here.

- [ ] Incorrect readonly state (#359)
- [ ] link/fiddles options stays disabled (#359)

there are more

**Comment by dustingetz** [comment]
Dancing with rel shadowing (and refreshes) to disable a syslink:
![image](https://user-images.githubusercontent.com/124158/42587386-8ff534ce-8508-11e8-9ad9-1a2485b2e00b.png)

**Comment by khardenstine** [comment]
The logic for sys links was definitely super broken.  I think I fixed it all with 6cd70b883b5630a47816d307133812e2aa97d966
