### ISSUE TITLE
field support for recursion-limit

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#363]
https://docs.datomic.com/on-prem/pull.html#recursive-specifications

Missed from #249

https://gist.github.com/khardenstine/0ab6c158eb291f4e387ef23377b7e0fc

**Comment by khardenstine** [comment]
Interesting to note:

> If a recursive subselect encounters an entity that it has already seen, it will not apply the pattern, instead returning only the :db/id of the entity. Thus recursive select is safe in the presence of cycles.

**Comment by dustingetz** [comment]
The current behavior unifies the pull spec with the resultset, so you get a set of longs here, which is perfectly fine.

**Comment by dustingetz** [comment]
![image](https://user-images.githubusercontent.com/124158/53421967-98aacf80-39ac-11e9-86ef-1529ed7a287b.png)
