### ISSUE TITLE
Fix table layouts in firefox (schema editor, fiddle src links, etc)

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#367]
![image](https://user-images.githubusercontent.com/124158/42728228-10d6f2da-8784-11e8-9066-1c7a6fb04361.png)

![image](https://user-images.githubusercontent.com/124158/42728230-30987df0-8784-11e8-9f97-e789141c2c9d.png)

reproduced to go here in firefox: http://jeremytaylor.hyperfiddle.net/_/:hyperfiddle.schema!$/

**Comment by khardenstine** [comment]
`max-width: 0` on `div.ui.hyperfiddle-schema th` seems to be the culprit

![image](https://user-images.githubusercontent.com/7741805/42730462-abbaabc8-87c2-11e8-8053-ffcd3d560ce9.png)

**Comment by dustingetz** [comment]
th { max-width: 0 } is used in all tables, i will sort it out

**Comment by khardenstine** [comment]
Closable?

**Comment by dustingetz** [comment]
Needs manual migration, i will do it
