### ISSUE TITLE
don't show navigate dirty-prompt if popover open but staging area is empty

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#37]

**Comment by khardenstine** [comment]
Some components use local state, that user work would be lost.

**Comment by dustingetz** [comment]
i see, didn't realize that. if alt-click is "ide" feature only it may not
matter?

**Comment by khardenstine** [comment]
Alt-click is not the only escape path that warrants a prompt:
- if the user uses the browser back/forward within a popover (not sure if we actually capture this yet)
- if there is ever an inline link within a popover (definitely an odd design decision by a user, but possible)

**Comment by dustingetz** [comment]
Inline links in popovers are legit for "middle click" type flows, though unclear if that would ever happen on a managed popover (as opposed to an iframe menu)
