### ISSUE TITLE
Two datoms conflict often when blogging

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#372]
![image](https://user-images.githubusercontent.com/124158/42854785-90f6cace-8a0b-11e8-9b03-949a85f34f6f.png)

**Comment by dustingetz** [comment]
![image](https://user-images.githubusercontent.com/124158/42854871-e9cf9b4e-8a0b-11e8-8c74-b6332d8abe04.png)

**Comment by dustingetz** [comment]
I think it's when i alt-tab before blur

**Comment by khardenstine** [comment]
on-blur is no longer a thing
