### ISSUE TITLE
Reaction regressions from June

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#373]
Not yet triaged sorry. I think these are separate from the react-context regressions which are not listed here.

- [ ] Reaction: Domain/css editor resets scroll (image margins on hello world)
- [ ] Reaction: hfhf (datamode) to hfhf-domains - saw old embed
- [ ] Reaction: “assert failed: fiddle”
- [ ] Reaction: “no matching clause” (attr in pull doesnt exist)
- [ ] Reaction: changing pull-database did not react existing popover (bc route i guess)
- [ ] Reaction: changing pull expression made tutorial toc readonly, data toggle fixed
- [ ] #231 Table not remounting on url change

this one might be react-context
- [x] #344 reaction broken: render-inline false->true when !browse shows "link has no fiddle"

**Comment by khardenstine** [comment]
[This](https://github.com/hyperfiddle/hyperfiddle/commit/dae86c88403c16dec402d1f04bb753e2595856a6) should probably help/solve most of these issues.
Opened a general ticket #393 for the crap that is our user-portal

**Comment by khardenstine** [comment]
This is now 3months old. Can it be closed? Can any actual issues be triaged and broken out into there own issues?

**Comment by dustingetz** [comment]
This can be closed imo
