### ISSUE TITLE
Reactions: alt-click handler is stale after docs sidebar navigate

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#374]
I believe this is a new regression

**Comment by khardenstine** [comment]
I'm not seeing this, any tighter reproduction steps?

**Comment by dustingetz** [comment]
1. http://tank.hyperfiddle.net/ , alt-click on the h1 to open src
2. alter the view e.g. the h1 text
3. alt-click h1 again to open src – observe nothing happens

**Comment by dustingetz** [comment]
Might be same bug as #635

**Comment by dustingetz** [comment]
Is this related to tempid/smart-entity-key? I think no, because these are not new entities, and the issue is pretty old.
