### ISSUE TITLE
Clean up ctx

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#376]
Current necessary values:
- :peer
- :hypercrud.browser/data
- :hypercrud.browser/eav
- :hypercrud.browser/fiddle
- :hypercrud.browser/field
- :hypercrud.browser/parent
- :hypercrud.browser/path
- :hypercrud.browser/route
- :hypercrud.browser/validation-hints

Other used values (can be refactored away):
- :branch (encase inside runtime)

UI:
- :hypercrud.ui/display-mode
- :hyperfiddle.ui/debug-tooltips
- :hyperfiddle.ui/iframe-on-click
- :hyperfiddle.ui/layout
- :hyperfiddle.ui/sort-col

---

Removed:
- :user-with! (see `hc.b.context/with-tx!`)
- :hypercrud.browser/fat-attribute (see `hc.b.context/hydrate-attribute`)
- :hypercrud.browser/schema
- :navigate-cmp
- :target-route
- :host-env
- :hypercrud.browser/request
- :user-renderer
- :hypercrud.browser/fields
- :hypercrud.browser/data-cardinality
- :alpha.hypercrud.browser/ui-comp
- :hypercrud.browser/attribute
- :hypercrud.browser/result
- :hypercrud.browser/source-symbol (see `hc.b.context/dbname`)
- :uri
  - ~~hc.b/auto-entity-from-stage should accept a second parameter for dbname (solves :uri context associng)~~
  - ~~tx-fns need to work with dbnames not uris~~ #496
- :hypercrud.browser/links
- :hyperfiddle.ide/user
- :hypercrud.browser/schemas
- :hypercrud.browser/invert-route (https://github.com/hyperfiddle/hyperfiddle/commit/e334632da7ab0a1ffa624e94d7a2a0fb281eede7)
- :hypercrud.browser/attr-renderers
- :hypercrud.browser/domain
- :hypercrud.browser/source-domain
- :hyperfiddle.runtime/branch-aux
- :hypercrud.ui/error

**Comment by dustingetz** [comment]
`:hypercrud.browser/data` can be factored away

**Comment by dustingetz** [comment]
- [ ] Lift all ctx keys into reaction (is this something that should eventually happen?)

**Comment by khardenstine** [comment]
The context has been repopulated with a ton of new keys.  A new ticket can be opened if this becomes a goal again
