### ISSUE TITLE
hyperfiddle.hyperfiddle.net default route can be simpler

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#378]
I think this makes more sense:

![image](https://user-images.githubusercontent.com/124158/43037752-3fc194fa-8cdf-11e8-8136-2374cd3034e8.png)

![image](https://user-images.githubusercontent.com/124158/43037740-1ed8e428-8cdf-11e8-91d1-89f280d4b41d.png)

Src mode is unchanged:

![image](https://user-images.githubusercontent.com/124158/43037745-2dad23ec-8cdf-11e8-9209-d369df7b438e.png)

**Comment by dustingetz** [comment]
In fact for src mode, the datomic arg is of course ignored, proof:
![image](https://user-images.githubusercontent.com/124158/43037763-7dae58a2-8cdf-11e8-9441-d8465a739e11.png)
![image](https://user-images.githubusercontent.com/124158/43037767-8c7ee676-8cdf-11e8-9c5e-560c0e4308d9.png)
![image](https://user-images.githubusercontent.com/124158/43037768-8f509d2c-8cdf-11e8-81cc-0608dc9ded81.png)

**Comment by khardenstine** [comment]
LGTM.  The pull-expression is completely defined, so the auto-links will still be defined for `'tempid'`.
