### ISSUE TITLE
tempid collision :ref :isComponent

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#38]
![image](https://user-images.githubusercontent.com/124158/35534048-50c3fa7c-050d-11e8-8a8d-58bd78fb9ffd.png)

**Comment by dustingetz** [comment]
I did not and I cant reproduce it today, but I didn't fix it, did you?

**Comment by dustingetz** [comment]
Could it be the reaction

**Comment by dustingetz** [comment]
Yes, It is the reaction that fixes it. removing "result @(:result ctx)" reproduces the problem

**Comment by khardenstine** [comment]
I would suspect this is an issue with any attribute/many create new link.
deterministic-ident is likely never receiving a reacted value:
https://github.com/hyperfiddle/hyperfiddle/blob/9fb25643986f37f16ff76373b9feab50e18b7a49/src/hypercrud/browser/auto_anchor_formula.cljc#L41

**Comment by khardenstine** [comment]
Can you @dustingetz  confirm this is no longer an issue?

**Comment by dustingetz** [comment]
Can't rep 
![image](https://user-images.githubusercontent.com/124158/37108430-1078d2a2-2205-11e8-9cef-90fd60208223.png)
