### ISSUE TITLE
Reactions: open popovers don't react to renderer changes

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#397]

**Comment by khardenstine** [comment]
http://hyperfiddle.hyperfiddle.net/:hyperfiddle.ide!new-link/~entity('$','-885565814')#:src

![image](https://user-images.githubusercontent.com/7741805/43277100-f916ed44-90d4-11e8-84ad-0deb30f0c963.png)

**Comment by khardenstine** [comment]
Fixed in master:
tested on new post:
http://demo.hyperfiddle.site/:dustingetz.tutorial2!blog/
http://demo.hyperfiddle.site/:dustingetz.tutorial2!new-post/~entity('$','hyperfiddle.tempid--853640389')
