### ISSUE TITLE
cardinality many incorrectly dispatching to form renderer

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#399]
:board/threads is :many – http://yellowdig.hyperfiddle.net/:admin!board-masterlist/

![image](https://user-images.githubusercontent.com/124158/43275978-52c328c0-90d1-11e8-9b6a-2b88351aeabe.png)

**Comment by khardenstine** [comment]
Thats an old inlined link. Updating the pull to be nested, and disabling that invalid sys-edit fixes it.
![image](https://user-images.githubusercontent.com/7741805/43276816-080dabcc-90d4-11e8-926d-24b49aaa5f3a.png)

**Comment by khardenstine** [comment]
Also that sys-edit probably used to be an attribute flavored EntityRequest, which as of this morning no longer exists
