### ISSUE TITLE
splat positioned wrong

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#400]
Should be first because * is up front imo, i doubt we are ordering by this rn
http://yellowdig.hyperfiddle.net/:admin.board-masterlist!board/~entity('$',17592186045425)

![image](https://user-images.githubusercontent.com/124158/43277319-b2a3ae8c-90d5-11e8-90a7-2a1bdc8f960f.png)

**Comment by khardenstine** [comment]
It is working as designed.
The logic is that splat expands to the inferred fields FIRST, then it renders the magic-new AFTER.
That expansion takes place entirely within position of the asterisk.

E.g.
`[:a :b * :y :z]`

If we infer `[:j :k]` from the results, the fields would be:
`[:a :b :j :k magic-new :y :z]`

**Comment by dustingetz** [comment]
Thanks, fixed the pull
