### ISSUE TITLE
Don't use middle click for opening new tabs

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#401]
On Windows, middle click on scrollable panes changes the mouse behavior to drag the content around.
We absolutely cannot steal this behavior.
Technically they are currently coexisting, but a new tab opens every time you middle click which is unwanted.

**Comment by khardenstine** [comment]
Couldn't find a visual of this behavior, but its mostly like this, except you middle click first to enable that scroll mode:
https://www.youtube.com/watch?v=VLv_wAfVO9A

**Comment by dustingetz** [comment]
This is pretty killer problem. I am thinking about just doing cmd-click instead of middle click, and forcing them to learn it in the tutorial.

**Comment by khardenstine** [comment]
Solved with #449 and https://github.com/hyperfiddle/hyperfiddle/commit/a8034e9a1e10cb3b4976831f5d2c7a23a70b3658
