### ISSUE TITLE
Reaction: "query should be vector or map"

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#404]
Repro:
1. Go to workshop (don't ever transact to this domain ever!) <http://workshop.hyperfiddle.net/:index/~entity('$','tempid')>
2. Paste this stage, observe a table <http://dustin.hyperfiddle.net/:workshop!options-done/>
3. Paste this stage, observe error, data/view toggle repairs <http://dustin.hyperfiddle.net/:workshop!table-form-equivalence/>
4. Goto 2

**Comment by dustingetz** [comment]
![image](https://user-images.githubusercontent.com/124158/43357202-db24db16-924b-11e8-933a-2140d69c534c.png)

**Comment by khardenstine** [comment]
I'm guessing this was a staleness/reaction bug, because the query from that stage seems fine:
```clj
[:find (pull ?e [:db/id 
                 :db/ident 
                 #_:reg/gender
                 {:reg/gender [:db/ident]}]) 
 :where
 [?e :db/ident ?v]
 [(namespace ?v) ?ns]
 [(ground "shirt-size") ?ns]]
```

Otherwise the linked stage area is missing a ton of renderer migrations, so the only usable testable view is data mode (which does not reproduce)
