### ISSUE TITLE
Special "shortcuts" sort order should be in that view only

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#407]
This is really surprising as a default on general queries
![image](https://user-images.githubusercontent.com/124158/43370022-b7d392f6-9345-11e8-8f5d-803e0a01f4b3.png)

**Comment by khardenstine** [comment]
It does work that way.  Your table is default sorting on keywords:
```clj
(sort [:whoami :blog/index :index :beta :consulting :beta/waiting])
=> (:beta :consulting :index :whoami :beta/waiting :blog/index)
```

Shortcuts doesnt look like that.
Here you can compare, view is our custom function on top, data mode behind it with the plain sort:
![image](https://user-images.githubusercontent.com/7741805/43398149-350de368-93d5-11e8-947e-c261d81c9329.png)

**Comment by dustingetz** [comment]
Jesus. Clojure WAT?
