### ISSUE TITLE
very specific iframe is NPE, and I can't see why

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#41]
http://litepay.hyperfiddle.net/ezpyZXF1ZXN0LXBhcmFtcyB7OmVudGl0eSAjZW50aXR5WyIkIiAxNzU5MjE4NjA0NTQ3Ml19LCA6Y29kZS1kYXRhYmFzZSAibGl0ZXBheSIsIDpsaW5rLWlkIDE3NTkyMTg2MDQ1NTA2fQ,,

![image](https://user-images.githubusercontent.com/124158/35580310-a9d45f2c-05b6-11e8-91a7-6a55cc828881.png)
click edit... busted formula here? (its a sys formula)
![image](https://user-images.githubusercontent.com/124158/35580324-b4350e76-05b6-11e8-9fb4-179980ef4b8a.png)

Can't type into these. Can't even retract Philadelphia, which is legit. Super weird.
![image](https://user-images.githubusercontent.com/124158/35580349-c4c08496-05b6-11e8-88f0-f75618d9f3d6.png)

**Comment by dustingetz** [comment]
Oh, it's a failure to convert the tree into a #entity

**Comment by khardenstine** [comment]
This is just a missing dbid in the pull expression
