### ISSUE TITLE
CSS editors can't be code anymore

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#414]
@khardenstine  i thought you fixed this in july?

parinfer breaks them badly

**Comment by khardenstine** [comment]
I don't know what happened, but the attribute renders got changed to code instead of css:
![image](https://user-images.githubusercontent.com/7741805/43483374-8050b6e8-94d9-11e8-87cb-ba4b75da00db.png)

**Comment by khardenstine** [comment]
I flipped them back to`hf.ui.controls/css`
