### ISSUE TITLE
picklist values are broken if :db/id is not pulled, which is not intuitive

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#419]
related https://github.com/hyperfiddle/hyperfiddle/issues/551

**Comment by dustingetz** [comment]
db/ident is enough
![image](https://user-images.githubusercontent.com/124158/43584123-7d7baaa2-962f-11e8-9f66-4266f2f88efd.png)

**Comment by khardenstine** [comment]
Identity inference is a pervasive problem system wide.  It is applicable to any attribute with `:db/unique :db.unique/identity`.

It's also a problem that we set forms to read-only when they have a unique identifier but no db/id

**Comment by khardenstine** [comment]
https://docs.datomic.com/on-prem/identity.html#entity-identifiers
