### ISSUE TITLE
r/partial fact dump

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#425]
This is the thing that is impossible:
```
(defn user-component [user-fn val props ctx]
  [user-portal (ui-error/error-comp ctx)
   [user-fn val props ctx]])

(defn user-control [?user-fn]
  (if ?user-fn
    (fn [val props ctx]
      [user-component ?user-fn val props ctx])))

(defn eval-renderer-comp+ [?f]
  (if ?f
    (eval-renderer-comp nil ?f)))

(defn attr-renderer [ctx]
  @(->> (context/hydrate-attribute ctx (:hypercrud.browser/attribute ctx))
        (r/fmap (r/comp eval-renderer-comp+ blank->nil :attribute/renderer))
        (r/fmap user-control)))


[:body :attribute _ false _] (or (attr-renderer ctx) control+)
```

**Comment by dustingetz** [comment]
https://groups.google.com/forum/#!topic/reagent-project/0FXwr2Dt7QU

**Comment by dustingetz** [comment]
Also, with-data and with-hyper-control can be used to cause gentler reactions (not recomputing as much). I opted for the flattest possible structure instead, which re-computes the hyper-control when the value changes. I think ultimately that is a very cheap computation and not worth the extra layer. Maybe I am wrong. I wanted to be sure I understood the problem also.

```
(defn with-value "Separate the data reaction to avoid thrash everywhere else" [control props ctx]
  [control @(:hypercrud.browser/data ctx) props ctx])

(defn with-hyper-control "reactions" [props ctx]
  [with-value (hyper-control ctx) props ctx])
```

**Comment by khardenstine** [comment]
The extra layer is good.  It lowers the cognitive load of us manipulating parent components.  Makes it harder to accidentally trash reaction perf.

**Comment by dustingetz** [comment]
This is also not allowed: 
`[hyperfiddle.ui/browse :hyper-control [] ctx (hyperfiddle.ide.hf-live/hf-live :fiddle/query :fiddle/markdown :fiddle/links)]`

Not sure why yet, but changing fiddle/markdown is stable, but changing fiddle/query resets the component and leaks memory.

**Comment by dustingetz** [comment]
Reagent can be forked to use a singleton map to cache :cljsReactCmp instead of putting it on the function, this would yield IEquiv for components.

**Comment by dustingetz** [comment]
If we replaced Reagent with core.async, i think we could get back reaction termination with a "shouldUpdate"/memoizer thing interposed through the core.async chain. Don't forward the event past this stage if if's the same as the previous one. Works because core.async is imperative, you have to >! to forward.

In fact is this a difference between r/track and fmap? r/track you have to deref the next stage
