### ISSUE TITLE
SSR failed on: Assert failed: (reactive? src) – on WWW only

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#426]

**Comment by dustingetz** [comment]
http://www.hyperfiddle.net/:demo!shirt-sizes/~entity('$',17592186046381)

Pretty sure this is the (comp str deref) instead of (comp str identity) but it should not break ssr – IDE should attach

**Comment by dustingetz** [comment]
If you softnav there, the right stuff happens and it is repairable:

![image](https://user-images.githubusercontent.com/124158/43738126-945d18f4-9991-11e8-927b-9c36e2d0fd9f.png)

**Comment by dustingetz** [comment]
To reproduce, 
1. http://www.hyperfiddle.net/:demo!hyper-control/
2. inspect src, change shirt-size :options to :options-foo
3. change render-inline to false
4. middle-click the "options-foo" anchor to see it in new tab with busted SSR

![image](https://user-images.githubusercontent.com/124158/43738184-c1e7369c-9991-11e8-8b15-a55b0bc23a29.png)

**Comment by dustingetz** [comment]
![image](https://user-images.githubusercontent.com/124158/43738220-e75d7e18-9991-11e8-9683-62397dbb9421.png)

**Comment by khardenstine** [comment]
IDE is attaching, the exception is not being caught correctly and its crashing the browser too (check your console).

Ignoring the main issue of the browser crashing, there are a few missed migrations:
- `hf.ui/table`, the undefined extra parameter sort-fn
- the extra deref and arity problems on the second field invocation

**Comment by dustingetz** [comment]
Yeah I know, I left it broken. There is a hyperfiddle regression here though right?

**Comment by dustingetz** [comment]
This is an extremely fatal crash inside of semantic-css, thus no UI will ever draw at all in top or bottom. WTF?

**Comment by dustingetz** [comment]
The ctx is empty - that's caused by the bad table renderer. But why is the IDE crashing?

![image](https://user-images.githubusercontent.com/124158/43786847-a6d814c4-9a37-11e8-92d3-2d2507183816.png)

**Comment by dustingetz** [comment]
The eval-renderer-comp doesnt seem to have anything to do with it (reverting that change doesnt repair the failure), and the reference was stable anyways due to the memoizing eval

**Comment by dustingetz** [comment]
SSR disagrees wiht clinet, becuase SSR doesn't have error boundaries, whjole page is crashed wiht a 3 line HTML repsonse. Clinet reattaches and vdom doesn't match so client and should blast it. but itd oesnt!

![image](https://user-images.githubusercontent.com/124158/43791503-d92b1b90-9a43-11e8-80bd-b9372660fd78.png)

![image](https://user-images.githubusercontent.com/124158/43791495-d49e7342-9a43-11e8-80f2-e447ff9695f4.png)

How can the dom and the vdom be so out of sync?

**Comment by dustingetz** [comment]
Interesting
- two data react roots

**Comment by dustingetz** [comment]
FIshy:
![image](https://user-images.githubusercontent.com/124158/43791585-1e16eb4e-9a44-11e8-87c6-916923fdb14a.png)

**Comment by dustingetz** [comment]
Karl says:: Did it bc streaming, want to stream the response and not have to render the full body firstr and glue it into the head

**Comment by dustingetz** [comment]
renderToStaticNodeStream did fix the data reactroot double, but not the real problem
![image](https://user-images.githubusercontent.com/124158/43791688-7ae73266-9a44-11e8-910b-93cbb984e7c0.png)

**Comment by dustingetz** [comment]
Dustin thinks this is only in play on WWW in the patholigical case where there is both SSR and the IDE toolbar. Can't rep in userland dustingetzcom. I think React reconciler is getting confused in reusing dom when attaching.

**Comment by dustingetz** [comment]
Table has busted arity, and deref is identity
```
(let [{:keys [:hypercrud.browser/fiddle
              :hypercrud.browser/result]} ctx]
  [:div {:class class}
   [hyperfiddle.ui/table
    #(vector 
       (hyperfiddle.ui/field [0 :db/ident] %)
       (hyperfiddle.ui/field [0 :reg/gender] % (comp str name :db/ident deref))
       (hyperfiddle.ui/field [0] %))
    hyperfiddle.data/sort-fn
    ctx]])
```

**Comment by dustingetz** [comment]
The migration is finished in prod, but can paste it back to repro. It's the shirt-size options.

**Comment by khardenstine** [comment]
I don't see any action item remaining.  Can this be closed?
