### ISSUE TITLE
system link dbid generation is not unique

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#428]
We just hash path, but that is not guaranteed to be unique on a page:

https://github.com/hyperfiddle/hyperfiddle/blob/baa4039e0d2f72ab0c4c46ba560b107003abfc2e/src/hypercrud/browser/system_link.cljc#L88

![image](https://user-images.githubusercontent.com/7741805/43839356-dff7bff2-9aeb-11e8-89a3-d773e9faf390.png)

**Comment by dustingetz** [comment]
Superseded by  #826
