### ISSUE TITLE
auto-transact settings wiped on deploy

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#436]
![image](https://user-images.githubusercontent.com/124158/43868304-fe143606-9b3a-11e8-9161-922b14e24ace.png)

**Comment by dustingetz** [comment]
![image](https://user-images.githubusercontent.com/124158/43868347-2b0ee7b4-9b3b-11e8-9733-532cd00d3bf7.png)

**Comment by khardenstine** [comment]
The deploy after the next will have much more stable localstorage (all values not just auto-tx).
The entire value is now version incremented by hand (no longer by the build sha).

**Comment by khardenstine** [comment]
Wait I never use auto-transact and I havn't had to toggle it in awhile, there is another problem here.
Every page refresh isn't reading the localstorage auto-tx settings

**Comment by khardenstine** [comment]
The entire staging area and auto-tx state is hosed (related: #431) from the database modeling
