### ISSUE TITLE
Clean up auto-control

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#45]
There are two auto-control fns (prime and unprime).
How do they relate? what is public api?

**Comment by dustingetz** [comment]
auto-control' is real
auto-control is legacy

not sure but i dont think any of this is public API now. It's all data driven. The schema pattern matching should be data driven core.match config stored on the domain.

**Comment by khardenstine** [comment]
The tension I'm seeing is there is no clean way to override the UI at the field/attribute/cell level.  I think ultimately any of the custom renderers I'm looking at just want to lightly amend a cell in a table or form and then immediately jump back into the default behavior.

This comment describes it perfectly
https://github.com/hyperfiddle/hyperfiddle/blob/82f91de4fba695f6c31dac3f943539cebc407a03/src/hypercrud/ui/auto_control.cljs#L77-L88

Our current options
- `:control` or `-> ctx :fields attr :renderer` or `:attribute/renderer` are all basically the same, and have no re-entry hook.
- `:cell` can easily just call the default `auto-control'`.  However it mustknow if is inside a form or table and provide applicable stylings (and there is also no way to get the default link behavior)

The legacy `auto-control` is basically the only re-entry point available right now, and its barely sufficient for most cases.

**Comment by dustingetz** [comment]
I see, so the interface is `(defn auto-control [ctx f])`, i've seen that pattern before in our codebase

**Comment by dustingetz** [comment]
Removing unused params from auto-control today, and putting ctx first, because it makes markdown cell renderers work

**Comment by dustingetz** [comment]
- [ ] migrate link/bindings (sets readonly) to use fiddle renderer cell api
  - [ ] remove control-props (blocked on link/bindings :read-only)
- [ ] migrate schema-attr-renderer to fiddle/renderer cell api
  - [ ] remove old auto-control interface (blocked on schema attr renderer legacy)
  - [ ] remove field/renderer interface (used by schema attr renderer legacy)

**Comment by dustingetz** [comment]
the link/fiddle renderer is a table, and the cell api doesn't handle the table case yet

**Comment by dustingetz** [comment]
(sources/all-source-vals! :fiddle/bindings)

**Comment by dustingetz** [comment]
Legacy auto-control removed, auto-control' is now auto-control. It's unclear if this is public api. Right now, it is indeed public API and is used by the schema-attribute-renderer.

**Comment by dustingetz** [comment]
This requires migrating the cell-api for bitcoin-merchant 

`!cell[(comp (partial vector :div.value) str :communication/email-address deref :value #(nth %& 2))](0 :invoice/from)`
becomes 
`!cell[(comp (partial vector :div.value) str :communication/email-address deref :value)](0 :invoice/from)`
