### ISSUE TITLE
Elevate route hint from hf.ui/result to hf.ui/fiddle

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#459]
hf.ui/result is used recursively within one route, as such the hints are appearing multiple times:
![image](https://user-images.githubusercontent.com/7741805/44131267-d2dc6bf4-a01f-11e8-961c-b5b24b27db5a.png)

Also being generated incorrectly:
![image](https://user-images.githubusercontent.com/7741805/44131471-49e3faf4-a021-11e8-9c87-938c331ac4b8.png)

**Comment by dustingetz** [comment]
Resolved in #467
