### ISSUE TITLE
hf-live (and manual src mode iframes) fails to shadow links

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#462]
All shadowing (not just links) should probably happen within  src-mode (and fiddle-src should probably use that feature too)
https://github.com/hyperfiddle/hyperfiddle/blob/0e92b9ddda5ded3b615926488285354690d86a91/src/hyperfiddle/ui.cljs#L198-L209

![image](https://user-images.githubusercontent.com/7741805/44167435-19068480-a09c-11e8-8df6-637f7701b6c0.png)

Renderer:
```clj
[:div {:class class}
 [hyperfiddle.ui/iframe ctx {:route [:Districts]
                             :user-renderer (hyperfiddle.ide.hf-live/hf-live :fiddle/ident :fiddle/type :fiddle/query :fiddle/renderer :fiddle/links)}]

 [hyperfiddle.ui/iframe ctx {:route [:Districts nil nil ":src"]
                             :user-renderer (partial hyperfiddle.ide.hf-live/docs-embed [:fiddle/ident :fiddle/type :fiddle/query :fiddle/renderer :fiddle/links])}]

 [hyperfiddle.ui/iframe ctx {:route [:Districts nil nil ":src"]}]

 [hyperfiddle.ui/iframe ctx {:route [:Districts nil nil ":src"]
                             :user-renderer hyperfiddle.ide.fiddles.fiddle-src/fiddle-src-renderer}]
 ]
```

![image](https://user-images.githubusercontent.com/7741805/44167534-6b47a580-a09c-11e8-825e-66fc0d6467e5.png)

**Comment by dustingetz** [comment]
HF-Live has a filter-disabled-links, i think, to hide the crap on the homepage
