### ISSUE TITLE
Regression: Schema new attribute broken

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#472]

**Comment by dustingetz** [comment]
Can't select a valueType:
![image](https://user-images.githubusercontent.com/124158/44347929-1f637a80-a467-11e8-82a3-e401ff7f1f06.png)

**Comment by dustingetz** [comment]
Not a blocker today, moving past

**Comment by khardenstine** [comment]
Lost the default-props merge here: https://github.com/hyperfiddle/hyperfiddle/commit/af53646e8d6175ecf0f269b524e0df885e5cb18a#diff-1258aba364e3f68f6f50af8a07a3b08dL101
