### ISSUE TITLE
 Tupled relation dependency is drawn gray instead of bluegreen

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#478]
- [ ] [beta user tupled q - data mode](http://d.hyperfiddle.net/:hfnet.user!view/'dustin.getz@gmail.com')

Introduced in #467

**Comment by khardenstine** [comment]
Based on our conversations earlier, this behavior is correct.

**Comment by dustingetz** [comment]
Desired behavior is to render both colors at the same time (striped or something)

**Comment by khardenstine** [comment]
Oh ok I read this wrong, that would be cool
