### ISSUE TITLE
Auto-transact in dustingetz.com

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#48]
This generalizes to userland even when the IDE is open.  It further generalizes to the IDE if there is just a branch stack and when the stack is empty, it transacts, thus "ide-transact" is just "stage". This lets us remove the concept of transact entirely.

**Comment by khardenstine** [comment]
> This generalizes to userland even when the IDE is open.

What if the user is building up a data migration along with schema changes?

> It further generalizes to the IDE if there is just a branch stack and when the stack is empty, it transacts, thus "ide-transact" is just "stage". This lets us remove the concept of transact entirely.

How would speculation work at all then?

**Comment by dustingetz** [comment]
the IDE can branch the top of the world for speculation
