### ISSUE TITLE
kill unsafe arity of unwrap

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#482]
Force passing (constantly nil) to silence, more likely #(timbre/warn %)

**Comment by dustingetz** [comment]
It is in contrib.ct now, for category theory

**Comment by dustingetz** [comment]
At first glance, this has surfaced some hidden errors:
![image](https://user-images.githubusercontent.com/124158/44555542-9e74df00-a703-11e8-803a-2cd80d963b24.png)

**Comment by khardenstine** [comment]
Existing tickets #113 #241
