### ISSUE TITLE
Infinite loop when service unavailable

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#487]
![image](https://user-images.githubusercontent.com/124158/44591258-3bc72600-a78b-11e8-8e7f-bc31951a7862.png)

**Comment by dustingetz** [comment]
When the service came back, the page did not recover. (This was triggerede by a transact)

**Comment by khardenstine** [comment]
The service/IO layer has been reworked a few times since this ticket was created (error handling especially).
Tried killing the service and event just the transactor (like the stacktrace indicates). Cannot reproduce.
