### ISSUE TITLE
Define behavior when :db/id is missing from pull-expressions

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#49]
We can either:
- automatically add it under the surface for all queries (ugly)
- warn on omission using validators on the query/pull fields
- provide sane behavior/dont crash (all writes are disabled, cannot build statements without dbids, any other features that need disabling?)

**Comment by khardenstine** [comment]
Quick chat today, we thing we should recursively add db/id automatically to all pull expressions

**Comment by dustingetz** [comment]
Idea: omit :db/id from pull will flip widgets into readonly mode and disable dependent links ?
