### ISSUE TITLE
Pave controls' :read-only & :disabled

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#494]
I'm guessing this mess is an artifact of [on-blur](https://github.com/hyperfiddle/hyperfiddle/issues/13).  We change read-only to disabled in tons of places, when we should just set the bit we want (probably readonly now that we use on-change).  Need to audit userland to see what is just internal cruft vs used.  `hf.ui.controls/entity-props` should probably be split apart as well

Semi-related #268

**Comment by dustingetz** [comment]
#482 #420

**Comment by khardenstine** [comment]
What does this have to do with unwrap?

**Comment by dustingetz** [comment]
Hmm i linked the wrong issue and can't find the right one sorry
