### ISSUE TITLE
remark-generic-extension properties casing

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#497]
- It appears to be react-remark that excessively adds camel-casing
- not sure where reagent kebab-cases.
- have yet to see the remark AST.
- readonly is handled inconsistently EVERYWHERE.

Links for later:
  - https:// github .com/mapbox/remark-react/issues/41#issuecomment-300149088
  - https:// github .com/reagent-project/reagent/issues/389
  - https://reactjs.org/docs/dom-elements.html#differences-in-attributes

# Reagent
```clj
(defn Comp [val props ctx] [:pre (js/pprint-str props)])

[:div
 (let [prop-str "floating=false accent=\"asdf\" readOnly=true readPnly=true what-the-fuck=true"
       md (string/join "\n" ["## Raw prop string:"
                             (string/replace prop-str #" " "\n\n")
                             "## Generated props map:"
                             (str "!f[main.main/Comp](){") prop-str "}"])]
     [hyperfiddle.ui/markdown md])]
```

![image](https://user-images.githubusercontent.com/7741805/44856161-c354df00-ac3a-11e8-980e-5b0373cf9450.png)

# just remark-react
https://codesandbox.io/s/43z045k894
![image](https://user-images.githubusercontent.com/7741805/44856188-d36cbe80-ac3a-11e8-9a90-635d41903c34.png)

# remark-html
https://codesandbox.io/s/lp81kq86pz
![image](https://user-images.githubusercontent.com/7741805/44856838-740fae00-ac3c-11e8-90d5-68b588e4bf14.png)

**Comment by dustingetz** [comment]
What is the issue exactly?
