### ISSUE TITLE
fiddle/renderer shouldn't insta-refresh until the cljs is valid (passes reader at least)

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#498]

**Comment by khardenstine** [comment]
contrib.ui.input/text-adapter works this way, and we should probably just make that a tad more general and compose it with code-mirror.
However these child controls: keyword/long/edn do NOT save their invalid values to database; when a user enters an invalid value, it is stored in component local state, and only propagates upwards once it is valid.
In the long run that is probably a terrible idea (users losing their work if they navigate or close tab), but its probably good enough in the short term.

**Comment by dustingetz** [comment]
We can have a yellow state for unsaved in addition to the red invalid state, or something

**Comment by dustingetz** [comment]
I have it backwards. Red means fix now, this is broken. Yellow means this is saved but fails validation. Restful Web APIs describes "profiles" which is the set of valid classes for an application ontology, so for example we will be able to validate :hf/new :hf/edit etc and mark invalid classes yellow.

**Comment by dustingetz** [comment]
This is super important, right now on the www hflive, if you edit the pull, the whole page crashes (because unless you are super careful, editing the pull will break the pull)

**Comment by dustingetz** [comment]
#712 dupe
