### ISSUE TITLE
data regression: :find relation scalars draws empty

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#499]
- [x] [subquery cookbook](http://www.hyperfiddle.site/:docs/:cookbook!datomic-subquery) Introduced in #467
- [x] broken scalar: element vs element-or-naked 
  - [hfnet :databases](http://hyperfiddle.hyperfiddle.net/:databases/#:src)
  - [hfnet :databases options](http://hyperfiddle.hyperfiddle.net/:database!options-list/)

**Comment by khardenstine** [comment]
I would expect data and view mode to be identical for the following:

# Query:
```clj
[:find (pull $seattle ?e [:db/id :neighborhood/name]) (count ?n)
 :in $seattle
 :where [$seattle ?e :neighborhood/name ?n]]
```

# Renderer:
```
(let [{:keys [:hypercrud.browser/fiddle]} ctx]
  [:div props
   [hyperfiddle.ui/markdown (:fiddle/markdown @fiddle) ctx] 
   [hyperfiddle.ui/table
    (fn [ctx]
      [(hyperfiddle.ui/field [0 :neighborhood/name] ctx)
       (hyperfiddle.ui/field [0] ctx)
       (hyperfiddle.ui/field [1] ctx)])
    ctx]])
```

# View mode
![image](https://user-images.githubusercontent.com/7741805/44885947-bb745980-ac91-11e8-8590-5286d196b878.png)

# Data mode
![image](https://user-images.githubusercontent.com/7741805/44885954-c333fe00-ac91-11e8-877c-420b341d9d37.png)

**Comment by dustingetz** [comment]
@khardenstine  my data mode looks different than yours, mine is closer
![image](https://user-images.githubusercontent.com/124158/44888014-faf47300-ac9c-11e8-836b-a325dc620af6.png)

**Comment by dustingetz** [comment]
I fixed the aggregate, but I disagree with your test.

These are equivalent:

![image](https://user-images.githubusercontent.com/124158/44888739-afdc5f00-aca0-11e8-9bf1-980ce7fe0637.png)

You need explicit entity-links in the view to get it to match.

**Comment by dustingetz** [comment]
Here it is without the extra nested pull, this matches on my machine now
![image](https://user-images.githubusercontent.com/124158/44888827-15c8e680-aca1-11e8-8c4a-9f6156e59647.png)
