### ISSUE TITLE
Surface deprecated warnings from user-fns

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#50]
When evaling a userfn, are deprecation warnings generated?
If so how can we surface them to users?

**Comment by dustingetz** [comment]
If IDE never SSRs then this is a non-issue right?

**Comment by khardenstine** [comment]
user functions are evaled in the browser all the time

**Comment by dustingetz** [comment]
Won't they see the js/console.warn in the IDE?

**Comment by khardenstine** [comment]
Im referring to literal cljs compiler warnings, I don't know if they are generated in cljs selfhost and where they go if they are.

**Comment by dustingetz** [comment]
Not an issue in new hf-defs and hfql
