### ISSUE TITLE
data regression: cardinality crash

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#507]
- [ ] http://www.hyperfiddle.net/:docs/:fiddle-markdown - `!link[new task](:hyperfiddle/new)` (the head link, not the body)

![image](https://user-images.githubusercontent.com/124158/44923110-4ea2a300-ad15-11e8-84dd-d021178abe09.png)

**Comment by dustingetz** [comment]
Bug is that !link doesn't know if he is in the head or not, so it always gets the data now, so how do we know if we assert or not?

![image](https://user-images.githubusercontent.com/124158/44925015-156d3180-ad1b-11e8-8b3a-d43bae41bf18.png)

**Comment by dustingetz** [comment]
@khardenstine  I think the cardinality assert is nonsense. I think the user has to know to do the right thing.

**Comment by dustingetz** [comment]
We can also assert in a different place, like in the renderer that's about to do garbage data

**Comment by dustingetz** [comment]
Yellowdig is also crashing now: http://yellowdig.hyperfiddle.net/:my-boards/

**Comment by khardenstine** [comment]
Yellowdig was a missing context/row call in the map

**Comment by dustingetz** [comment]
http://bitcoin-merchant.hyperfiddle.net/:admin!accounts-pending/

**Comment by dustingetz** [comment]
The bitcoin merchant has a bad path, maybe the assert is right

**Comment by dustingetz** [comment]
- [ ] I have this turned off for hack reasons in #510, this is a reminder to make sure it gets turned back on when i unwind the hack

**Comment by dustingetz** [comment]
This is now turned off in master and prod. It will come back when this auto-link stuff cools down. Currently it has to be off because i use context/focus without data in auto-link generation.

**Comment by dustingetz** [comment]
Auto-field doesn't inspect the cardinality anymore, so this can be turned back on

**Comment by dustingetz** [comment]
This is getting paved anyway, closing
