### ISSUE TITLE
Ability to opt out of auto-formulas or auto tx-fns

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#51]
sys-remove is a great example.  The link is blank and there is no need to generate and run all the formulas (and track unused derefs)

**Comment by dustingetz** [comment]
@khardenstine  can this be closed (the disable link feature?)

**Comment by khardenstine** [comment]
No, this is needed for links that aren't disabled

**Comment by dustingetz** [comment]
Is this a perf issue or can this be closed now as of #467?
