### ISSUE TITLE
Duplicate fields for refs

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#512]
- [ ] http://www.hyperfiddle.site/:demo!form-fields/

![image](https://user-images.githubusercontent.com/124158/44958959-9829f400-aeb5-11e8-8993-b58d39ecaf56.png)

Related commits:
* 537980f142901f1ea8af10b193b8f77368fb0b87 "Add relation column to tables"
* c916ed084abdf8846445155a0ef2102d67667b19 "Lift (field [] entity-links-iframe) out of pull/relation"
* be1bee0f564a12e139457a071ecfcb0bd3df9891 "Untangle form-field’s missing head and find-tuple"

**Comment by dustingetz** [comment]
be1bee0 had an unintended effect of drawing this new button (maybe desirable?):
![image](https://user-images.githubusercontent.com/124158/44958993-fb1b8b00-aeb5-11e8-9b03-ddec7ce12b7c.png)

**Comment by khardenstine** [comment]
Reverted the breaking change from https://github.com/hyperfiddle/hyperfiddle/commit/be1bee0f564a12e139457a071ecfcb0bd3df9891

The field abstraction is a super leaky mess.  We probably should be calling `entity-links(?-iframe)` with a nil label-fn or find a way to just invoke entity-links directly without the field.
`[field [] ctx entity-links (assoc props :label-fn (r/constantly nil))]`
`[entity-links val ctx (assoc props :label-fn (r/constantly nil))]`

**Comment by dustingetz** [comment]
![image](https://user-images.githubusercontent.com/124158/45119952-d0863800-b12a-11e8-9759-28d155720840.png)

![image](https://user-images.githubusercontent.com/124158/45119974-dd0a9080-b12a-11e8-99ca-04b65668eb81.png)

**Comment by dustingetz** [comment]
Fixed in #532
