### ISSUE TITLE
:hidden link is unused

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#515]

**Comment by dustingetz** [comment]
![image](https://user-images.githubusercontent.com/124158/45508199-38a7d000-b762-11e8-8363-29d46d1f547a.png)

**Comment by khardenstine** [comment]
I doubt it impacted this search, but I've been bitten before by forgetting about destructured maps when searching for keywords.
e.g. `:hidden` will not `(let [{:keys [hidden]} m]`
