### ISSUE TITLE
new-link on find-tuple rendered N times for each tuple entry

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#518]
hf/new on beta and user record. both appear in each form
![image](https://user-images.githubusercontent.com/7741805/44988765-d4169500-af59-11e8-87cc-8be61b2b847d.png)

**Comment by dustingetz** [comment]
This is currently not an issue because I don't generate hf/new on relations, it doesn't really make sense. It might also be fixed anyway.
