### ISSUE TITLE
Using r/partial where partial will suffice

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#520]
- `@(r/fmap (r/comp (r/partial = :hf/iframe) :link/rel) link-ref)`

The stable fn ref is never passed as a prop and doesn't need to be stable. There is enough confusion in this area that I think we should strive to choose clojure.core/partial where possible.

**Comment by khardenstine** [comment]
I want to veto this.  This would break reaction caching:
https://github.com/reagent-project/reagent/blob/master/src/reagent/ratom.cljs#L192-L223

Admittedly we are currently broken in other ways, but fixing them are internal details, not rewriting every invocation.  Given the widget on-change/debounce changesets that have landed, render performance is now a pressing concern.

**Comment by dustingetz** [comment]
I see, so any argument passed to r/* must be stable, or you need to deref up front and never call into r/*. So the only other way to write this is `(-> @link-ref :link/rel (= :hf/iframe))` which over-updates.
