### ISSUE TITLE
Staging area regression: can't fix stage to undo something if auto-transact is on

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#521]
Auto-transact is on, so this should never happen. A `localStorage.clear()` verified that the transaction did occur and it is the  stage view is stale.

![image](https://user-images.githubusercontent.com/124158/44995854-f832a000-af72-11e8-834d-e01df9efeb9e.png)

**Comment by dustingetz** [comment]
Next I did a localStorage.clear, and the thing transacted! What?

I've highlighted the error for the missing link that was just retracted by the above stage.

![image](https://user-images.githubusercontent.com/124158/44995904-2b752f00-af73-11e8-9eb3-f956648051d0.png)

**Comment by dustingetz** [comment]
Mis diagnosed. Auto transact is on. It went through properly. The stage view is stale. Noticed in #522

**Comment by khardenstine** [comment]
This is probably debounce regressions

**Comment by khardenstine** [comment]
Partially fixed with 46d7f597489eae75cef8849a42b3f7b5bd57a661
Rest of commits are tagged
