### ISSUE TITLE
bad focus crashes whole page

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#526]
![screenflow](https://user-images.githubusercontent.com/124158/45044254-8ffcc080-b03d-11e8-9f23-555aeaf30efc.gif)

**Comment by dustingetz** [comment]
This is because the assert crashes the server on request side

**Comment by dustingetz** [comment]
This has to validate in the UI by styling links invalid, or something. Disabling the assert.

**Comment by khardenstine** [comment]
https://github.com/hyperfiddle/hyperfiddle/commit/15a919dceadcd93ef5e79c05f4e2e1746b38002e#r30449561
