### ISSUE TITLE
Crashing iframe view loses pink box and can't alt-click to get to source to fix it

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#540]
- [ ] [http://d.hyperfiddle.net/:hfnet.user!view/'dustin.getz@hyperfiddle.net'](http://d.hyperfiddle.net/:hfnet.user!view/'dustin.getz@hyperfiddle.net')

**Comment by dustingetz** [comment]
Assert false to reproduce

**Comment by khardenstine** [comment]
I don't think styles aren't being passed through in the user-portal on error cases:
https://github.com/hyperfiddle/hyperfiddle/blob/5d0d521f67b5213abe084f0815c3a9d5843ff1f3/src/hyperfiddle/ui.cljs#L182

**Comment by dustingetz** [comment]
Okay, there might be a confounding issue also - the pink box might be a separate bug than the alt-click. Today I experienced alt clicks go to the wrong place (parent) when alt-click on domain frame in data tab. And then later it worked. So a stale key maybe.

**Comment by dustingetz** [comment]
![image](https://user-images.githubusercontent.com/124158/45256588-75d92000-b366-11e8-849c-882cd792cd02.png)
