### ISSUE TITLE
Stale/cached view in popover error stage

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#542]
http://www.hyperfiddle.site/:docs/:cookbook!form-value-renderer

![screenflow](https://user-images.githubusercontent.com/124158/45256495-fb5bd080-b364-11e8-9856-6917cdaea10f.gif)

**Comment by dustingetz** [comment]
I just saw this generalize to the actual stage, it happens after transact?

**Comment by khardenstine** [comment]
Fixed 46d7f597489eae75cef8849a42b3f7b5bd57a661
