### ISSUE TITLE
Another way to break hflive query editor

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#565]
- [x] invalid EDN - unbalanced paren
- [x] invalid EDN - unbalanced map keys e.g. `{:reg/shirt-size}` (which happens as you type)

**Comment by dustingetz** [comment]
![screenflow](https://user-images.githubusercontent.com/124158/45328431-f005d200-b529-11e8-9925-64b9393a45cc.gif)

**Comment by khardenstine** [comment]
Breaking changeset: https://github.com/hyperfiddle/hyperfiddle/commit/918394777343ad6156a157dc21b4b17ec77b3209
We used to always generate routes in ui-from-link and only do the route validation for popovers and anchors. Now it happens always for iframes as well and the monad returns a left.
Key comment indicating the indifference for iframes to route validation. 
https://github.com/hyperfiddle/hyperfiddle/commit/918394777343ad6156a157dc21b4b17ec77b3209#diff-0055e8215729ed27280d2babc93814faR251

**Comment by khardenstine** [comment]
This is probably inflaming #540, but there are still unique problems to that ticket.

**Comment by dustingetz** [comment]
@khardenstine I got this far now I'm stuck

![screenflow](https://user-images.githubusercontent.com/124158/45517431-1b7ffb00-b77c-11e8-906c-1890bdda9ef6.gif)

**Comment by dustingetz** [comment]
Pre-breaking links:
* [base](https://github.com/hyperfiddle/hyperfiddle/blob/2e359364753e49e298afdbb08863e0a0fe58ad65/src/hypercrud/browser/base.cljc#L141)
* [routing](https://github.com/hyperfiddle/hyperfiddle/blob/2e359364753e49e298afdbb08863e0a0fe58ad65/src/hypercrud/browser/routing.cljc#L77)

**Comment by dustingetz** [comment]
I don't fully understand the implications of this changeset but its working okay.

**Comment by dustingetz** [comment]
It was just a bad assert
