### ISSUE TITLE
pprint doesn't work inside Track

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#574]
A reagent bug but do we have the capability to PR this now?

![image](https://user-images.githubusercontent.com/124158/45489706-00d56400-b733-11e8-99ec-04afcaf7b649.png)

**Comment by khardenstine** [comment]
I wouldn't call this a reagent bug.  Take ThinEntity.  Ideally we want to embed the following lines in the ThinEntity ns and any consumer (other libraries too!) would automatically get correct pprint:
https://github.com/hyperfiddle/hyperfiddle/blob/master/src/hyperfiddle/pprint.cljc#L10-L20

If that worked in CLJS, we would duplicate that for Track and make a PR.  But Clojurescript has no easy way (that I know of) to extend the default pprint dispatcher.  Here it is all locked up:
https://github.com/clojure/clojurescript/blob/master/src/main/cljs/cljs/pprint.cljs#L2904-L2906 

The best solution I found was manually binding our own dispatch function for pprint everywhere: https://github.com/hyperfiddle/hyperfiddle/blob/master/src/contrib/pprint.cljc#L15-L17
