### ISSUE TITLE
ctx schemas includes zzz attrs (pprint spam)

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#575]

**Comment by khardenstine** [comment]
I dont understand what this issue is.

Schemas should include `zzz*`; they are still usable attributes.  The concept only exists as an ugly hack for our fiddle model because it changed so much over time.

If you are sick of seeing the schemas in the ctx, this is just a duplicate of #376 then.

**Comment by dustingetz** [comment]
ZZZ should not be considered usable attributes, they are scheduled for deletion and essentially do not exist. I am not altering the schema editors behavior, but I am removing them from the ctx, because i want to be able to look at it and not see noise.

**Comment by khardenstine** [comment]
I dont agree "deleting" attributes is something we should double down on; especially not via a thrown together hack.  Furthermore these "zzz.*" attributes are local to fiddle repos.  Users should have full ability to define their own attribute idents, including prefixing with "zzz".

**Comment by dustingetz** [comment]
Ok, it's a one-liner to toggle back in the future
