### ISSUE TITLE
Prod database editor: Assert failed: % hyperfiddle.domain.dbname__GT_hfdb 

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#595]
Starting from domain editor, click on a database
* http://seattle.hyperfiddle.net/:hyperfiddle.ide!domain/~entity('$domains',(:domain!ident,'seattle'))

HFHF works, surprisingly: http://hyperfiddle.hyperfiddle.net/:hyperfiddle.ide!domain/~entity('$domains',(:domain!ident,'hyperfiddle'))

This might be my bug

**Comment by khardenstine** [comment]
This is on me.  I forgot to remove known bad asserts.

**Comment by dustingetz** [comment]
The assert compounded the issue, but with the assert removed the error becomes "fiddle not found" which is correct, because this is an invalid uri from seattle:
* http://seattle.hyperfiddle.site/:databases!edit/~entity('$domains',17592186046096)

**Comment by dustingetz** [comment]
databases is probably hfnet.databases, and certain hfnet fiddles probably do belong in userland domains in cloud only

**Comment by dustingetz** [comment]
Very interestingly, :databases/option-list is available in seattle *via hf/iframe from :hyperfiddle.ide/domain* but not addressable standalone

**Comment by khardenstine** [comment]
uris are gone just about everywhere.  No longer applicable
