### ISSUE TITLE
Reverse lookups crash data mode

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#597]
http://hyperfiddle.hyperfiddle.net/:databases!edit/~entity('$domains',17592186046097)

`this.mseq.cljs$core$ISeq$_first$arity$1(...).cljs$core$IMapEntry$_key$arity$1 is not a function
`

![image](https://user-images.githubusercontent.com/7741805/45628388-f46a4780-ba61-11e8-8206-63afa3d354df.png)

Only happens with the asterisk in the :domain/_fiddle-database reverse lookup:
```clj
[:db/id
 :database/uri
 :hyperfiddle/owners
 {:database/write-security [:db/ident]}
 :database.custom-security/client
 :database.custom-security/server
 {:domain.database/_record [:domain.database/name {:domain/_databases [:domain/ident]}]}
 {:domain/_fiddle-database [* :domain/ident]}
 :db/doc]
```

**Comment by dustingetz** [comment]
#854
