### ISSUE TITLE
Altering sec/attempt-to-transact? causes broken states for auto-transact

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#599]

**Comment by dustingetz** [comment]
Impacts toggling whitelist, and can put you into limbo stuck state wrt auto-transact

**Comment by khardenstine** [comment]
https://github.com/hyperfiddle/hyperfiddle.net/commit/8f9d010a1ad28e958e1d9e038515e62125cd92c9
