### ISSUE TITLE
ui/form crashes on scalar queries

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#60]
http://dustingetz.hyperfiddle.net/ezpyZXF1ZXN0LXBhcmFtcyB7OmVudGl0eSAjZW50aXR5WyIkIiAxNzU5MjE4NjA0NTQ3OV19LCA6Y29kZS1kYXRhYmFzZSAiaHlwZXJibG9nIiwgOmxpbmstaWQgMTc1OTIxODYwNDU0NDB9

User mode renders, then click on "data" to see error. `field` is defined, `ctx :attribute` is not
```
Uncaught Error: Doesn't support name: 
    at Object.cljs.core.name (core.cljs:9133)
    at hypercrud.ui.label.label (label.cljs:39)
    at form.cljs:42
    at Function.hypercrud.ui.form.form_cell.cljs$core$IFn$_invoke$arity$variadic (form.cljs:42)
    at Object.hypercrud.ui.form.form_cell [as reagentRender] (form.cljs:35)
```

**Comment by khardenstine** [comment]
Localized to the inline bio link:  http://dustingetz.hyperfiddle.net/ezpjb2RlLWRhdGFiYXNlICJoeXBlcmJsb2ciLCA6bGluay1pZCAxNzU5MjE4NjA0NTQ0N30,

This (perfectly legal) scalar query is causing the issue:
```edn
[:find (pull ?e [:db/id :user/bio-short :user/picture :user/title :user/bio :user/name]) .
 :in $
 :where [?e :db/ident :hyperblog/bio]]
```

Related #44

**Comment by dustingetz** [comment]
This is actually due to `:user/bio-short` not being installed (interestingly there *is* an attr renderer for it)
