### ISSUE TITLE
shadow entities are hashmaps, not Entity (Nothing is broken)

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#61]
It is super duck typey though and is surely a problem in the future

**Comment by khardenstine** [comment]
This is only important on the boundary of injecting information into the topnav.
Everywhere else (base/ordered-fes) it is probably preferred and intentional to be using hashmaps and not entities

**Comment by khardenstine** [comment]
Other conversation: https://github.com/hyperfiddle/hyperfiddle/issues/227#issuecomment-385550675
