### ISSUE TITLE
popover widgets dont stage anything when auto-tx is on

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#614]
![image](https://user-images.githubusercontent.com/124158/45726749-95eeb780-bb8e-11e8-9791-68b5a0e1737c.png)

![image](https://user-images.githubusercontent.com/124158/45726756-9b4c0200-bb8e-11e8-8013-d08b6bca3957.png)

**Comment by khardenstine** [comment]
This is everywhere, not just tank.

**Comment by dustingetz** [comment]
multi-color-tx doens't have the modal-form

![image](https://user-images.githubusercontent.com/124158/45754586-0a0a7900-bbea-11e8-8e0c-363559b1dd77.png)

**Comment by dustingetz** [comment]
#556

**Comment by dustingetz** [comment]
Here is the bug: https://github.com/hyperfiddle/hyperfiddle/commit/974ad8e4433eea7161cfa75b2e063cabbe40cd94#diff-aec4a622cbac0d762b94928badc90034R98

**Comment by dustingetz** [comment]
No i'm wrong, this is a popovercmp not effect cmp, because there is a form AND txfn
