### ISSUE TITLE
UX: Default home-route should be shortcuts

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#615]
"Fiddle not found" is pretty rough on onboarding

**Comment by dustingetz** [comment]
Index fiddle runs in content domain (white background, like schema).

Wrong: http://seattle.hyperfiddle.net/:hyperfiddle.ide!entry-point-fiddles/
Like this: http://seattle.hyperfiddle.net/_/:hyperfiddle.schema!$/

**Comment by dustingetz** [comment]
Thoughts:
* schema is injected in hyperfiddle.ide.system-fiddle, because it is an IDE concern, but it is content domain
* In fact, everything in h.ide.system-fiddle is content-domain IDE-concerns
* None of the h.ide.system-fiddles have the magic-ide-ns, which is what crosses to ide-domain
* so :hyperfiddle.ide/entry-point-fiddles needs changes: 
  1) [ ] be available in content-domain (today that means a system fiddle in git)
  2) [ ] not have the magic-ide-ns

**Comment by dustingetz** [comment]
But, one way or the other, it is definitely an IDE-domain fiddle being injected into the content-domain. So do we need two namespaces?

Cases are:
- :hyperfiddle.ide/domain – runs in ide viewport
- :hyperfiddle.schema/$ –
- :hyperfiddle.ide/topnav – runs in ide viewport
- fiddle-src is just a renderer

all hyperfiddle.ide fiddles are available in the IDE viewport

Action:
- [ ] Add a second magic namespace which injects ide-domain fiddles into the content-domain.

It can eventually be used for schema, once fiddle-params are a thing.

How does entry-point-fiddles currently know what database to look in?

**Comment by dustingetz** [comment]
Entry-point-fiddles runs in a topnav ctx, which has the fiddle-database bound to $

**Comment by dustingetz** [comment]
This means entry-point-fiddles should get the blue background, it's source.

**Comment by dustingetz** [comment]
The user will want to customize their index (as it represents service discovery). They can only do that if they configure $src on the content-domain. Should this be mandatory?

**Comment by dustingetz** [comment]
:index and service discovery is not really an IDE concern. So is this an IDE fiddle? The default should be injected from some other domain, but maybe not IDE? Can this be bundled with the foundation?

Maybe if the IDE were general, it is not named IDE anymore, but rather "browser". Foundation today does not have any core hypercrud.browser imports, just tangential routing setup that could be jiggled to somewhere else, its not even actual routing.

- [ ] IDE can set up its own ctx, instead of foundation doing it right above

**Comment by dustingetz** [comment]
I think
- IDE becomes the generalized cross-domain abstraction at browser level. Browsers talk to domains.
- foundation becomes basic setup unrelated to domains - stage, errors, page vs leaf, local-basis

**Comment by dustingetz** [comment]
source-domain, source-domain-insecure all flattens into the "browser talks to domains" layer. the source-domain is no longer special, its just another domain.

**Comment by dustingetz** [comment]
@khardenstine  please review these two commits (ignore the stream of consciousness in the comments)

**Comment by dustingetz** [comment]
This comes with a migration in hfhf to shadow in the view:

```
(let [ctx (update ctx :hypercrud.browser/data (partial contrib.reactive/fmap hyperfiddle.foundation/shadow-domain))]
  [:div props
   [:h3 "Environment: " [hyperfiddle.ui/value [:domain/ident] ctx #(str %)]]
   [hyperfiddle.ui/field [:domain/ident] ctx hyperfiddle.ide.fiddles.domain/domain-ident-renderer]
   [hyperfiddle.ui/field [:hyperfiddle/owners] ctx hyperfiddle.ui/hyper-control]
   [hyperfiddle.ui/field [:domain/databases] ctx 
    (fn [val ctx props]
      [hyperfiddle.ui/table 
       (fn [ctx]
         [[hyperfiddle.ui/field [:db/id] ctx (fn [val ctx props] 
                                               (hyperfiddle.ui/link :hf/remove :remove-database ctx "remove"))]
          [hyperfiddle.ui/field [:domain.database/name] ctx hyperfiddle.ui/hyper-control]
          [hyperfiddle.ui/field [:domain.database/record :database/uri] ctx hyperfiddle.ui/hyper-control]])
       ctx])]
   [hyperfiddle.ui/field [:domain/fiddle-database] ctx hyperfiddle.ui/hyper-control {:options :database-options
                                                                                     :option-label (comp :database/uri first)}]
   [hyperfiddle.ui/field [:domain/aliases] ctx hyperfiddle.ui/hyper-control]
   [hyperfiddle.ui/field [:domain/disable-javascript] ctx hyperfiddle.ui/hyper-control]
   [hyperfiddle.ui/field [:domain/home-route] ctx hyperfiddle.ui/hyper-control]
   [hyperfiddle.ui/field [:domain/environment] ctx hyperfiddle.ui/hyper-control]
   [:p "Source code concerns. todo migrate into fiddle-database"]
   [hyperfiddle.ui/field [:domain/code] ctx hyperfiddle.ui/hyper-control]
   [hyperfiddle.ui/field [:domain/css] ctx hyperfiddle.ui/hyper-control]
   [:p "Attribute renderers. todo migrate into fiddle-database"]
   [hyperfiddle.ui/browse :hf/iframe :attribute-renderers ctx]]
  ) 
```

**Comment by dustingetz** [comment]
Broken

**Comment by khardenstine** [comment]
Fixed https://github.com/hyperfiddle/hyperfiddle/commit/3fd21996f97cd608f5e55c660751f4c067a77dc4
