### ISSUE TITLE
Insta: broken interactions on domain panel only

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#619]
![screenflow](https://user-images.githubusercontent.com/124158/45766402-78106980-bc05-11e8-8613-9d2916db54bb.gif)

**Comment by dustingetz** [comment]
It is also very jarring on this panel, even if it doesn't crash (e.g. with auto tx off) the local state vs server response is wrong and the server clobbers me as i type

**Comment by dustingetz** [comment]
The rest of the attrs on this env panel also have same bug

**Comment by dustingetz** [comment]
Auto-transact is on

**Comment by dustingetz** [comment]
Auto-transact is actually off when this is happening. Auto-transact on is a workaround and fixes it

**Comment by khardenstine** [comment]
Fixed https://github.com/hyperfiddle/hyperfiddle/commit/5232ad069db499d05a09fb124b5360f9fc70efd9
