### ISSUE TITLE
While developing, queries get stuck as loading often

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#635]
This happens about 50% of the time, need to refresh to fix it. Something to do with the debounce, i think.

![image](https://user-images.githubusercontent.com/124158/45902992-3e329500-bdb6-11e8-87d2-afddf3fcd86a.png)

**Comment by dustingetz** [comment]
Refreshes have left it super-fucked, the tabs are out of sync across multiple refreshes:

![image](https://user-images.githubusercontent.com/124158/45903051-691ce900-bdb6-11e8-8d24-9dc50554fa15.png)

**Comment by dustingetz** [comment]
They keep trading localStorage! Refresh one, and they swap localStorage, lol

**Comment by dustingetz** [comment]
![image](https://user-images.githubusercontent.com/124158/45903089-8baf0200-bdb6-11e8-8984-478f594cfcfe.png)

**Comment by dustingetz** [comment]
Visible in the hero video here (I refresh to fix it)

![image](https://user-images.githubusercontent.com/124158/45903470-d54c1c80-bdb7-11e8-97dc-5f5b7aad2698.png)

**Comment by dustingetz** [comment]
Stuck at "loading..." means the insta transitioned through an invalid query. We never show the datomic error in this case, it just gets stuck at loading and never recovers without a refresh.

**Comment by dustingetz** [comment]
Missing schema errors are related to loading. I stage schema attr, then use it in the pull, then query gets stuck loading and doesn't recover if you toggle state, then refresh and i get these schema errors. Transacting repairs it all.

![image](https://user-images.githubusercontent.com/124158/48986422-c436c900-f0e2-11e8-8628-67f6e496b4e9.png)

**Comment by dustingetz** [comment]
This is a race condition related to speed you type

1. from tank, refresh, new fiddle
2. fiddle/type query
3. edit default query :where `[?e :dustingetz.post/title]`

If you didn't reproduce it, whack your stage and try again and type a little different.

Note the loading query is different than the query i tyoed

![image](https://user-images.githubusercontent.com/124158/49751150-b18fc880-fc7a-11e8-9378-5e17188ba0da.png)

I was able to reproduce it with cmd-z undo/redo - 

![image](https://user-images.githubusercontent.com/124158/49751276-fae01800-fc7a-11e8-94b4-ee2fb7ac1aa3.png)

**Comment by dustingetz** [comment]
If you just mash undo/redo at random times, you will eventually reproduce it.

**Comment by dustingetz** [comment]
Once you reproduce it once, it becomes reliable, i think the local state of the codemirror is corrupted

**Comment by dustingetz** [comment]
Once reliable, `INFO [actions:40] - Ignoring response for -1860351418` starts spamming the log reliably

**Comment by khardenstine** [comment]
The current plan is this could be fixed by removing reactions on the hc.b/data (assuming we can solve context/refocusing), which would also simplify the interface for users.
However the planned changes for a user land refresh button/cmd+enter (#717 and #712) should make this a rare or non occurrence.

**Comment by dustingetz** [comment]
Hoplon is a bust:

![image](https://user-images.githubusercontent.com/124158/49762022-87e49a80-fc96-11e8-95d3-2756f7157493.png)

**Comment by dustingetz** [comment]
It is not clear to me that the monster mlet in base.cljc is correct, i think it could be responsible for the bugs we see. (Because even in the presence of Reagent nondeterminism, by my understanding it should get the right answer in the end)

**Comment by dustingetz** [comment]
Flattening the reactions in ui-from-link by @link-ref at the top only, will have deep impact on this bug, i think. There is a deep reaction chain here that can simply be headed off, and this bug may disappear
