### ISSUE TITLE
Intermittent localStorage glitches on transact with multiple tabs – stage comes back

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#641]
As described in #635, but splitting out here.

Possibly same bug as #540 #374 #635

**Comment by dustingetz** [comment]
As described in #635, but splitting out here.

**Comment by khardenstine** [comment]
Almost assuredly a race condition, something like:
- Tab 1 hydrates-route
- Tab 2 hydrates-route
- Tab 2 stages tx2
- Tab 1 rehydrates with tx2
- Tab 2 transacts tx2 and clears stage area
- Tab 2 issues request for global-basis
- Tab 1 detects cleared stage area, requests hydrate-route with tx1
- Tab 2 global-basis returns, propagates through local-storage
- Tab 1 detects new global-basis, restarts bootstrapping
- Tab 1 before bootstrapping finishes, hydrate-route completes, global-basis gets updated again with the old value
- Tab 1 propagates stale basis through local-storage

**Comment by dustingetz** [comment]
I saw it more today maybe once every 30 mins while editing the www. Sometimes an old stage would show up in the staging area as well (turning it yellow, and then on refresh would be white again). I never had to clear local storage, only refresh.
