### ISSUE TITLE
dustin@gmail can edit fiddles on www but not clear stage

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#650]
This stage is read-only, but the fiddle/markdown is not

![image](https://user-images.githubusercontent.com/124158/45953661-cbedca80-bfd8-11e8-8d28-08f81c468624.png)

**Comment by dustingetz** [comment]
duplicate #599 ?

**Comment by khardenstine** [comment]
8f9d010a1ad28e958e1d9e038515e62125cd92c9
