### ISSUE TITLE
Demo polish

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#664]
- [ ] I don't know how, but it needs to be interactive

http://tank.hyperfiddle.net/:dustingetz!quick-demo/

**Comment by khardenstine** [comment]
Why not put it in demo?
This ticket belongs in hf.net

**Comment by dustingetz** [comment]
Good idea: http://demo.hyperfiddle.net/:quick-demo/

@khardenstine  Can you set security on demo to allow anonymous editing?

**Comment by khardenstine** [comment]
Done
