### ISSUE TITLE
Fate of hydrate-loop and interim browser-request data structure

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#670]
Since it is now bypassed it in the JVM, the loop code could be removed completely.
Also the collection of requests in browser-request is no longer necessary.

However that adds the hard requirement of always running hydrate-route on the JVM.

Should revisit after ion

Related hyperfiddle/hyperfiddle.net#177

**Comment by dustingetz** [comment]
Kill it

**Comment by khardenstine** [comment]
urania & muse
- https://github.com/funcool/urania
- https://github.com/kachayev/muse
- https://speakerdeck.com/kachayev/efficient-concurrent-and-concise-data-access-in-clojure

haxl
- https://simonmar.github.io/bib/papers/haxl-icfp14.pdf
- https://github.com/facebook/Haxl/

stitch - https://www.youtube.com/watch?v=VVpmMfT8aYw

**Comment by khardenstine** [comment]
The loop is gone, browser-request still needs cleaned up

**Comment by khardenstine** [comment]
Cleaned up in https://github.com/hyperfiddle/hyperfiddle/commit/87ee56266656e289cbd710af076998da94dfb815
