### ISSUE TITLE
"duplicate key" in a simple query

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#678]
http://tank.hyperfiddle.net/:mbrainz/ toggle to view. maybe i am tired

**Comment by khardenstine** [comment]
This is a hash collision on integers when computing [react keys](https://github.com/hyperfiddle/hyperfiddle/blob/83d9acdc3aa98fb274a4f27f529c307940a863bf/src/hyperfiddle/data.cljc#L21)
```js
x = [/* insert db/ids from api view*/]
x.length
4601
[...new Set(x.map(cljs.core.hash))].length
4561
```

Related #298

**Comment by dustingetz** [comment]
Couldn't easily reproduce

**Comment by khardenstine** [comment]
Duplicate of #298
