### ISSUE TITLE
":db.error/not-an-entity" during tutorial

### ISSUE THREAD

**Issue by aeberts** [hyperfiddle/hyperfiddle#688]
I'm working through the tutorial and got to 0:13 seconds where you replace `[?e :db/ident :db/add] ` with `[?e :neighbourhood/name]` and ran into the following error:

```
:db.error/not-an-entity
Unable to resolve entity: :neighbourhood/name
Hint: If this is a schema attribute, does it exist?
This can happen if you both create a schema entity and use it in the
same transaction. Transact the schema before using it. Also try auto-transact.
```

I'm assuming that it's because the schema is set to: `$$beta$clojurians$mbrainz` but I can't see how to change the schema to `$` like it is in the video.  Please see screenshot below for details:

<img width="672" alt="screen shot 2018-10-08 at 9 18 21 pm" src="https://user-images.githubusercontent.com/571576/46646843-6f92bb00-cb41-11e8-9ec4-2ba48e523ca0.png">

**Comment by dustingetz** [comment]
Hi Alexander, no u in neighborhood. There are actually four databases available, $ $beta $clojurians $mbrainz, with a link to each schema, and a style issue has obfuscated that. Datomic defaults to the $ database when not explicitly named. Thanks for the report, I will leave this issue open until the UX and error is clarified.

**Comment by aeberts** [comment]
Ha! That's what I get for being Canadian, Lol ;-) 

Thanks for the clarification - Hyperfiddle is very interesting. Congratulations on creating something that is quite unique.

**Comment by dustingetz** [comment]
Improved css for schema links in hfhf env css

**Comment by dustingetz** [comment]
I'm guessing that is probably enough to prevent this confusion, so marking this resolved. The error message needs better typesetting, the message itself is probably okay. We'll clean up the error styles in one swoop later.

**Comment by dustingetz** [comment]
Oops, hfhf editor css does not get loaded onto content domain pages right now.

**Comment by dustingetz** [comment]
https://github.com/hyperfiddle/hyperfiddle.net/commit/85572d7df1f3f0256b938bb3622cb599300bcc4e
