### ISSUE TITLE
Pushy replaceState flag on anchor tag

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#693]
Useful in topnav

**Comment by dustingetz** [comment]
@khardenstine please review, this is experimental

**Comment by khardenstine** [comment]
Pushy changes seem ok; the topnav changes confuse me.  How does a user get back to the view?  They cant use the browser history (replace state) and the view radios are disabled.

**Comment by dustingetz** [comment]
@khardenstine thanks, review again please

**Comment by khardenstine** [comment]
LGTM
