### ISSUE TITLE
Any UI components that can be reactive, should be fully reactive

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#7]
- [x] results
- [x] relations/relation
- [x] cell-data
- [x] values
- [x] ordered-fes
- [x] anchors
- [x] schemas
- [x] :fiddle'
- [x] :fiddle
- [x] :request
- [x] Entity ILookup should return IReactive

No reason to be made reactive:
- [x] :route (fiddle-id or params change? dont change much, not worth the interface overhaul #on its own see #125)
- [x] :uri
- [x] :hypercrud.browser/domain (see hyperfiddle/hyperfiddle.net#209)

Should fix:
- [x] #38 

Assertions ~~, when data changes in the following ways, should the UI rerender?~~:
(can we develop tests for these? not without hyperfiddle/hyperfiddle.net#208)

Action | Rerender table cell | notes
-- | -- | --
add/remove result rows | no | _ 
edit another result's cell data | no | _
reordering rows (sorting) | no | _

**Comment by dustingetz** [comment]
Reactive formulas: `(juxt :cell-data (comp :reg/gender :cell-data))`

**Comment by khardenstine** [comment]
Data correction for latest commits:
https://gist.github.com/khardenstine/746ea237baae1de2221c23e888db4d47

**Comment by khardenstine** [comment]
Migrations for :schemas https://gist.github.com/khardenstine/f9f8765598cba2494ba2772b83eb8995

**Comment by dustingetz** [comment]
🎉
