### ISSUE TITLE
:hyperfiddle/owners not in demo, and ensure-schema! didnt repair it

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#707]

**Comment by dustingetz** [comment]
I think because it's not here: http://hyperfiddle.hyperfiddle.net/_/:hyperfiddle.schema!$/

**Comment by dustingetz** [comment]
A related issue is that export-fiddles should omit :hyperfiddle/owners

**Comment by khardenstine** [comment]
hyperfiddle/owners isn't root schema.  It is entirely opt in
