### ISSUE TITLE
queries should support superset of edn

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#721]
Works fine when L11 is not commented out.
![image](https://user-images.githubusercontent.com/124158/47576863-83953580-d913-11e8-819d-0d9c2f145761.png)

**Comment by khardenstine** [comment]
https://sentry.io/hyperfiddle/cloud-browser/issues/744005910

**Comment by khardenstine** [comment]
`d/q` clearly accepts a superset of edn, as that query in string format is allowed and read correctly.
However we parse `:fiddle/query` everywhere as edn, of which the above comment is not legal edn (see https://github.com/edn-format/edn#discard "reader should not call user-supplied tag handlers during the processing of the element to be discarded")
