### ISSUE TITLE
console links regressions

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#730]
Toggling to data mode - Is it the state closure? (It shouldn't break though)
![image](https://user-images.githubusercontent.com/124158/48303147-a2c7c180-e4d4-11e8-9274-1a0c5d02d31b.png)

**Comment by dustingetz** [comment]
http://tank.hyperfiddle.net/:dustingetz!youtube-embed/

**Comment by khardenstine** [comment]
A couple of NPEs in this function:
https://github.com/hyperfiddle/hyperfiddle/blob/29fbdaef394e12ab4f7ccf181f6a3f30c6992d5c/src/hyperfiddle/ide/console_links.cljc#L113-L129

unwrap nil doesn't type check for :blank fiddles.  Then after that is fixed, it appears the rest of the function cannot handle a nil qfind.

**Comment by dustingetz** [comment]
There are more
- [ ] http://hyperfiddle.hyperfiddle.site/:domains!edit/'alexandrkozyrev'
