### ISSUE TITLE
Infer dbname as $ if in blank context

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#732]

**Comment by dustingetz** [comment]
Is this legit? 
![image](https://user-images.githubusercontent.com/124158/48304512-774ed200-e4e8-11e8-8c05-a858a6f20b63.png)

**Comment by khardenstine** [comment]
Why would we want this behavior?

**Comment by dustingetz** [comment]
The slack parser has a top-level button that is not in a result context that stages a transaction, and it seemed like a reasonable thing to implement, because it's almost always gonna be this

**Comment by dustingetz** [comment]
@khardenstine This might be a mistake, leaving issue open. Here is what drove the need:

![image](https://user-images.githubusercontent.com/124158/48318441-2a91f680-e5cf-11e8-97c2-a55390f8e2a3.png)


But I did it wrong. That txfn on L10 should be a proper hypermedia control if it wants security - in prod, is there ever a reason to just allow arbitrary transactions to go up? Seems like a recipe for abuse. Should always go through txfn.

**Comment by khardenstine** [comment]
A txfn would have been sufficient.  If for some reason staging arbitrary tx becomes a frequent need, there are easy improvements we can make to `actions/with-groups` and `util/with-tx!` to make it painless to choose the db (`util/with-tx!` is already just a helper/wrapper around `with-groups`, so it can be blown up).

I would like to see this changeset reverted.

**Comment by dustingetz** [comment]
@khardenstine I want to unrevert this and instruct Alexandr to do this. Txfn is not ready yet. I will migrate him to txfn when the time is right.

**Comment by dustingetz** [comment]
This would work out-of-the-box without editing the formula if $ was inferred by default

![image](https://user-images.githubusercontent.com/124158/48722602-668e1280-ebf2-11e8-9807-a69c055819eb.png)
