### ISSUE TITLE
Clojurians demo is broken in tank

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#733]
- [ ] http://tank.hyperfiddle.net/:clojurians/ - view and data
- [ ] http://tank.hyperfiddle.net/ - toggle to data

**Comment by dustingetz** [comment]
Both line 11 and 18 cause error

![image](https://user-images.githubusercontent.com/124158/48308232-6ffde780-e52d-11e8-9dff-06b4478000b9.png)

**Comment by dustingetz** [comment]
Debugging line 3 only: field source-symbol is null thus can't lookup schema

**Comment by khardenstine** [comment]
Already fixed in master
