### ISSUE TITLE
fiddle/uuid for anon fiddles

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#734]
This was for the slack parser, i wanted the ability to generate hydrateable fiddle gists without prompting the user for a fiddle/ident. I ended up moving in a different direction for that, but I will need this soon enough, so will go ahead and put this in.

**Comment by dustingetz** [comment]
Tank's definition of what constitutes a fiddle is `:where [?e :fiddle/ident]`. It makes sense to me to expand that definition to include :fiddle/uuid

**Comment by khardenstine** [comment]
That sounds like a conflation of entity identity with knowing if an entity is a fiddle.  A `:hyperfiddle/type` attribute could solve this (in the spirit of `:db/valueType`)

**Comment by dustingetz** [comment]
Related
- fiddle/ident is actually cardinality many (for keeping old URLs working)
- fiddle/ident-primary (or canonical)

**Comment by dustingetz** [comment]
```
[[:db/add "-2017569654" :db/ident :fiddle/uuid]
 [:db/add "-2017569654" :db/valueType :db.type/uuid]
 [:db/add "-2017569654" :db/cardinality :db.cardinality/one]
 [:db/add "-2017569654" :db/unique :db.unique/identity]
 [:db/add "-2017569654" :db/doc "For creating new fiddles without needing a human to fill in an ident"]]
```

**Comment by dustingetz** [comment]
user=> (tools.hfnet/ensure-schema-and-docstrings!)
IllegalArgumentExceptionInfo :db.error/wrong-type-for-attribute Value hyperfiddle.security/root is not a valid :uuid for attribute :hyperfiddle/owners  datomic.error/arg (error.clj:57)

**Comment by dustingetz** [comment]
Manually fixing tank, and then ensure-schema, worked
