### ISSUE TITLE
no schema for attr: :zzz.fiddle/entrypoint?

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#735]
![image](https://user-images.githubusercontent.com/124158/48360220-be65d000-e66c-11e8-8bf3-34042f6fdfaa.png)

But that's not true:

![image](https://user-images.githubusercontent.com/124158/48360232-c58cde00-e66c-11e8-8408-4c660dfa920a.png)
![image](https://user-images.githubusercontent.com/124158/48360287-e7866080-e66c-11e8-85f1-c0cc8367c00a.png)

**Comment by khardenstine** [comment]
From #575

Fixed already in master via 715d21fc84a59e620ecc89c6194afc97c4476804
