### ISSUE TITLE
Abstract over Schema vs Indexed-schema dichotemy

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#737]
(deftype Schema [schema-seq] ILookup (memoized (group-by-unique :db/ident schema-seq)) or something

**Comment by khardenstine** [comment]
What is the value of this proposal?  I don't believe anyone needs it unindexed.

**Comment by dustingetz** [comment]
Constructing mocks, and remembering, and also it can canonicalize idents e.g. smart-lookup-ref-no-tempids
