### ISSUE TITLE
Internal service error on .com

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#739]
- [ ] http://alexandrkozyrev.hyperfiddle.com/:two-panes/ .  (.net works)

Works
* http://dustingetzcom.hyperfiddle.com/ and other pages here

![image](https://user-images.githubusercontent.com/124158/48440988-60161b80-e758-11e8-8177-c2e3cff81f34.png)

**Comment by khardenstine** [comment]
Recaptured in:
hyperfiddle/hyperfiddle.net#358
hyperfiddle/hyperfiddle.net#359
