### ISSUE TITLE
New domain onboarding - system is adding sandbox and hyperblog 

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#74]
This stage hydrates out with a hyperblog and sandbox code databases added, wth?
```
{nil {#uri "datomic:free://datomic:4334/domains"
        [{:user/sub "google-oauth2|116635422485042503270", :domain/ident "yc",
          :domain/code-databases
            #{{:dbhole/name "yc", :dbhole/uri #uri "datomic:free://datomic:4334/yc",
               :repository/environment
                 "{\"$\" #uri \"datomic:free://datomic:4334/yc-app\"}"}}}]}}
```
![image](https://user-images.githubusercontent.com/124158/36057433-1a2d7254-0ddc-11e8-8fa9-de44ff9316f7.png)

**Comment by dustingetz** [comment]
This has me astounded. I find no source code that could have done this. Yet the entities clearly exist, both in the domain panel and in the domain masterlist, and the entities are real because i retracted them later.

**Comment by khardenstine** [comment]
You are upserting onto your user domain record by :user/sub (db.unique/identity).  You want to add your oauth sub to :domain/members for non-user domains and leave :user/sub blank.

You renamed the `dustingetz` domain to `yc`.
