### ISSUE TITLE
How to get started as a dev

### ISSUE THREAD

**Issue by kashert** [hyperfiddle/hyperfiddle#740]
Can't find any documentation or pointers as to how you'd start anything resembling what's on the official website. There's no obvious entry point anywhere?

**Comment by dustingetz** [comment]
Unfortunately you can't yet, until we decouple it from our cloud infrastructure. ETA on that is Q1.

**Comment by dustingetz** [comment]
This is resolved by new quickstart and hyperfiddle-app repo (which remain private for now but can be published at any point)
