### ISSUE TITLE
Cannot copy text from disabled code mirrors

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#742]
No option in context menu to copy.  Copy shortcut doesnt work either
![image](https://user-images.githubusercontent.com/7741805/48566041-dab17900-e8c7-11e8-91ca-8e0d6535980b.png)

**Comment by dustingetz** [comment]
https://github.com/codemirror/CodeMirror/issues/1099
> This is intentional. Nocursor implies no selection. Just use readOnly: true if you want things to be selectable. You can style the cursor to be invisible if you don't want it to show up (use something like .CodeMirror-cursor { display: none !important })
