### ISSUE TITLE
schema editor new attr is busted 

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#75]
![image](https://user-images.githubusercontent.com/124158/36057492-cf36cb8c-0ddc-11e8-9c4a-7fc76681c121.png)

**Comment by dustingetz** [comment]
It still works actually

**Comment by dustingetz** [comment]
This is a data edit to fix (remove the unused param), but the link editor on this page is broken

![image](https://user-images.githubusercontent.com/124158/36064049-4663b60e-0e53-11e8-80dc-f6c1d0ad1ce0.png)

part of the cause here is the schema fiddles are hashmaps and not Entity. The formula returns @(:cell-data ctx) which is the correct formula, but it is a hashmap not an Entity (thus it has no URI thus the param is malformed)

**Comment by dustingetz** [comment]
- [ ] schema-editor merge-in-tx needs to return entity, but this isn't the bug
- [ ] auto-fiddle needs to return nested entities like hydrates, but this didn't fix the problem

**Comment by khardenstine** [comment]
[Links tab being broken](https://github.com/hyperfiddle/hyperfiddle/issues/75#issuecomment-364666289) is because you are viewing a system link

**Comment by khardenstine** [comment]
Related: #32
