### ISSUE TITLE
User static assets s3 organization

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#76]
* Userland fiddles need code artifacts by url (e.g. upload .css files and html them in)
* Hyperblog needs static assets (not just images)
* dustinetz.com is outgrowing imgur, the images need to be organized/tagged etc in a database

I am thinking a user generated content bucket, `s3://hyperfiddle/ugc/:domain/` with public readable, and eventually a fiddle for managing the bucket and coordinating uploads to the bucket (proxied through hyperfiddle-service as a control point for security). Maybe a totally separate bucket for security reasons.

**Comment by khardenstine** [comment]
Related: hyperfiddle/hyperfiddle.net#131
