### ISSUE TITLE
Unchecking a bool should :db/add false, not :db/retract true

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#787]
Because the fact is now known – this distinction matters when people write queries

**Comment by dustingetz** [comment]
http://tank.hyperfiddle.site/:cookbook!markdown-table/

Impossible to make these say false, they toggle to nil

![image](https://user-images.githubusercontent.com/124158/52443752-8bf53300-2af4-11e9-87b1-2df84b135b7e.png)

**Comment by khardenstine** [comment]
As of 035b668, our checkbox bool controls will also now set values to false.  I suspect that was originally undesired, but if not that special logic should be implemented in the specific bool control
