### ISSUE TITLE
user.domain/docs-nav-items is not defined in SSR but is defined in SPA

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#788]
This was introduced by migrating from contrib.merge-user to defn. I migrated the call-site to user.domain/* and the SPA worked. The docs site was now crashing for several hours without me knowing. Repaired it by migrating this fn to cljs-ns. What?? http://www2.hyperfiddle.net/:docs!index/ http://www2.hyperfiddle.net/:hyperfiddle.ide!domain/~entity('$domains',(:domain!ident,'www2'))

**Comment by dustingetz** [comment]
I am seeing this in prod now and I think this is a reaction bug now (which is different diagnosis than above which i cant explain). Data view toggle fixes this now. The fiddle/renderer does not eval what is in the stage until second time through; the first time through does not see the stage.

**Comment by khardenstine** [comment]
This [commit](https://github.com/hyperfiddle/hyperfiddle/commit/cf13779f3d8fe08f973beb25dd3c1dc407500435) fixes the asserts firing.  Otherwise the first 2 comments seem like user error.  After deploy ping me if this isn't closeable and you are still having issues

**Comment by dustingetz** [comment]
Smoking gun
![image](https://user-images.githubusercontent.com/124158/49837186-8e950f80-fd73-11e8-9ac7-14d9f2fa614e.png)

**Comment by dustingetz** [comment]
Karl Hardenstine [6:36 PM] looks like domain/code is deviated between www and www2
