### ISSUE TITLE
content-domain css leaks into ide-domain views

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#789]
Can all of Hyperfiddle CSS be done as inline styles? Would that solve this problem? (From Alexandr)
![image](https://user-images.githubusercontent.com/124158/49410548-3a66ab80-f733-11e8-8f26-b1e00afb0295.png)

**Comment by dustingetz** [comment]
Ultimately this does not help much I think, because too many browser defaults will be changed and you can't encode everything. Each domain will need to be in a html iframe and we will need some mechanism to propagate state down into descendent iframes, and actions back up

**Comment by dustingetz** [comment]
https://github.com/hyperfiddle/hyperfiddle/issues/827

**Comment by khardenstine** [comment]
https://github.com/Wildhoney/ReactShadow#inline-styles
