### ISSUE TITLE
Markdown is bugged

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#807]
This is a brand new fiddle in tank, :fiddle/markdown is "### :dustingetz/naked-codemirror"

![image](https://user-images.githubusercontent.com/124158/49699416-e1699e00-fb9e-11e8-9989-c22af112110b.png)

**Comment by dustingetz** [comment]
![screenflow](https://user-images.githubusercontent.com/124158/49699434-27266680-fb9f-11e8-9a78-a76f9a0ce395.gif)

**Comment by khardenstine** [comment]
Almost assuredly this commit https://github.com/hyperfiddle/hyperfiddle.net/commit/fce9682c9fdea2b6353a45b6eb73f8f1499aa24f
https://github.com/hyperfiddle/hyperfiddle.net/issues/322

**Comment by dustingetz** [comment]
https://github.com/mapbox/remark-react/commit/860d56d3cab8a8174064817c2b685bbf8a430a96#diff-0730bb7c2e8f9ea2438b52e419dd86c9R82
