### ISSUE TITLE
Loading/error at fiddle level should not block inline links that are independent

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#81]
This fiddle has top-level inline links, that we should see despite the failure
![image](https://user-images.githubusercontent.com/124158/36179474-6e3a866e-10ea-11e8-9399-b8e0062b550a.png)

I toggle the fiddle to :blank and we see them
![image](https://user-images.githubusercontent.com/124158/36179480-743d89b2-10ea-11e8-88e6-a1419d6bb09a.png)

**Comment by khardenstine** [comment]
This is somewhat difficult from a user renderer perspective.  We would never be able to unpack the result monad for users, their own code would have to do it for them (a double-deref, one for reactivity, one for the either).
https://github.com/hyperfiddle/hyperfiddle/blob/2c5d86381ae3dcd016f506f11c28fd49f451a4b8/src/hypercrud/browser/base.cljc#L144-L150

**Comment by dustingetz** [comment]
I see, so the userland ui fn needs to use the monad interface basically. That would align with the idea that the userland ui fn is not the happy path, userland should parameterize leaf renderers instead, so we control the larger structure

**Comment by dustingetz** [comment]
Not really an issue anymore
