### ISSUE TITLE
:hypercrud.browser/route should be eav-typed (with metadata instead of ThinEntity) 

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#815]
Related: #779, #826

Original title: Remove #entity from urls except in tempid case

The tempid case can be handled simpler as "$:tempid", i think. Then this type can be deleted, or at least becomes encapsulated? @khardenstine  is this correct?

**Comment by khardenstine** [comment]
I'm not 100% sure this would work, but I do like the idea.  I would want to know (think through and audit) the impact on popovers with reversed tempids in their routes (and then nested popovers too).

**Comment by dustingetz** [comment]
ThinEntity has to stay, because it is used by tempid reversal logic in routing

**Comment by dustingetz** [comment]
#779

**Comment by dustingetz** [comment]
We need #entity tag in the URL; but in our data structures, it can be tagged with metadata instead. That optimizes this userland api:

![image](https://user-images.githubusercontent.com/124158/50044539-f341ba00-0052-11e9-96f2-3b6f11463288.png)

**Comment by dustingetz** [comment]
`~entity('$',(:user!sub,'google-oauth2|116635422485042503270'))`
`^{:db,$},(:user!sub,'google-oauth2|116635422485042503270')

**Comment by dustingetz** [comment]
The root cause here is that, the route decoder, needs to take tempids in the url and turn them into reified & colored dbids that match the hydrated stage, and there can be a stage per database input into the query. So the tempid is tagged with color so we can decide which color to use to reverse it. To infer it we need to parse the datomic datalog :where in order to see which databases the dbid is being interpreted as a ref in the context of.

So this is to fix the pathological query with two dbid inputs of different color AND who were a tempid in the url AND had a tempid collision

**Comment by dustingetz** [comment]
So tempid inversion is only even triggered in routing if the param is a tempid, right here:

![image](https://user-images.githubusercontent.com/124158/50045410-39e9e100-0060-11e9-88f4-58475ee293d3.png)

So, only tempids need to be tagged in the url (though they always need to be tagged, even in the single-database case).

The multi-color case only slightly increases the problem – the tempids need to be tagged as tempid, and also tagged with their color.

**Comment by dustingetz** [comment]
But, by the time the route is parsed and ready for userland, everything is reversed and tempids became dbids if needed. So i think we can drop out the ThinEntity wrapper at this point?

**Comment by dustingetz** [comment]
Even if we concede that we will not have multi colored queries in Cloud (and instead this will be accomplished through cross domains), can the $ drop out? There can still be multiple stages, but all parameters to a fiddle are now known to be the color of that fiddle's query. (Even special dbvals, like filters and asof and history, all have consistent dbids)

Can a fiddle ever take as an argument, a dbid from another domain? I think no! You have to use a UUID here, you can't store foreign dbids in a database, which means they are never joined on, which means foreign dbids are never an input to a single-color query


(Idea for multi-color query case, in the future: Use the ordering of the :in to indicate this. `:in $ ?e $user ?u` can be parsed to invert tempids intelligently in the router)

**Comment by dustingetz** [comment]
```
~e,'tempid'
^:e,"tempid"
```

**Comment by dustingetz** [comment]
The question remains, how do you attach metadata to a java.lang.String, which cannot be subclassed https://groups.google.com/forum/#!topic/clojure/KC5PG0sRTHU https://www.reddit.com/r/Clojure/comments/a6g8bw/clojure_doesnt_allow_metadata_on_primitives_this/

**Comment by dustingetz** [comment]
- [ ] VERIFY FORMULA REACTIONS

**Comment by dustingetz** [comment]
In summary, I did not touch the URLs, though I believe we *can* remove the "$" from the URL. Even so, refs need to be tagged as such to trigger tempid reversal, which is essential complexity.
