### ISSUE TITLE
Bad txfn can corrupt stage, not recoverable by clearing stage

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#816]

**Comment by dustingetz** [comment]
No, staging area is fine:
![image](https://user-images.githubusercontent.com/124158/49876517-8f6c8680-fdf1-11e8-94a1-e26fd88a7169.png)

The uri is busted:
![image](https://user-images.githubusercontent.com/124158/49876665-d35f8b80-fdf1-11e8-9921-5e343c2b8585.png)

**Comment by dustingetz** [comment]
So now we have this, which looks fine but is corrupted and non-recoverable without localstorage.clear

![image](https://user-images.githubusercontent.com/124158/49876738-f853fe80-fdf1-11e8-8e3d-7a2c9a3596ba.png)

**Comment by dustingetz** [comment]
![image](https://user-images.githubusercontent.com/124158/49876773-0c97fb80-fdf2-11e8-9661-30fb6f83549c.png)

**Comment by dustingetz** [comment]
The formula is in play, because if i whack it, we get this correct invalid state:
![image](https://user-images.githubusercontent.com/124158/49876910-4cf77980-fdf2-11e8-9245-0123718e5a6b.png)
For us to get this far, the formula is working properly: 
![image](https://user-images.githubusercontent.com/124158/49876939-5ed91c80-fdf2-11e8-807a-6c889c687b51.png)

**Comment by dustingetz** [comment]
Busted:
![image](https://user-images.githubusercontent.com/124158/49877671-ed01d280-fdf3-11e8-9d07-9d95dcf2a563.png)

**Comment by khardenstine** [comment]
Good assert on blur to prevent staging to nil branches:
https://github.com/hyperfiddle/hyperfiddle/blob/dd612bbf27c28d5a18278a47ade2c981bfe270e7/src/hyperfiddle/actions.cljc#L204

Missing assert when we stage a popover:
https://github.com/hyperfiddle/hyperfiddle/blob/dd612bbf27c28d5a18278a47ade2c981bfe270e7/src/hyperfiddle/actions.cljc#L241-L242

**Comment by dustingetz** [comment]
The bug is that there's no database in scope in the ctx as it is naked. https://github.com/hyperfiddle/hyperfiddle/issues/732

**Comment by dustingetz** [comment]
I recommend we unrevert #732. $ is always in scope until otherwise indicated. Which is consistent with precedent in fiddle/query and fiddle/pull-database. This makes userland simpler – one less place you have to write a formula (and this is a place that happens a lot).

**Comment by dustingetz** [comment]
Per live discussion, Dustin advocated inferring $ always (changing business rules about connection-color and security to also reflect this), and Karl advocates waiting to see in two weeks if the internals check out with this theory. For now I am isolating this $ inference to just this spot.

**Comment by dustingetz** [comment]
The cost of delay is the custom link/formula is still in userland. Reverting #732 will instantly fix that.
