### ISSUE TITLE
broken reaction in form remove!

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#820]
http://tank.hyperfiddle.net/:dustingetz.tutorial!view-post/~entity('$',17592186046224)

Date reacts, but title and markdown do not. This predates the eav context/routing refactor im slamming in.

**Comment by khardenstine** [comment]
Looks like this is a bug in the text controls, notice the date control correctly clears:

Before:
![image](https://user-images.githubusercontent.com/7741805/50016323-d9db3800-ff96-11e8-9ecb-5195a2a03e73.png)

After:
![image](https://user-images.githubusercontent.com/7741805/50016340-e1024600-ff96-11e8-9c98-17a75483c84d.png)


Also if we change the form to splat the form works as expected:
Before:
![image](https://user-images.githubusercontent.com/7741805/50016435-258de180-ff97-11e8-81ef-6248daeb8797.png)

After:
![image](https://user-images.githubusercontent.com/7741805/50016442-2b83c280-ff97-11e8-954e-b3660f3bd8fa.png)
