### ISSUE TITLE
Demo redirects to http://demo.hyperfiddle.net/:hacky-hack-hack/

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#872]
It redirected to please-login/:hacky-hack-hack/, and then after login redirected to /:hacky-hack-hack/
That's pretty bad marketing for that string to ever be seen by a user

![image](https://user-images.githubusercontent.com/124158/52883180-10b90000-3138-11e9-821f-f9ab02234c32.png)

**Comment by dustingetz** [comment]
This is actually catastrophic. It appears that demo has been redirecting to an error message for who even knows how long?

![image](https://user-images.githubusercontent.com/124158/52883115-da7b8080-3137-11e9-9756-c66754f9859e.png)

**Comment by dustingetz** [comment]
Oh I see this is only when you go there directly. Assuming people come by navigating from WWW it is fine

**Comment by khardenstine** [comment]
Fixed in branch net#318
