### ISSUE TITLE
"Loading" stuck when changing :find (but not :where)

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#892]
Toggle db/id here: http://tank.hyperfiddle.net/:seattle!neighborhoods/

**Comment by dustingetz** [comment]
![image](https://user-images.githubusercontent.com/124158/54089146-42d70f80-433c-11e9-9ce1-8a7353220b7a.png)

**Comment by dustingetz** [comment]
![image](https://user-images.githubusercontent.com/124158/54089148-4b2f4a80-433c-11e9-95ba-39e90a3ed7e1.png)

**Comment by dustingetz** [comment]
Happens only when altering :find, does not happen when altering :where

**Comment by dustingetz** [comment]
![image](https://user-images.githubusercontent.com/124158/54373592-ec2b4780-4653-11e9-8bc5-fc5edde3d96e.png)

Something is calling contrib/group-by-unique on loading

**Comment by dustingetz** [comment]
* Removing db/id does not trigger this, only adding it.
* Not an issue in this nested form: http://tank.hyperfiddle.site/:seattle!neighborhood-edit/~entity('$',(:neighborhood!name,'Alki'))

**Comment by dustingetz** [comment]
Bug is not reproducible at oldprod before the big merge, which makes me suspect this series of changes after the merge:

![image](https://user-images.githubusercontent.com/124158/54382130-bb540e00-4665-11e9-8ec1-2c7a5081f196.png)

**Comment by dustingetz** [comment]
![image](https://user-images.githubusercontent.com/124158/54383139-c4de7580-4667-11e9-8f6e-1362b49e7588.png)

**Comment by khardenstine** [comment]
A bisect on prod deploys found the bug was not introduced in any of the above screenshotted commits.  It first appeared in this range of commits:
https://github.com/hyperfiddle/hyperfiddle/compare/7dfd155a1fc371b9fb6ae18022f6d018fc4833cf...885c10a40e000d5466092d9370fcc487fc5edaa4

Reverting this [commit](https://github.com/hyperfiddle/hyperfiddle/commit/7ebe2bd7eca80e509f174adb1781ff315c67ce47) fixes the bug.

**Comment by dustingetz** [comment]
Wow, Karl the killing machine at it again
Do you know why?
ᐧ

**Comment by dustingetz** [comment]
Commented out path does not exhibit bug. if no-splat causes bug.
![image](https://user-images.githubusercontent.com/124158/54638145-b5449f80-4a60-11e9-8f52-c9e7b80b0f29.png)

**Comment by dustingetz** [comment]
This version does NOT exhibit the bug

![image](https://user-images.githubusercontent.com/124158/54638492-87ac2600-4a61-11e9-968d-a2285c73e3c1.png)

**Comment by dustingetz** [comment]
Adding a delay does indeed reintroduce the bug 
![image](https://user-images.githubusercontent.com/124158/54638614-d8bc1a00-4a61-11e9-9274-9eacf6b90d26.png)

**Comment by dustingetz** [comment]
The thing is, there are no f'ing reactions in this file

**Comment by dustingetz** [comment]
I think this is a reagent deepbug – because the if statement is not actually in play – the test steps never involve a splat.

**Comment by dustingetz** [comment]
This is still reproducible in other places
- [x] http://tank.hyperfiddle.site/:seattle!neighborhoods/
- [ ] http://tank.hyperfiddle.site/:dustingetz!counter/

**Comment by dustingetz** [comment]
Remaining issue seems to only be in cases of FindScalar. Various other transitions of find-spec do not seem to trigger this.

**Comment by dustingetz** [comment]
This is caused by an exception during a reaction

**Comment by dustingetz** [comment]
![image](https://user-images.githubusercontent.com/124158/55259737-e3826600-523c-11e9-9058-8453f13f97fb.png)


![image](https://user-images.githubusercontent.com/124158/55259715-d9606780-523c-11e9-9caf-6803a8eb550f.png)

**Comment by dustingetz** [comment]
@khardenstine  please review https://github.com/hyperfiddle/hyperfiddle/commit/d4a8683e3d0f5a83bc82f7aced80abc85fe73fbd

**Comment by dustingetz** [comment]
Seems fixed. Will probably come back. Solution is to replace contrib.reactive gymnastics with track to simplify the reactions.

**Comment by dustingetz** [comment]
More places:
- [ ] http://tank.hyperfiddle.site/:foo!clojurians/ (changed :channel/creator [*] to [:user/name])

![image](https://user-images.githubusercontent.com/124158/55438305-39be1480-556f-11e9-8ab9-0f9df51c56e7.png)

**Comment by dustingetz** [comment]
Any splat to not-splat

**Comment by dustingetz** [comment]
Any splat to not-splat (or at least this one) causes a loading map to mash into the attributes:

![image](https://user-images.githubusercontent.com/124158/55513313-6471a100-5633-11e9-9a6f-3361713cd4a0.png)

**Comment by dustingetz** [comment]
???

![image](https://user-images.githubusercontent.com/124158/55513539-eeba0500-5633-11e9-93af-67824165ee67.png)

**Comment by dustingetz** [comment]
Splat, hard refresh, change splat to :user/name (v quickly so no hydrate), wait for hydrate, clear console, alt-enter:
```
index-result' a:  :fiddle/type
core.cljs:192 index-result' a:  :fiddle/pull-database
core.cljs:192 index-result' a:  :fiddle/pull
core.cljs:192 pull-enclosure-here; pull-enclosure:  [:db/id :channel/name :channel/created :message :data #:message{:_channel [:message/text #:message{:user []}]}]  pull-path:  []
core.cljs:192 pull-enclosure-here; pull-enclosure:  [:db/id :channel/name :channel/created :message :data #:message{:_channel [:message/text #:message{:user []}]}]  pull-path:  []
core.cljs:192 spread-attributes as:  (:db/id :channel/name :channel/created :message :data :message/_channel)
core.cljs:192 pull-enclosure-here; pull-enclosure:  [:db/id :channel/name :channel/created #:message{:_channel [:message/text #:message{:user [:user/name]}]}]  pull-path:  []
core.cljs:192 pull-enclosure-here; pull-enclosure:  [:db/id :channel/name :channel/created #:message{:_channel [:message/text #:message{:user [:user/name]}]}]  pull-path:  []
core.cljs:192 spread-attributes as:  (:db/id :channel/name :channel/created :message/_channel)
core.cljs:192 index-result' a:  :db/id
core.cljs:192 pull-enclosure-here; pull-enclosure:  [:db/id :channel/name :channel/created #:message{:_channel [:message/text #:message{:user [:user/name]}]}]  pull-path:  [:db/id]
core.cljs:192 index-result' a:  :channel/name
core.cljs:192 pull-enclosure-here; pull-enclosure:  [:db/id :channel/name :channel/created #:message{:_channel [:message/text #:message{:user [:user/name]}]}]  pull-path:  [:channel/name]
core.cljs:192 index-result' a:  :channel/created
core.cljs:192 index-result' a:  :message
core.cljs:192 index-result' a:  :message
reporter.cljs:31 CLJS DevTools Error No matching clause: 
core.cljs:192 index-result' a:  :message
reporter.cljs:31 CLJS DevTools Error No matching clause: 
core.cljs:192 index-result' a:  :message
reporter.cljs:31 CLJS DevTools Error No matching clause: 
core.cljs:192 index-result' a:  :message
reporter.cljs:31 CLJS DevTools Error No matching clause: 
core.cljs:192 index-result' a:  :message
reporter.cljs:31 CLJS DevTools Error No matching clause: 
core.cljs:192 index-result' a:  :message
reporter.cljs:31 CLJS DevTools Error No matching clause: 
core.cljs:192 index-result' a:  :message
reporter.cljs:31 CLJS DevTools Error No matching clause: 
reporter.cljs:31 CLJS DevTools Error [object Object] is not ISeqable
reporter.cljs:31 CLJS DevTools Error [object Object] is not ISeqable
core.cljs:192 index-result' a:  :message
reporter.cljs:31 CLJS DevTools Error No matching clause: 
core.cljs:192 index-result' a:  :message
reporter.cljs:31 CLJS DevTools Error No matching clause: 
core.cljs:192 index-result' a:  :message
reporter.cljs:31 CLJS DevTools Error No matching clause: 
core.cljs:192 index-result' a:  :db/id
core.cljs:192 pull-enclosure-here; pull-enclosure:  [:db/id :channel/name :channel/created #:message{:_channel #}]  pull-path:  [:db/id]
core.cljs:192 index-result' a:  :channel/name
core.cljs:192 pull-enclosure-here; pull-enclosure:  [:db/id :channel/name :channel/created #:message{:_channel #}]  pull-path:  [:channel/name]
core.cljs:192 index-result' a:  :channel/created
core.cljs:192 index-result' a:  :message/_channel
core.cljs:192 index-result' a:  :message
reporter.cljs:31 CLJS DevTools Error No matching clause: 
core.cljs:192 index-result' a:  :message
reporter.cljs:31 CLJS DevTools Error No matching clause: 
core.cljs:192 index-result' a:  :message
reporter.cljs:31 CLJS DevTools Error No matching clause: 
core.cljs:192 index-result' a:  :message
reporter.cljs:31 CLJS DevTools Error No matching clause: 
core.cljs:192 index-result' a:  :message
reporter.cljs:31 CLJS DevTools Error No matching clause: 
core.cljs:192 index-result' a:  :message
reporter.cljs:31 CLJS DevTools Error No matching clause: 
reporter.cljs:31 CLJS DevTools Error [object Object] is not ISeqable
reporter.cljs:31 CLJS DevTools Error [object Object] is not ISeqable
core.cljs:192 index-result' a:  :message
reporter.cljs:31 CLJS DevTools Error No matching clause: 
core.cljs:192 index-result' a:  :message
reporter.cljs:31 CLJS DevTools Error No matching clause: 
```

**Comment by dustingetz** [comment]
Missing doall in deep link computation (data.cljc)

One clue may have been a flush! in the middle of the call stack

A bunch of spooky red warnings went away too

**Comment by dustingetz** [comment]
This missing doall in deep link logic fully explains the r/apply mystery from last week, i think

**Comment by dustingetz** [comment]
Seeing this in the Eval work. Flush in callstack ... red reagent warnings ... 
![image](https://user-images.githubusercontent.com/124158/73140803-ef041080-404a-11ea-8400-11ead8a496b6.png)
![image](https://user-images.githubusercontent.com/124158/73140813-004d1d00-404b-11ea-99f8-0c6a3ecc648f.png)
