### ISSUE TITLE
Remove route from peer/partitioned-request

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#91]
If the route could possibly invalidate a partition's ptm then the request would be different because of it (thus invalidating itself).  Also branch-aux should get canned too.

The only things that should be needed are parameters sent to hydrate-request (local-basis, stage, request)

**Comment by dustingetz** [comment]
what is peer/partitioned-request

**Comment by khardenstine** [comment]
Essentially the logic that manages tagging requests with a t value.
It's so the runtime can invalidate responses internally when a user updates the basis/route/staging area.

**Comment by khardenstine** [comment]
Fixed as of:
https://github.com/hyperfiddle/hyperfiddle/commit/d329d3194c1b4d7c504d57c48dee3870efd3a091 via #7
