### ISSUE TITLE
tilde in database name ednish-decodes as #

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#918]
http://domains.hyperfiddle.site/:databases!edit/~entity('$domains',(:database!uri,~uri,'datomic:free:!!datomic:4334!~khardenstine@gmail.com+2'))

![image](https://user-images.githubusercontent.com/124158/55654131-8c414000-57be-11e9-82b9-62c198245e9f.png)

**Comment by khardenstine** [comment]
Duplicate #236
