### ISSUE TITLE
sys-edit-entity--fiddle-links pink dash encapsulates new fiddle/link

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#92]
The new fiddle/link button should not be inside that table's pink box:
![image](https://user-images.githubusercontent.com/7741805/36558173-2bb3761c-17d8-11e8-9488-eef44d1d77fd.png)

Looks localized to that specific screen based on the overflow style's scope:
![image](https://user-images.githubusercontent.com/7741805/36558254-747aaa3c-17d8-11e8-82fd-71f41f433cd6.png)

**Comment by dustingetz** [comment]
i think this is deliberate to allow the following overflow for usability:
![image](https://user-images.githubusercontent.com/124158/36560386-89d23f16-17de-11e8-9d5b-c1cfc50b347b.png)

**Comment by khardenstine** [comment]
This popover no longer exists
