### ISSUE TITLE
stale/can-be-loading is no longer working

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#921]
This needs to be returning false, @khardenstine  can you tell me how to fix this?

![image](https://user-images.githubusercontent.com/124158/56097829-5dfee700-5ec7-11e9-94f0-5154b41e7ddc.png)

This is at a bp from clicking on "datomic" in this screenshot:
![image](https://user-images.githubusercontent.com/124158/56097835-6d7e3000-5ec7-11e9-9808-74e6a56d6de5.png)

**Comment by dustingetz** [comment]
This is blocking the landing page videos

**Comment by dustingetz** [comment]
The bug is that each navigate is now causing "Loading" message flickers, which are supposed to be suppressed.

**Comment by dustingetz** [comment]
I diagnosed this wrong. It's working fine, i think a key changed in ui-from-link or iframe-cmp which is busting the load-cmp too soon, or something like that

**Comment by khardenstine** [comment]
fixed in master
