### ISSUE TITLE
CLI: Multi database doesn't work

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#944]
![image](https://user-images.githubusercontent.com/124158/58569675-930b9280-8204-11e9-902b-2622954f9ee8.png)

**Comment by dustingetz** [comment]
I expected the databases to upsert. Trying again now with actual existing databases (restoring prod)

**Comment by dustingetz** [comment]
Confirmed still broken

![image](https://user-images.githubusercontent.com/124158/58571055-0dd5ad00-8207-11e9-973e-349ab87cb903.png)

**Comment by dustingetz** [comment]
Latest CLI (this morning) – concerning

![image](https://user-images.githubusercontent.com/124158/58572212-44142c00-8209-11e9-97cb-d44448457c87.png)

**Comment by dustingetz** [comment]
Bug was bad query but error was so bad it fooled us too; Resolution may be to improve the error?

![image](https://user-images.githubusercontent.com/124158/58573696-488e1400-820c-11e9-8c18-f9ceb985d187.png)

**Comment by khardenstine** [comment]
#170
