### ISSUE TITLE
Clean up hyperfiddle.api/tx vs hyperfiddle.api/txfn

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#956]
The marked legacy txfn looks preferred over tx.  Not sure why the tx functions need access to the raw link record, other than hiding the dispatching value.

All the context/link* apis fall out if we clean up the hf.api/tx dispatcher.

**Comment by dustingetz** [comment]
Where do they access the raw record?

My idea for cleaning up dispatchers generally requires self-hosted core.match. The rules are pretty complicated. The current way is bad but it at least works on the common patgs

**Comment by dustingetz** [comment]
https://github.com/noprompt/meander may be a better core match that already supports cljc

**Comment by dustingetz** [comment]
https://github.com/hyperfiddle/hyperfiddle/commit/5e0803aa71f79c330b5ea06551c5772e9ec4bf1f

**Comment by dustingetz** [comment]
Karl may be right that the dispatch can tighten up. but not worth further changes as HFQL makes links entirely implicit and context is being rewritten
