### ISSUE TITLE
Iframes are broken in Prod SSR, e.g. docs are broken

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#958]
Hard nav: http://www.hyperfiddle.net/:docs/:getting-started

![image](https://user-images.githubusercontent.com/124158/60440532-02e5b200-9be3-11e9-9569-e2826fc50431.png)

**Comment by dustingetz** [comment]
This is probably specific to hydrate-result-as-fiddle which can be deprecated and removed

**Comment by khardenstine** [comment]
fixed in prod
