### ISSUE TITLE
Schema New Attr typeahead is causing history warnings

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#962]
It doesn't actually navigate anywhere but it is a little wanky

![image](https://user-images.githubusercontent.com/124158/61902975-44166c80-aed8-11e9-88b1-1603901a45af.png)

**Comment by dustingetz** [comment]
Schema editor filter is wonky – i think this above bug has put my browser into a bad state. I filtered by "crm" after staging the above :crm/location and the staging area vanished and came back on refresh (but the attr was in the filtered result)

**Comment by khardenstine** [comment]
fixed in master
