### ISSUE TITLE
new fiddle not working with auto-transact not sure why

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#98]

**Comment by dustingetz** [comment]
- [ ] Radio is glitchy with and without auto-transact
- [ ] can't stage with auto-transact
- [ ] disable auto-transact and stage, see it working (the datomic bad query error which is good)
- [ ] explicitly transact, everything gone now. The redirect maybe? Route still has tempid in it

**Comment by khardenstine** [comment]
Fixed in #114 
Other bullets I believe are all irrelevant now, they should have their own issues if not
